### ISSUE TITLE
"Run tools such as EF..." takes the user to cli tools which don't mention EF

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#111]
_From @moozzyk on June 17, 2016 19:41_

![image](https://cloud.githubusercontent.com/assets/1438884/16162449/6686ace4-3488-11e6-9f2b-36cd82cd36f1.png)

Takes the user to:
https://dotnet.github.io/docs/core-concepts/core-sdk/cli/index.html

which does not mention EF at all since these are basic CLI tools.

_Copied from original issue: aspnet/Templates#620_

**Comment by Eilon** [comment]
_From @mlorbetske on June 28, 2016 17:39_

Let's update the FWLink for this one to point at more EF centric documentation

**Comment by Eilon** [comment]
I think the link is correct. It's talking generally about CLI tools, and just giving an example of EF migrations.

**Comment by moozzyk** [comment]
Must have been fixed since the link used before now returns 404.

**Comment by Eilon** [comment]
Ah ok I checked the current link and it goes to a general CLI tools page.
