### ISSUE TITLE
OrgAuth: Account Controller should return void

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#126]
_From @rustd on June 12, 2015 22:17_

Since https://github.com/aspnet/Mvc/issues/2409 is fixed. We should change the AccountController for SSO/ MultiOrg to return void

_Copied from original issue: aspnet/Templates#104_

**Comment by tonydrake** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tonypeterdrake@gmail.com
    Domain tonydrake.com has exceeded the max emails per hour (101/100 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:41427 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by web240.dnchosting.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1e77C1-003ZYw-B7
	for tony@tonydrake.com; Tue, 24 Oct 2017 16:57:02 -0500
Date: Tue, 24 Oct 2017 14:56:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1508882179;
	bh=7aIpzyzUWCsuZsbYPkvEH1gLbzMIc1dZPERxM6Cfl7g=;
	h=From:Reply-To:To:Cc:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=OF7mB2ZqQ3zlwPKfWpamfR3Oi/QHkkm/vJy9aNHiNw1SPh6X5iAP2Dr5ZVaV+YgtW
	 retmeyM8ttD/6lYmeaug9psaNZ7aczIuMVxUGVQ5GubtK3xubgdkQpb4Rra5fo97Mn
	 tH1DvmjuF3ftRisoTQqFw1G1maPRlNI7qEJcCAF8=

**Comment by Eilon** [comment]
@javiercn - thoughts on this?

**Comment by javiercn** [comment]
Our account controller returns action results to signal the middleware what to do. Using action results makes it easier to unit test and its the recommended pattern. Updating from an MVC5 app will already require you to significantly change the auth code, so I don't think we should neither do this nor that there is value here.

I'm closing it.
