### ISSUE TITLE
AccessDenied.cshtml page has a small bug

### ISSUE THREAD

**Issue by chenzhitong** [aspnet/templating#132]
Views/Account/AccessDenied.cshtml page has a small bug.

This is the default code after the project is created.
<img width="607" alt="image" src="https://user-images.githubusercontent.com/6295602/32085878-339a6920-bb04-11e7-891a-60488b112ef6.png">

h2 this line should be.
`<h2 class="text-danger">@ViewData["Title"]</h2>`

The default code is missing an **@**

**Comment by Eilon** [comment]
Hi @chenzhitong thanks for the report, we just fixed the bug a few days ago! 😄  https://github.com/aspnet/templating/pull/40
