### ISSUE TITLE
Add an option to use yarn instead of npm in new projects

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/templating#139]
Some people prefer yarn to npm. It would be nice to add this as an option users could set when creating a new project.

Ideas:
 - Add it as an option: `dotnet new react --with-yarn`
 - Use https://www.nuget.org/packages/Yarn.MSBuild/ or something similar. This package bundles yarn with it so you don't need a global install of yarn.

**Comment by Eilon** [comment]
@SteveSandersonMS thoughts on this?

**Comment by Eilon** [comment]
No plans to include yarn at this time. We're trying to reduce how much 3rd party content is in the templates.
