### ISSUE TITLE
Include the 'additional-methods.js' in the template

### ISSUE THREAD

**Issue by kichalla** [aspnet/templating#14]
A new jquery-unobtrusive adapter was added for handling validation of file extensions. https://github.com/aspnet/jquery-validation-unobtrusive/commit/e7444c9ab5512d455069815e23b954ce2e7b2518

This adapter uses 'extension' method from the jquery-validation's 'additional-methods.js' file. This file is [already ](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/wwwroot/lib/jquery-validation/dist/additional-methods.js)being downloaded as part of the jquery-validation package. We just need to include it in the template's .cshtml file: https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Views/Shared/_ValidationScriptsPartial.cshtml

cc @dougbu @Eilon

**Comment by Eilon** [comment]
No plans to add it by default. It's left as an exercise to the reader.
