### ISSUE TITLE
Produce launchSettings.json by default for ASP.NET Core projects

### ISSUE THREAD

**Issue by Petermarcu** [aspnet/templating#142]
I ran `dotnet new web` and there was no launchsettings.json. I expected the same output from `dotnet new web` as I get when I do `File->New Project->ASP.NET Core Web Application->Web Application`. Looks like there are a few differences. This causes issues for upstack templates and tools that expect certain things to be available in the base. 

https://github.com/ElectronNET/Electron.NET/issues/30

**Comment by danroth27** [comment]
We will need launchSettings.json for things like HTTPS and specifying the dev hosting environment.

**Comment by danroth27** [comment]
@javiercn

**Comment by javiercn** [comment]
Yeah, launchSettings.json should be the default experience

**Comment by danroth27** [comment]
The proposal here is to produce launchSettings.json by default.

**Comment by SteveSandersonMS** [comment]
@danroth27 @javiercn Could you clarify how things are going to work for published apps? Currently we don't publish the `launchSettings.json` file. If someone creates a brand new project, then runs `dotnet publish -c Release`, then goes to the publish directory and runs `dotnet <app>.dll`, is it going to listen for HTTPS connections? Is there some new default Kestrel behavior that makes this work?

**Comment by javiercn** [comment]
@SteveSandersonMS If you use Kestrel on the edge you need to do additional work to deploy to production, essentially there is new configuration that kestrel will pick-up by default from the appSettings. We haven't figured out how that configuration will look like, but for production scenarios we assume 443 for HTTPS in the absence of information.

When you are behind IIS or any other proxy is the proxy responsible for listening on the public endpoints and 443 is assumed for HTTPS

**Comment by danroth27** [comment]
Regardless, the decision to produce a launchSettings.json by default is independent of how we HTTPS by default. We still want it there for things like setting environment variables.

**Comment by SteveSandersonMS** [comment]
@danroth27 I'm not in any way objecting to creating launchSettings.json by default. I just want to understand how all the scenarios work now, since I often do template work and need to be sure whatever I do fits in with the plan.

@javiercn Today if you publish and run a brand new app locally, it listens for HTTP on port 5000. Do you happen to know where that 5000 number comes from - is this a Kestrel default, or is it in ASP.NET somewhere? Will there be an equivalent high-numbered default HTTPS port (Justin suggested 4430), so you can publish and run with no additional manual steps?

**Comment by javiercn** [comment]
@SteveSandersonMS It's hardcoded in kestrel. There can't be a default for HTTPS as you need a certificate. I'm wondering if it would be worth to have a feature on the set of server features to not do redirection in case there is no https endpoint being listen on.

**Comment by jkotalik** [comment]
@javiercn I don't know if we want to have that feature. If someone intends on redirecting to HTTPS, we shouldn't ever respond with a HTTP page. 
So to be clear, if the client fails to create a certificate, then they can't run any of our samples, correct? I know our current plan is to have certificate creation on first time experience.

**Comment by javiercn** [comment]
https://github.com/aspnet/templating/commit/4d2e642b94ad6c2e152e09005c33bac7543bcf04
