### ISSUE TITLE
Problems with build.cmd command

### ISSUE THREAD

**Issue by RepositoryNY** [aspnet/templating#143]
I have cloned this repository, and run `build.cmd`.

Here is the error in console:

> Using KoreBuild 2.1.0-preview1-15552
> WARNING: dotnet found on the system PATH is 'C:\Program
> Files\dotnet\dotnet.exe' but KoreBuild will use
> 'C:\Users\Yuriy\.dotnet\x64\dotnet.exe'.
> WARNING: Adding 'C:\Users\Yuriy\.dotnet\x64' to system PATH permanently may be
> required for applications like Visual Studio or VS Code to work correctly.
> Adding C:\Users\Yuriy\.dotnet\x64 to PATH
> .NET Core runtime 2.0.0 is already installed. Skipping installation.
> .NET Core SDK 2.1.0-preview1-007042 is already installed. Skipping installation.
> >>> dotnet.exe msbuild @E:\AspNetCoreTemplates\artifacts\msbuild\msbuild.rsp
>   Using lineup Internal.AspNetCore.Universe.Lineup 2.1.0-preview1-27512
>   Using lineup Internal.AspNetCore.Partners.Lineup 2.1.0-preview1-27509
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
>   Pinned 20 package(s) from 2 lineup(s) in 1880ms
> 
> Build FAILED.
> 
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
> C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\modules\KoreBui                                                                                                                ld.Tasks\module.targets(34,5): error KRB4004: PackageReference to Microsoft.AspN                                                                                                                etCore did not specify a version and was not found in any lineup. [C:\Users\Yuri                                                                                                                y\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\KoreBuild.proj]
>     0 Warning(s)
>     10 Error(s)
> 
> Time Elapsed 00:00:03.56
> dotnet.exe failed with exit code: 1
> At C:\Users\Yuriy\.dotnet\buildtools\korebuild\2.1.0-preview1-15552\scripts\com
> mon.psm1:11 char:9
>          throw "$cmdName failed with exit code: $exitCode"
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : OperationStopped: (dotnet.exe failed with exit c
>    ode: 1:String) [], RuntimeException
>      FullyQualifiedErrorId : dotnet.exe failed with exit code: 1
> 

How can I properly use this templates, and create new projects with them?

**Comment by natemcmaster** [comment]
The build.cmd script is currently broken while I'm working on infrastructure changes in aspnetcore. I should have this fixed later.

> How can I properly use this templates, and create new projects with them?

You don't need to build this repo to use our templates. They are bundled "File -> New Project" experience in Visual Studio and `dotnet new` in the .NET Core command-line.

**Comment by RepositoryNY** [comment]
Ok, so how to deal without that script? 

If I type `dotnet new` or choose "File -> New Project" , I can only see standart ASP.NET Core 2.0 templates, where I don't have Aurelia, Knockout and Vue templates, which are [here](https://github.com/aspnet/templating/tree/dev/src/Microsoft.AspNetCore.SpaTemplates/content). How can I build those three templates?

**Comment by natemcmaster** [comment]
Closing as build.cmd should succeed in building new packages locally now. cref #148
