### ISSUE TITLE
Password is posted in clear text in ASP.NET Core Web Application template

### ISSUE THREAD

**Issue by kosa-gyula-77** [aspnet/templating#144]
In Visual Studio Professional 2017 (15.4.1),

1. Select New Project, 
2. choose template 'ASP.NET Core Web Application', 
3. select ASP.NET Core 1.1, 
4. select Web Application (MVC), 
5. choose 'Individual User Accounts' authentication

Actual: On login, the password is posted to the server in clear text. 

Expected: Password is [sent hashed](https://stackoverflow.com/a/21716654/1986541).

**Comment by Eilon** [comment]
Hi, we are updating the ASP.NET Core templates to use HTTPS, which is a best practice. As such, there are no plans to hash the passwords on the client before sending to the server.

cc @blowdart FYI.
