### ISSUE TITLE
Update the jquery unobtrusive script in templates to the latest version

### ISSUE THREAD

**Issue by kichalla** [aspnet/templating#15]
An update was made to the unobtrusive script, so we need to use this latest version
Related issue: https://github.com/aspnet/templating/issues/14

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please handle this? Thanks!

**Comment by Eilon** [comment]
We might want to wait a tiny bit until we know what versions of the jQuery unobtrusive scripts we want to use.
