### ISSUE TITLE
launchSettings.json is missing from 2.1 templates

### ISSUE THREAD

**Issue by danroth27** [aspnet/templating#152]
Looks like `Properties/launchSettings.json` is missing for the 2.1 templates (it's there in the 2.0 templates). As a result specifying `--use-launch-settings.json` doesn't actually add anything to the generated project.

**Comment by SteveSandersonMS** [comment]
> it's there in the 2.0 templates

Where are you seeing that? Also I just tried `dotnet new mvc` against the 2.0.2 SDK and it produced a project with no `launchSettings.json` file.

**Comment by danroth27** [comment]
Sorry, I was referring to the template content in this repo, not the generated template output. The [Properties](https://github.com/dotnet/corefx/issues?q=is%3Aissue+is%3Aopen+directoryservices+label%3Aarea-System.DirectoryServices) content folder is missing in the dev branch.

**Comment by jkotalik** [comment]
The [rel/2.0.3 projects](https://github.com/aspnet/templating/tree/rel/2.0.3/src/Microsoft.DotNet.Web.ProjectTemplates/content/EmptyWeb-CSharp/Properties) in ProjectTemplates have the launchSettings.json file.

**Comment by SteveSandersonMS** [comment]
Got it - thanks for clarifying. I see that it only gets used if you pass the `--use-launch-settings` flag to `dotnet new`.

**Comment by jkotalik** [comment]
Should we also add launchSettings.json to each of the spa templates?

**Comment by SteveSandersonMS** [comment]
Yes, all the web templates (including SPA) should be updated to be consistent about this.

**Comment by Eilon** [comment]
Is this bug a dup of https://github.com/aspnet/templating/issues/142 ? If not, how are they different?

**Comment by danroth27** [comment]
@Eilon this bug tracks that there is literally no launchSettings.json in the 2.1 templates - even if you pass `--use-launch-settings` you aren't going to get one. #142 tracks producing launchSettings.json by default.

**Comment by SteveSandersonMS** [comment]
@javiercn Can this be closed now you implemented it?

**Comment by javiercn** [comment]
Yeah, thanks @SteveSandersonMS
