### ISSUE TITLE
Make launchSettings.json the default and provide an options to exclude it instead

### ISSUE THREAD

**Issue by javiercn** [aspnet/templating#153]
Right now is not the default, so HTTPS redirection won't work correctly.

**Comment by SteveSandersonMS** [comment]
If the app would be created in a broken state without `launchSettings.json`, why allow it to be excluded?

Or is the idea that we replace it with an option like `--suppress-https-redirection` that, if set, eliminates both the HTTPS redirection and launchSettings.json?

**Comment by javiercn** [comment]
You might want to use the new support for kestrel config (pending implementation). If we don't add launchSettings.json we most likely will add kestrel config to the config file.

**Comment by danroth27** [comment]
Dup of #142

**Comment by SteveSandersonMS** [comment]
@javiercn Sorry, I don't understand your comment - I must be missing context, but it's unclear to me how your comment relates to my question. Also, are you saying I should be doing something about this?
