### ISSUE TITLE
Upgrading to bootstrap4?

### ISSUE THREAD

**Issue by kakins** [aspnet/templating#154]
I admit I'm a dummy when it comes to webpack.  However it seems simply updating my package.json's bootstrap value to 4.0.0-alpha.6 just downloads bootstrap 3.3.7 again.  I've seen various tutorials about how to use the newest version of bootstrap, but none that relate directly to how the current spa templates are set up.

**Comment by kakins** [comment]
Well after posting this, I clicked "update package" via the IDE under npm, and at first it seemed to remove bootstrap and failed to install.  I then clicked restore package and it looks like it downloaded version 4.  Is this an issue with the project setup, npm, Visual Studio, all of the above?

**Comment by SteveSandersonMS** [comment]
Update packages using `npm install --save <packagename>[@version]`, so it updates both your `package.json` and `npm-shrinkwrap.json` files consistently.
