### ISSUE TITLE
Websocket errors

### ISSUE THREAD

**Issue by dloukola** [aspnet/templating#156]
I've been trying to run the @SteveSandersonMS angular-cli branch (I understand this is not complete yet), and I get websocket errors constantly. 

Initial load of the site works fine, but hitting refresh takes about 2 minutes to come back with the errors below.

Any ideas?

VM60:164 WebSocket connection to 'wss://localhost:44316/sockjs-node/393/eors52lf/websocket' failed: Error during WebSocket handshake: Unexpected response code: 500
WrappedWebSocket @ VM60:164
WebSocketBrowserDriver @ websocket.js:6
WebSocketTransport @ websocket.js:32
SockJS._connect @ main.js:219
SockJS._receiveInfo @ main.js:193
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
(anonymous) @ info-receiver.js:67
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
(anonymous) @ info-ajax.js:37
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
xhr.onreadystatechange @ abstract-xhr.js:124
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
zone.js:2933 POST https://localhost:44316/sockjs-node/393/de54glzj/xhr_streaming?t=1510753383995 net::ERR_CONNECTION_RESET
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
AbstractXHRObject._start @ abstract-xhr.js:132
(anonymous) @ abstract-xhr.js:21
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
ZoneTask.invoke @ zone.js:488
timer @ zone.js:2040
setTimeout (async)
scheduleTask @ zone.js:2056
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2072
proto.(anonymous function) @ zone.js:1366
AbstractXHRObject @ abstract-xhr.js:20
XHRCorsObject @ xhr-cors.js:8
XhrReceiver @ xhr.js:19
Polling._scheduleReceiver @ polling.js:26
Polling @ polling.js:18
SenderReceiver @ sender-receiver.js:20
AjaxBasedTransport @ ajax-based.js:44
XhrStreamingTransport @ xhr-streaming.js:15
SockJS._connect @ main.js:219
SockJS._transportClose @ main.js:299
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onerror @ websocket.js:54
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
client*:146 [WDS] Disconnected!
close @ client*:146
sock.onclose @ socket.js:15
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:356
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
ZoneTask.invoke @ zone.js:488
timer @ zone.js:2040
setTimeout (async)
scheduleTask @ zone.js:2056
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2072
proto.(anonymous function) @ zone.js:1366
SockJS._close @ main.js:344
SockJS._transportClose @ main.js:303
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
(anonymous) @ sender-receiver.js:28
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
(anonymous) @ polling.js:41
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
(anonymous) @ xhr.js:27
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
xhr.onreadystatechange @ abstract-xhr.js:124
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
XMLHttpRequest.send (async)
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
AbstractXHRObject._start @ abstract-xhr.js:132
(anonymous) @ abstract-xhr.js:21
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
ZoneTask.invoke @ zone.js:488
timer @ zone.js:2040
setTimeout (async)
scheduleTask @ zone.js:2056
ZoneDelegate.scheduleTask @ zone.js:411
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2072
proto.(anonymous function) @ zone.js:1366
AbstractXHRObject @ abstract-xhr.js:20
XHRCorsObject @ xhr-cors.js:8
XhrReceiver @ xhr.js:19
Polling._scheduleReceiver @ polling.js:26
Polling @ polling.js:18
SenderReceiver @ sender-receiver.js:20
AjaxBasedTransport @ ajax-based.js:44
XhrStreamingTransport @ xhr-streaming.js:15
SockJS._connect @ main.js:219
SockJS._transportClose @ main.js:299
g @ emitter.js:30
EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onerror @ websocket.js:54
wrapFn @ zone.js:1166
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
zone.js:2933 GET https://localhost:44316/sockjs-node/info?t=1510753567641 net::ERR_CONNECTION_REFUSED

**Comment by SteveSandersonMS** [comment]
Sorry, since this is not even released as a preview yet, you shouldn't expect it to work. There are runtime changes necessary to make things like Websocket proxying work correctly.

We'll release a preview of the new SPA templates within the next few weeks.

**Comment by georgiosd** [comment]
Any updates on this one? We're in January now so wondering if we have a new release date - this doesn't seem to work in rc1 either

**Comment by DanHarman** [comment]
@dloukola thanks - I just tried upgrading the nuget packages to the preview 2 version on a react project from 2.0.0 and it still has the same problem, but I'm still on the release sdk so I have a feeling that may be my issue.

**Comment by dloukola** [comment]
@DanHarman I think you need to be on 2.1 sdk. We upgraded even though working with preview stuff can many times be very painful.
