### ISSUE TITLE
Determine the TFM templates need to target and be tested for in 2.1

### ISSUE THREAD

**Issue by pranavkm** [aspnet/templating#159]
Currently templates target `netcoreapp2.0` and we additionally test them in `net461`. We need some guidance about what TFMs we'd build and test them for for the next release.

**Comment by pranavkm** [comment]
cc @Eilon

**Comment by Eilon** [comment]
@richlander / @KathleenDollard - for .NET CLI SDK release associated with the 2.1 runtime, what TFMs do the console template target? Just netcoreapp2.1? Just 2.0? Both, via an option?

We'll presumably want to do the same thing for ASP.NET Core in the 2.1 timeframe.

**Comment by jbagga** [comment]
We now target netcoreapp2.1 https://github.com/aspnet/templating/commit/886a9857262ac664b7fefe8b6fdfa29f063adc45
cc @Eilon

**Comment by Eilon** [comment]
netcoreapp2.1 is all we need, so closing. Thanks!
