### ISSUE TITLE
Problem with button

### ISSUE THREAD

**Issue by NorDroN** [aspnet/templating#163]
@SteveSandersonMS I've tried new angular template and noticed that this button doesn't work. I see 3 ways for fix:
1) add bootstrap.js and jquery.slim.js (but i thing it not so good idea)
2) add package like ng-bootstrap
3) remove this button

<img width="372" alt="screenshot_68" src="https://user-images.githubusercontent.com/5458276/33097795-5059c304-cf1c-11e7-85e7-111cf24090c7.png">

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. I'll track this within https://github.com/aspnet/JavaScriptServices/issues/1288, so closing it here.
