### ISSUE TITLE
[question] angular new template released ng cli 1.5.1?

### ISSUE THREAD

**Issue by stephenlautier** [aspnet/templating#165]
I see the template update for angular, however, I'm not sure if I'm missing something in order to update it or it's not released yet. 
Is it released? if so how to update it?

I saw the following template nugets 
https://www.nuget.org/packages/Microsoft.AspNetCore.SpaTemplates (contains aurelia etc...)
https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates (contains angular)

The Aurelia one seems to be updated lately, however, the angular doesn't. Is it simply not released yet? Thanks.

**Comment by SteveSandersonMS** [comment]
The new Angular CLI (1.5.4)-based template isn't yet released, but you can try out a pre-preview of it: https://github.com/aspnet/JavaScriptServices/issues/1288#issuecomment-346003334

**Comment by stephenlautier** [comment]
Thanks, i had missed that one
