### ISSUE TITLE
TOTP asp.net Identity ManageController.EnableAuthenticator  AddModelError 

### ISSUE THREAD

**Issue by danroth27** [aspnet/templating#166]
_From @arlenniu on November 25, 2017 13:14_

public async Task<IActionResult> EnableAuthenticator(EnableAuthenticatorViewModel model)

error------
 if (!is2faTokenValid)
            {
                ModelState.AddModelError("**model.Code**", "Verification code is invalid.");
                return View(model);
            }

ok----
 if (!is2faTokenValid)
            {
                ModelState.AddModelError("**Code**", "Verification code is invalid.");
                return View(model);
            }

_Copied from original issue: aspnet/Mvc#7084_

**Comment by danroth27** [comment]
_From @Eilon on November 27, 2017 18:55_

@blowdart any ideas on this? Is it a bug in the template?

**Comment by danroth27** [comment]
_From @blowdart on November 27, 2017 19:0_

Uh, @danroth27 ?

**Comment by jbagga** [comment]
Testing with 2.0.0:

There is no bug in the template as far as I can tell. The ModelState expects `Code` as the key and the template provides that correct key to add the error to.

@arlenniu can you elaborate what the issue you're hitting is? Which SDK are you using? Are you able to provide more context/sample related to your scenario?

**Comment by jbagga** [comment]
@arlenniu Closing for now. Please feel free to reopen this issue with more information
