### ISSUE TITLE
KnockoutTemplate_Works_NetCore test flaky on VS

### ISSUE THREAD

**Issue by jbagga** [aspnet/templating#176]
`KnockoutTemplate_Works_NetCore` test fails with the following error when run as part of a test run in VS

Expected: Weather forecast
Actual:   Counter

If the test is run by itself, it passes.

Possible race condition? https://github.com/aspnet/templating/blob/dev/test/Templates.Test/SpaTemplateTest/SpaTemplateTestBase.cs#L72 and https://github.com/aspnet/templating/blob/dev/test/Templates.Test/SpaTemplateTest/SpaTemplateTestBase.cs#L82.

cc @Eilon @SteveSandersonMS

**Comment by Eilon** [comment]
@SteveSandersonMS can you take a look?

**Comment by SteveSandersonMS** [comment]
The next step will be to remove the sources and tests for that template following [this announcement](https://github.com/aspnet/Announcements/issues/289).

**Comment by Eilon** [comment]
Ah, yes, let's get those deleted.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please look into this? Thanks!

**Comment by kichalla** [comment]
https://github.com/aspnet/templating/commit/69f52cc3b6dee462fa76d471478f287565da3ad0
https://github.com/aspnet/templating/commit/88f8f977022681a15d3d6700ac311cc01aaa9cf2

**Comment by natemcmaster** [comment]
Should Microsoft.AspNetCore.SpaTemplates also be removed from the 2.0.x patches?

**Comment by Eilon** [comment]
@natemcmaster I think it's fine to keep it there.
