### ISSUE TITLE
Bump jQuery version up

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/templating#18]
_From @peterblazejewicz on February 3, 2017 20:52_

e.g.:
https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-FSharp/bower.json#L6

The 2.2.3 works just fine:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/bower.json#L6

_Copied from original issue: dotnet/templating#249_

**Comment by mlorbetske** [comment]
@sayedihashimi @phenning should we get these updated & updated in aspnet/templates as well?

**Comment by mlorbetske** [comment]
_From @peterblazejewicz on February 3, 2017 21:25_

Well, there is `2.2.4` on `aspnet cdn` already:
https://www.asp.net/ajax/cdn#jQuery_Releases_on_the_CDN_0
```html
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js" integrity="sha384-rY/jv8mMhqDabXSo+UCggqKtdmBfd3qC2/KvyTDNQ6PcUJXaxK1tMepoQda4g5vB" crossorigin="anonymous"></script>
```

**Comment by Eilon** [comment]
Hold on, I think @DamianEdwards and I need to triage this first, no? Or was there a separate discussion on this?

**Comment by jbagga** [comment]
@mkArtakMSFT and @DamianEdwards had a discussion I believe. I will be updating jQuery to 3.3.1 btw (the latest)

**Comment by Eilon** [comment]
Just chatted with @DamianEdwards and in order for this to work we have to update Bootstrap to the latest patch version of the current major/minor we're using, or else it won't work.

We also have to update some license info to use the new version. I'll provide the new license info, and it'll need to go in as part of the PR you send.

**Comment by jbagga** [comment]
We currently have bootstrap 3.3.7. The next version is 4.0.0. Trying to get a version in this range: 3.3.0 <3.4.0 does not change the version to a patch after 3.3.7. @DamianEdwards Is there a patch version after 3.3.7 I should be able to update the templates to?
Updating to 4.0.0 will be more involved. There are breaking changes.

**Comment by Eilon** [comment]
Yeah we don't want Bootstrap 4.x yet. @DamianEdwards had said that we need the latest patch of the current we're using, which already seems to be 3.3.7 per their GitHub repo. So maybe that's already fine?

**Comment by peterblazejewicz** [comment]
You need to fit into this sem-ver:
https://github.com/twbs/bootstrap/blob/v3.3.7/bower.json#L32
that AFAIK resolves  to `<4.0.0`
Thx!

**Comment by DamianEdwards** [comment]
If you use a bootstrap version that's too low, with jQuery 3.x, you'll get an error printed in the browser console telling you. I believe 3.3.7 is the version where they added support for jQuery 3+ so we should be OK, but of course we just need to verify in the running app.

**Comment by jbagga** [comment]
I don't see any console logs in the browser with the PR I sent above updating jQuery to 3.3.1 and not updating bootstrap. @Eilon let me know what license info needs to change
