### ISSUE TITLE
Go back to server selected listening ports in AspNetCoreProcess

### ISSUE THREAD

**Issue by javiercn** [aspnet/templating#181]
Revert the change below (adding an HTTPS url to it instead) and modify the base url of the http client to replace 127.0.0.1 by localhost so that we don't run into certificate errors.

```
{ "ASPNETCORE_URLS", "http://127.0.0.1:0" }
{ "ASPNETCORE_URLS", $"http://localhost:{_httpPort};https://localhost:{_httpsPort}" },
{ "ASPNETCORE_HTTPS_PORT", $"{_httpsPort}" }
```

**Comment by mkArtakMSFT** [comment]
@javiercn , I've put this in preview2 milestone. Please let me know if this should be prioritized higher.
