### ISSUE TITLE
New Templates

### ISSUE THREAD

**Issue by virzak** [aspnet/templating#189]
What are the prerequisites for previewing the new templates? Are there any instructions?
They seem to be dependent on AspNetCore 2.1.0-preview1, but other than getting the sdk from  dotnet.myget.org, I wasn't sure  what to do next. VS Preview couldn't build the new project.

Please advise.

**Comment by virzak** [comment]
Also, will typescript be dropped from future templates?

**Comment by cvanem** [comment]
I believe this is what you are looking for:
https://github.com/dotnet/templating

**Comment by virzak** [comment]
@cvanem that's the repository. I have the source code. My questions are:
1 how to run it
2 where did typescript go

Thanks

**Comment by virzak** [comment]
@cvanem Thanks. Exactly what I was looking for. Names are so similar, almost confusing.

I ran dotnet new3 -i Q:\Code\Libraries\aspnet-templating\
When I restore that, the project file is missing.

Just wanted to get a sense of general direction.

If I start a new front-end heavy project, should I be going with create-react-app or with the current reactredux template?

Thanks

**Comment by cvanem** [comment]
I'm not sure how to actually run it. I got about half way through and gave up.  I would go with the current reactredux template.  I believe the new reactredux template preview uses the create-react-app module, at least from what I remember when I looked at the updates.  I haven't had a chance to get into it further than that.

**Comment by virzak** [comment]
@SteveSandersonMS can you weigh in on this please?

**Comment by SteveSandersonMS** [comment]
@virzak Prerequisites and installation instructions are at https://docs.microsoft.com/en-us/aspnet/core/spa/. You don't need to clone any repos or use `dotnet new3`.

> Also, will typescript be dropped from future templates?

No, it's fundamental to the Angular template, and still useful in most of the others (notably excluding React, since it's not standard in Create React App).

**Comment by virzak** [comment]
@SteveSandersonMS thanks.

Could you share the long term goals for specifically reactredux template?
Do you have plans to add server-side prerendering? typescript?
Assuming typescript will come when CRA implements it.

We're in the beginning of a project not due in a while. Should we:
1) Go with older stable templates and risk being outdated
2) Go with newer and sacrifice typescript and  server-side prerendering

**Comment by SteveSandersonMS** [comment]
The goal is to be aligned with CRA. If CRA gets TypeScript and/or SSR options, we'll make use of them.

**Comment by virzak** [comment]
@SteveSandersonMS That means that our existing reactredux projects and components we wrote for them now need to be ported to ES6, just to move then back to Typescript later when CRA it. 

Not sure why Microsoft would want to cut its own language from its template, just to rely on Facebook to implement support for it.

I added Typescript support to the latest templates. Please feel free to integrate it into your repository.

https://github.com/virzak/CRA.Typescript.Dotnet.ProjectTemplate
