### ISSUE TITLE
Bump jQuery.Validate version up

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Templating#19]
_From @peterblazejewicz on February 3, 2017 20:53_

E.g.:
https://github.com/dotnet/templating/blob/master/template_feed/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-FSharp/bower.json#L7

The 1.15.0 version works just fine with scaffolded content:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/bower.json#L7

_Copied from original issue: dotnet/templating#250_

**Comment by mlorbetske** [comment]
@sayedihashimi @phenning should we get these updated & updated in aspnet/templates as well?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
