### ISSUE TITLE
IConfigurationRoot over IConfiguration in templates?

### ISSUE THREAD

**Issue by guardrex** [aspnet/templating#193]
The templates are using `IConfiguration` ([example](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Startup.cs#L40)), but the [Configuration](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/index) topic examples use `IConfigurationRoot`. This caused a bit of confusion for a reader of the topic. We'll address the doc issue explaining the difference, but I'm wondering if the templates should be using `IConfigurationRoot` throughout?

cc/ @HaoK

**Comment by HaoK** [comment]
The only reason you really ever need IConfigurationRoot is if you want to reload config, or want access to the individual providers that make up the config, neither of these two situations are common

**Comment by guardrex** [comment]
@HaoK Thanks ... I'll open a doc issue then, and we can discuss explaining it in the Configuration topic.
