### ISSUE TITLE
Unhandled Exception: User Denied Access

### ISSUE THREAD

**Issue by jbagga** [aspnet/templating#194]
Repro:
Set up Facebook Login
On the Facebook login page, press "Not Now"

Results in the following error being displayed
![unhandledexceptionuserdeniedaccess](https://user-images.githubusercontent.com/6234561/33912265-0bb65ab2-df4a-11e7-9b7f-ce8b5154fdaa.PNG)

Are there special set up instructions that anyone using the template needs to follow to not error out in this scenario and gracefully redirect back to the login page? 

cc @HaoK @Eilon

**Comment by HaoK** [comment]
Yeah we have an issue tracking this, its a known painpoint: https://github.com/aspnet/Security/issues/1165
