### ISSUE TITLE
Unhandled Exception: Missing Oauth Token

### ISSUE THREAD

**Issue by jbagga** [aspnet/templating#195]
Repro:
Set up Twitter Login
On the Twitter Login page, click on the Cancel button and then Return to {Your app name}

The following error is displayed:
![unhandledexceptionmissingoauthtoken](https://user-images.githubusercontent.com/6234561/33912866-529203f8-df4c-11e7-8077-94386378cd47.PNG)

cc @Eilon @HaoK

**Comment by HaoK** [comment]
You can probably dupe this/track via https://github.com/aspnet/Security/issues/1165 as well
