### ISSUE TITLE
Pass ASP.NET Core Appsettings Values to Angular

### ISSUE THREAD

**Issue by NorDroN** [aspnet/templating#197]
Hi!
How can I pass ASP.NET Core Appsettings Values to Angular (e.g. https://elanderson.net/2017/10/pass-asp-net-core-appsettings-values-to-angular/ ) in new template with index.html?

**Comment by mkArtakMSFT** [comment]
Hi @NorDroN , you can expose an API from the server and call it from the client to retrieve whatever is required. /cc @SteveSandersonMS

**Comment by NorDroN** [comment]
@mkArtakMSFT, I know about this, but I'd like to get some parameters without request, e.g. value of ASPNETCORE_ENVIRONMENT or another options which depends on value of ASPNETCORE_ENVIRONMENT

**Comment by SteveSandersonMS** [comment]
@NorDroN It follows from Angular CLI conventions that Angular is responsible for returning the entire initial HTML page. As such, the ways to use server-side code when serving the initial HTML page are:

* Using SSR. You can put in arbitrary logic then. Read more about SSR at https://docs.microsoft.com/en-us/aspnet/core/spa/angular#server-side-rendering
* Or, by using ASP.NET middleware to intercept requests for the initial HTML page and then modify the output (either by capturing the HTML that was being served and then manipulating it as a string, or by just overriding the response for those requests to serve some completely customised content). You can read more about ASP.NET middleware at https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware
