### ISSUE TITLE
Use the 'main' element in _Layout.cshtml

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/templating#2]
Use the semantic `main` element in the `_Layout.cshtml` file.

The semantic `header` element could be used too.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.

**Comment by vanillajonathan** [comment]
What is the rationale for not adopting semantic elements for the modern web?

https://caniuse.com/#feat=html5semantic

**Comment by Eilon** [comment]
It seems like a fairly minor improvement in the template.

**Comment by vanillajonathan** [comment]
Minor improvements are improvements too. If it is minor, then it should be quick and easy to implement.
It would encourage a more semantic web. If someone doesn't like it, they could always revert back to using old `div` elements.
