### ISSUE TITLE
The templates favicon

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/templating#206]
_From @guardrex on October 3, 2017 2:56_

I don't see a favicon here, so this might be the wrong place to ask. The `dotnet new` templates favicon isn't attractive ...

![favicon1](https://user-images.githubusercontent.com/1622880/31107913-7c7aba48-a7bb-11e7-9f0c-45961a01cb7c.png)

Any interest in using the *really nice looking* MS logo favicon? (or *anything else* :smile:)

![favicon2](https://user-images.githubusercontent.com/1622880/31107919-8d047f02-a7bb-11e7-9384-212a0b090dff.png)

_Copied from original issue: dotnet/templating#1262_

**Comment by mlorbetske** [comment]
_From @PureKrome on October 3, 2017 5:35_

one of these should be the `favicon`

(yes, reduce size, pixelate, etc)

![](https://dnfwebsitewusproduction.blob.core.windows.net/media/Default/_Profiles/9079eeb0/af4f35b8/at-dotnet-bot.png?v=636154283130000000)

![](http://images.danielwmoore.com/wp/MS-ninjacat-unicorn-office-xbox-windows-bing.png)

**Comment by mlorbetske** [comment]
_From @guardrex on October 3, 2017 5:40_

They both :guitar: *ROCK* :guitar:!

I know it's a small thing, but I think MS should make a statement here. Hit them with a favicon that everyone can be proud of.

**Comment by mlorbetske** [comment]
_From @ctolkien on October 3, 2017 5:46_

Here is my vote:

![image](https://user-images.githubusercontent.com/515955/31111520-52814e60-a85a-11e7-9e35-58923f7e6365.png)

#neverforgot

In all seriousness. I don't think a favicon should be shipped in the templates. They should be things you _build_ on, not things you need to remove and/or entirely replace.

**Comment by mlorbetske** [comment]
_From @guardrex on October 3, 2017 5:51_

The thing about the *favicon.ico* is that browsers will (often) just check the base URL (domain) for it. It kind'a makes them "happy" :smile: if it's just there. If we'll provide it, then let's see something nice there.

**Comment by guardrex** [comment]
@natemcmaster @jbagga Is this under consideration for 2.1. The little dot.net robot (or something) would be soooo much nicer than what we have now imo. It would help make our doc samples pop if we had something cool up there.

**Comment by ctolkien** [comment]
My reasons for voting removal:

* Browsers cache this _really_ aggressively - if the wrong favicon gets loaded in, it can be really difficult to get rid of it or have it update. I swear for just about every project we've done, there has been a "why isn't the bloody favicon showing up?!"
* Favicons are now much more complex than a single icon. Different DPI modes, `apple-touch-icon`, `mask-icon`, `manifest.json`, etc..

To reiterate - the templates should be a base to build from, not be a "half baked" website that you need to pull apart. We already have a bunch of noise to deal with (outdated versions of Bootstrap, etc.), this just adds to it.

**Comment by natemcmaster** [comment]
cc @Eilon for triage

**Comment by Eilon** [comment]
We will review this in the next template triage, but for the reasons mentioned by others, we are very unlikely to add this.

**Comment by guardrex** [comment]
> for the reasons mentioned by others, we are very unlikely to add this.

This issue isn't about "adding" a favicon (adding size/type versions or even necessarily removing it). The question is about *replacement*. The current favicon is *ugly as hell* imo. :smile: I'm asking for consideration on an eye-pleasing dot.net robot dude or some similarly nice looking replacement. Specifically, I'm asking because the doc samples look bad with this favicon on display.

**Comment by poke** [comment]
For the reasons pointed out by @ctolkien, can we at least *remove* the current favicon until we have a clearer plan on how to move forward?

**Comment by Eilon** [comment]
Ah, I forgot there already was one. I think the only reason we ever added one was to avoid all the HTTP 404's that you will get if it isn't there.

**Comment by ctolkien** [comment]
>I think the only reason we ever added one was to avoid all the HTTP 404's that you will get if it isn't there.

Sure, but you'll get a half dozen iOS specific 404's now anyway. (iOS has gotten better at this in more recent versions... but still).

**Comment by Eilon** [comment]
Yeah times have changed, so it's worth considering.

BTW I find the 404's most annoying during local web dev and I see the logs streaming in from the console. So, it's only a desktop browser (Chrome/Edge/whatever), so the number of favicons they look for is I think fairly limited.

**Comment by guardrex** [comment]
If it's removed, then @Rick-Anderson might approve one for our doc samples (so we would add it when building a sample), which would make me happy.

**Comment by Eilon** [comment]
Closing because for the reasons mentioned at https://github.com/aspnet/templating/issues/206#issuecomment-361399077, we do want a favicon, so we can't delete it completely. As far as what to put, we don't want to put a Microsoft or .NET logo because that would imply the site being built is associated with those.

Ultimately, each site author needs to come up with their own logo and use that, so we can't do this automatically at template creation time.

**Comment by guardrex** [comment]
> that would imply the site being built is associated with those.

That's a very good reason. However ......

![uglyfavicon](https://user-images.githubusercontent.com/1622880/35711620-771918f6-0783-11e8-88e4-bfbc2b7e9e0c.png)

really? ... *REALLY*??? :smile: lol .... It doesn't need to be an image associated with the Foundation or MS. Certainly something better than that could have been devised.

**Comment by Eilon** [comment]
Yeah it's not a beautiful icon, but given that we expect people to swap it out anyway, it doesn't matter a whole lot...

**Comment by guardrex** [comment]
... but in terms of doc samples, which do prominently represent the framework. We're forced to use the templates for the samples. This one doesn't do anything for my *beautiful* doc samples. I guess it's possible that we could be granted permission for doc samples to use a different icon. 

I'm not too concerned about it, of course. I know it doesn't really matter. I just think that if there is an option, then why not? Everything surrounding ASP.NET Core *should look amazing*, and this icon just doesn't cut it.

**Comment by Eilon** [comment]
Your dinosaur icon looks pretty cool. Go ahead and use that in the docs 😄

**Comment by PureKrome** [comment]
![](https://78.media.tumblr.com/00db1814b3e29b4373420806dcfc7487/tumblr_inline_n1zwiryPoQ1solpjm.gif)

![](https://78.media.tumblr.com/43e63461d1e3f22a49b18dbf15227a1d/tumblr_inline_n3t10oQfIh1solpjm.gif)
