### ISSUE TITLE
Consider adding an option to the MVC auth template that only does cookie auth without OIDC

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/templating#21]
_From @danroth27 on May 15, 2017 21:52_

We had some requests to provide an option for only doing cookie auth with the OIDC stuff:

https://github.com/aspnet/Identity/issues/1187#issuecomment-301602256

We should see based on the preview1 feedback how many folks want this and react accordingly.

Daniel Roth

_Copied from original issue: dotnet/templating#800_

**Comment by mlorbetske** [comment]
_From @Ponant on May 15, 2017 22:4_

Somewhat related (feedback on preview 1)
https://github.com/aspnet/tooling/issues/1040
https://github.com/aspnet/tooling/issues/1041
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/422

**Comment by danroth27** [comment]
We ended up pushing the in app OIDC support out of 2.0
