### ISSUE TITLE
Routes using query string parameters don't work in the Knockout-CSharp template

### ISSUE THREAD

**Issue by Bumbolio** [aspnet/templating#215]
I attempted to register a route that had a query string parameter but crossroads wasn't picking it up.  Here is an example route.  
```
{ url: 'linkaccount{?query}', params: { page: 'streaming-services' } },
```
The problem was that the query string portion of the url was not included when invoking `crossroads.parse()`.  By including `document.location.search` in the string being passed to `crossroads.parse()`, this issue is resolved.  Followed the History.js example from the [Crossroads documentation](https://github.com/millermedeiros/crossroads.js/wiki/Examples#using-with-historyjs). 

Example fix:
```
crossroads.parse(history.location.pathname + document.location.search);
```
```
this.disposeHistory = history.listen(location => crossroads.parse(location.pathname + document.location.search));
```

I can send a pull request if needed, but I couldn't reach the site to sign up as a contributor (https://cla2.dotnetfoundation.org/).

**Comment by Bumbolio** [comment]
I went a head and opened PR #216 with a proposed fix.

**Comment by SteveSandersonMS** [comment]
See #216 for info
