### ISSUE TITLE
Add fallback css and js files for Razor Pages template

### ISSUE THREAD

**Issue by jbagga** [aspnet/templating#217]
The Razor Pages template is missing some min files:

1. lib/bootstrap/dist/css/bootstrap.min.css
2. lib/bootstrap/dist/js/bootstrap.min.js
3. lib/jquery/dist/jquery.min.js

This is only a problem for the offline template creation scenario.

**Comment by mkArtakMSFT** [comment]
@jbagga, please confirm those should be included in the templates before actually including them. Thanks!

**Comment by jbagga** [comment]
@phenning Any idea why only Razor Pages was missing some min files in aspnet/Templates repo? It was carried over to templating and was discovered as part of offline testing.

MVC: https://github.com/aspnet/Templates/tree/dev/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/wwwroot/lib/bootstrap/dist/css
RazorPages: https://github.com/aspnet/Templates/tree/dev/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/RazorPagesWeb-CSharp/wwwroot/lib/bootstrap/dist/css

**Comment by phenning** [comment]
@jbagga  It looks like they were never included when the template was first authored by @glennc:

https://github.com/dotnet/templating/tree/rel/2.0.0-servicing/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/RazorPagesWeb-CSharp/wwwroot/lib/bootstrap/dist/css
