### ISSUE TITLE
Specify DebugType = Full for desktop targeting projects < net471 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/templating#222]
We made a change to Mvc as part of 2.1.0-preview to use the app's DebugType setting to determine the view's pdb type. The SDK defaults this value to `portable` which does not correctly work for desktop applications targeting < net471. We'll workaround this in our templates by explicitly specifying `DebugType = Full` in our desktop templates when the tfm < net471

**Comment by pranavkm** [comment]
cc @rynowak \ @DamianEdwards

**Comment by pranavkm** [comment]
We never got around to addressing this. That said, I'm not entirely sure how we would use the TFM version to pivot this feature. Could we just have the template set `DebugType = Full` if the TFM is desktop?

**Comment by Eilon** [comment]
Hmm yeah this is a bit gross...

**Comment by pranavkm** [comment]
Moving this to the preview2 milestone so we don't missing triaging this.

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please handle this? Thanks!

**Comment by pranavkm** [comment]
@DamianEdwards ping - confirming that this is something we'd like to do for desktop templates. If you'd like to do a refresher on why we need this I can drop by and go over.

**Comment by Eilon** [comment]
@pranavkm yeah @DamianEdwards wants this.

**Comment by pranavkm** [comment]
Looks like support for portable pdbs did not land in 4.7.1. It'll be available in 4.7.2, but the app has to opt in it to it - https://github.com/dotnet/designs/blob/master/accepted/diagnostics/debugging-with-symbols-and-sources.md#stack-traces. 

> The feature is only enabled by default for applications built against .NET Framework 4.7.2. Applications built against previous .NET Framework versions can add the following configuration entry to their App.config files in order to enable reading source information from Portable and Embedded PDBs when running on .NET Framework 4.7.2:

So the plan of action is to enable this by default for all desktop targeting projects. I filed https://github.com/aspnet/Home/issues/2956 to see if we can make the experience better for portable pdbs.

**Comment by pranavkm** [comment]
In addition to changing the DebugType, we should also explicitly reference the `Microsoft.DiaSymReader.Native` package. According to the Roslyn folks, using this package is the recommended way to get a reference to the DiaSymReader component that is required to produce full pdbs. The template seems like a better place to add this reference rather than adding a reference to `Microsoft.AspNetCore.Mvc.Razor` since it's only ever used when generating full pdbs.

**Comment by pranavkm** [comment]
Spoke to the powers to be - we'll reference the package from Razor.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/templating/commit/ade5ae534d27a2a0f5e4a5c02ee4f52bde2072a9
