### ISSUE TITLE
Link on Razor Pages individual auth template page GenerateRecoveryCodes is broken

### ISSUE THREAD

**Issue by pranavkm** [aspnet/templating#226]
There's a bug in the 2.0.5 Razor Pages individual auth template where the link in GenerateRecoveryCodes.cshtml is incorrect:

```
<p>
    Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key
    used in an authenticator app you should <a asp-action="ResetAuthenticatorWarning">reset your authenticator keys.</a>
</p>
```

Needs to be changed to

```
<p>
    Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key
    used in an authenticator app you should <a asp-page="./ResetAuthenticator">reset your authenticator keys.</a>
</p>
```

**Comment by pranavkm** [comment]
Tracking fixing this in the Identity repo via https://github.com/aspnet/Identity/issues/1558.

**Comment by pranavkm** [comment]
Broken link is fixed in Identity UI - https://github.com/aspnet/Identity/commit/e44cba9b752cf54ef75504051d291ae299a17779#diff-f6ffc3b753a4210ef639736b520f99daR19. Using this to track porting it for 2.0.x

**Comment by Eilon** [comment]
This patch is **approved** for the Feb 2018 patch. Please send a PR to the appropriate branch, get it reviewed, and merge.

Please consider adding a [quirks-mode switch](https://github.com/aspnet/Home/wiki/Quirks-mode-switches-in-patches) for this change.
