### ISSUE TITLE
Merge release/2.0.0 back to dev

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/templating#228]
The 2.0.5 patch went out today. To make sure we are keeping dev and release branches in sync, let's merge the release/2.0.0 branch back to dev.

FYI I started to do this, but there were a bunch of changes that I'm not familiar with. Not sure what should be brought back into dev or not.

cc @pranavkm

**Comment by pranavkm** [comment]
Merged in to release/2.1 in https://github.com/aspnet/templating/commit/a6eb93cfdd10c387c80fe67d9be7b8e006515fbb
Merged in to dev in https://github.com/aspnet/templating/commit/b0bb1980433eaed138977e7dbaec39c0193ff9a4
