### ISSUE TITLE
Update SPA template package IDs for 2.1

### ISSUE THREAD

**Issue by danroth27** [aspnet/templating#230]
If you install an SDK that carries the 2.1 ASP.NET Core SPA templates then the 2.0 templates disappear in VS. This is because the package ID for the SPA templates is not unique between 2.0 and 2.1 so the 2.0 templates get updated to be 2.1 templates. We should create separate version specific package IDs for the SPA templates like we do for the other web templates.

**Comment by Eilon** [comment]
@SteveSandersonMS - can you get this done for preview1?

cc @mlorbetske / @seancpeters FYI

**Comment by SteveSandersonMS** [comment]
Yes, definitely.
