### ISSUE TITLE
Set MVC compat version to 2.1 in the 2.1 templates

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#235]
Compat switches for MVC were introduced in https://github.com/aspnet/Mvc/pull/7142.

Presumably, the 2.1 templates should set the compat mode to 2.1, because otherwise the default would be the 2.0 behavior.

@rynowak - what are your thoughts on the recommended way to set the switch? Is there (or should there be) a config-based way to set it? Or just do it in code in `.AddMvc(...)`?

cc @danroth27 @DamianEdwards

**Comment by rynowak** [comment]
It should be in code.

**Comment by Eilon** [comment]
cc @mkArtakMSFT FYI
