### ISSUE TITLE
Appveyor reports NS_ERROR_FILE_NOT_FOUND warnings on PR builds

### ISSUE THREAD

**Issue by jbagga** [aspnet/templating#237]
~1. The build does not install the runtime store and Travis tests fail with the following:~
```
ASP.NET process exited without listening for requests.
[xUnit.net 00:03:53.1964560]       Output: 
[xUnit.net 00:03:53.1966060]       Error: Error:
[xUnit.net 00:03:53.1967550]         An assembly specified in the application dependencies manifest (3a3a8d81df5f425fb0f78a747f1d57b4.deps.json) was not found:
[xUnit.net 00:03:53.1968950]           package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.1'
[xUnit.net 00:03:53.1970390]           path: 'lib/netstandard2.0/Microsoft.AspNetCore.Antiforgery.dll'
[xUnit.net 00:03:53.1971820]         This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
[xUnit.net 00:03:53.1975090]           aspnetcore-store-2.0.3.xml
```

https://travis-ci.org/aspnet/templating/jobs/330125248#L1803

2. The Appveyor build reports a warning
```
addons.xpi	WARN	Error parsing extensions state: [Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) 
[amIAddonManagerStartup.readStartupData]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  
location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm :: loadExtensionState :: line 1554"  data: no] Stack trace:
loadExtensionState()@resource://gre/modules/addons/XPIProvider.jsm:1554 < getInstallState()@resource://gre/modules/addons/XPIProvider.jsm:1589 < checkForChanges()@resource://gre/modules/addons/XPIProvider.jsm:3109 < startup()@resource://gre/modules/addons/XPIProvider.jsm:2188 
< callProvider()@resource://gre/modules/AddonManager.jsm:269 < _startProvider()@resource://gre/modules/AddonManager.jsm:739 
< startup()@resource://gre/modules/AddonManager.jsm:906 < startup()@resource://gre/modules/AddonManager.jsm:3090 
< observe()@jar:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/omni.ja!/components/addonManager.js:65
``` 

https://ci.appveyor.com/project/aspnetci/templating/build/1.0.184#L109

This is the PR: https://github.com/aspnet/templating/pull/231

cc @natemcmaster @SteveSandersonMS 

Are the templating tests not supposed to run on Travis?

**Comment by SteveSandersonMS** [comment]
I don't know for sure, but I wonder if it has anything to do with this: https://github.com/aspnet/templating/blob/dev/test/Templates.Test/Helpers/AspNetProcess.cs#L45 It's an existing workaround for a runtime-store-publishing-related issue. Maybe that workaround is no longer correct for the newest SDK.

I'll try to debug what's changed on Monday if that's OK.

As for the tests on Travis, we haven't changed anything related to that recently, so whatever used to be the case should still be. The error looks like it relates to WebDriver in some way. Because of recent work on other projects, I've found a much faster and more reliable way to use WebDriver in our unit tests so maybe we should switch over to this alternate approach. We could discuss it next week if that's convenient.

**Comment by jbagga** [comment]
The failing Travis check is on a 2.0.x patch PR and that does not have the work around https://github.com/aspnet/templating/blob/release/2.0/test/Templates.Test/Helpers/AspNetProcess.cs#L33

Appveyor does pass but the warnings are pretty consistent

**Comment by jbagga** [comment]
https://github.com/mozilla/geckodriver/issues/923 Maybe we need to use a newer Firefox version than 47 https://www.appveyor.com/docs/how-to/selenium-testing/
cc @SteveSandersonMS

**Comment by mkArtakMSFT** [comment]
Hi @SteveSandersonMS. Have you tried it out? Any findings? Thanks!

**Comment by mkArtakMSFT** [comment]
@jbagga, please follow up on this one to make sure it's handled. Thanks!

**Comment by mkArtakMSFT** [comment]
This will be handled as part of https://github.com/aspnet/templating/issues/277.
