### ISSUE TITLE
Web App with Individual Auth uses Web Helper instead of TagHelper

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/templating#25]
_From @phenning on July 6, 2017 17:26_

In the Individual Auth template for Core Web Application, there is exactly one Web Helper, at line 38 in Views/Accout/Login.cshtml.

This should be changed to a TagHelper.

```
                        <div class="checkbox">
                            <label asp-for="RememberMe">
                                <input asp-for="RememberMe" />
                                @Html.DisplayNameFor(m => m.RememberMe)
                            </label>
                        </div>
```

_Copied from original issue: dotnet/templating#1024_

**Comment by Eilon** [comment]
No tag helper currently exists for this. If we add one, we can consider it. Here's the related issue: https://github.com/aspnet/Mvc/issues/6782

**Comment by Eilon** [comment]
This issue was moved to aspnet/Identity#1665
