### ISSUE TITLE
Angular CLI template does not work with CLI 1.6.5

### ISSUE THREAD

**Issue by paulsperanza** [aspnet/templating#255]
I updated the CLI on my machine, 1.6.1 to 1.6.5. I created a new sample app and it would not work as the browser showed CANNOT GET. 

I downgraded the CLI back to 1.6.1, recreated a new app and it works. The sample app package.json looks for 1.6.3. Not sure if this is an issue or expected behavior. Maybe the global CLI has to be the same as the package.json version or lower.  Anyway, that's what I found so I'm reporting it so maybe if this is expected at least we can document it.

**Comment by Eilon** [comment]
@SteveSandersonMS - thoughts on this?

**Comment by SteveSandersonMS** [comment]
It's possible there was some breaking change in the `ng` tooling between 1.6.1 and 1.6.5. However, the Angular CLI template is now updated to 1.6.8 so this should no longer be applicable.
