### ISSUE TITLE
Update ASP.NET Core 2.1 templates to use fixed ports when running from the command-line

### ISSUE THREAD

**Issue by danroth27** [aspnet/templating#263]
The ASP.NET Core 2.1 templates currently generate random ports for the generated app, including the project launch profile. This make it tedious to then browse to the application when launched from the command line. We should change the project launch profile to specify explicitly the default ports (5000 & 5001) using the ASPNETCORE_URLS environment variable.

**Comment by Eilon** [comment]
@jbagga here's a preview1 item for you.

**Comment by Eilon** [comment]
Please sync with @danroth27 if you have questions on this.
