### ISSUE TITLE
Razor template should be updated to Bootstrap 4

### ISSUE THREAD

**Issue by murbanowicz** [aspnet/templating#268]
Hello,

Bootstrap 4 has been released so razor template should be updated to Bootstrap 4 instead of forcing everyone to rework it by themselves.

**Comment by DamianEdwards** [comment]
Agreed. We'll have to do an assessment of how much work this is before we commit to it for 2.1 however.

@Eilon can we have someone take a look please?

**Comment by DamianEdwards** [comment]
Oh and if we do this it would be all templates, not just the Razor Pages version.

**Comment by Eilon** [comment]
Closing as a dup of https://github.com/aspnet/templating/issues/278 because the other bug is broader in scope. Thanks!
