### ISSUE TITLE
Logging configuration in WebApi and Spa template shouldn't include providers.

### ISSUE THREAD

**Issue by seancpeters** [aspnet/templating#27]
_From @pakrym on August 14, 2017 23:28_

Expected:
```
 "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
}
```
https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/appsettings.json

Actual:
```
"Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Warning"
      }
    }
}
```
https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/template_feed/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/WebApi-CSharp/appsettings.json

_Copied from original issue: dotnet/templating#1208_

**Comment by pakrym** [comment]
https://github.com/aspnet/templating/pull/13
