### ISSUE TITLE
Change templates to use Microsoft.AspNetCore.App

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/templating#270]
Now that we have split the shared framework and metapackage into Microsoft.AspNetCore.App and Microsoft.AspNetCore.All we should convert our default templates to use .App. This needs to go into 2.1.

IIRC we also need to add sqlite dependencies in the templates for OSX using EF?

cc @DamianEdwards @ajcvickers @natemcmaster @Eilon

**Comment by Eilon** [comment]
For SQLite, wouldn't we need it on all non-Windows templates? (Not just OS X)
