### ISSUE TITLE
Remove hardcoded year value 2017

### ISSUE THREAD

**Issue by ljnotes** [aspnet/templating#271]
@natemcmaster

It would be great to replace the hardcoded copyright year value `2017 - Company.WebApplication1` from [RazorPagesWeb-CSharp\Pages\_Layout.cshtml](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Pages/_Layout.cshtml) with `@DateTime.Now.Year`. 

Though it has no functional implications, it would make the application better moving forward (2018+ ..)

### Expected
> @DateTime.Now.Year - Company.WebApplication1

**Comment by natemcmaster** [comment]
A PR would be great :)

**Comment by Eilon** [comment]
We'll review this in template triage.

**Comment by Eilon** [comment]
We might want to just not have a year at all. Showing the current year is often incorrect.

**Comment by Eilon** [comment]
Ok I read some more, and maybe we do need a year... we'll see.

**Comment by DamianEdwards** [comment]
I've heard both, and most recently that you don't need it, but also that it should be hard coded to the date of publish, not auto-set to whatever today is. Oh and the templates used to emit it as `@DateTime.Now.Year` but we removed it. Also, **not** using `DateTime.UtcNow` on a server makes me sad, which is another reason not to change this :smile:

**Comment by DamianEdwards** [comment]
Some references...

From https://www.copyrightlaws.com/copyright-notice-year/

> For constantly evolving websites and blogs that contain works published over several years, the notice may include a range of years (e.g., 2009–2018), starting from the date of the oldest published elements and ending with the date of the newest published elements.

From https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated:

> The copyright notice on a work establishes a claim to copyright. The date on the notice establishes how far back the claim is made. This means if you update the date, you are no longer claiming the copyright for the original date and that means if somebody has copied the work in the meantime and they claim its theirs on the ground that their publishing the copy was before your claim, then it will be difficult to establish who is the originator of the work.
> 
> Therefore, if the claim is based on common law copyright (not formally registered), then the date should be the date of first publication. If the claim is a registered copyright, then the date should be the date claimed in the registration. In cases where the work was substantially revised you may establish a new copyright claim to the revised work by adding another copyright notice with a newer date or by adding an additional date to the existing notice as in "© 2000, 2010". Again, the added date establishes how far back the claim is made on the revision.

From https://www.nolo.com/legal-encyclopedia/when-do-you-need-copyright-notice-websites-and-where-do-you-place-it.html:

> The copyright notice must also state the year the work was published. It has yet to be decided exactly when a website is "published" for copyright purposes, since many websites are updated daily. You should assume that any website that can be accessed has been "published" as soon as it launches, and include a copyright notice on it to reflect the original date.
> 
> However, if an update contains a substantial amount of new material, it is considered to be a separate work of authorship in its own right. The notice for such a derivative work should contain the date the new work was published. The notice need not contain the date or dates of the prior version or versions; however, it is common practice to include such dates in the copyright notice. (Some websites will indicate a series of years in the footer, e.g., "© 2017, 2016, 2015").

**Comment by DamianEdwards** [comment]
Certainly the template source itself shouldn't be hard coded: it should be printing into the output project the current year (which is perhaps what the original @ljnotes intended in the first place). I could possibly be convinced it should be changed to emit something like `&copy; 2017-@DateTime.Now.Year - Company.WebApplication1`

**Comment by natemcmaster** [comment]
>Certainly the template source itself shouldn't be hard coded: it should be printing into the output project the current year

Not hard to do. cref https://github.com/dotnet/templating/wiki/Available-Parameter-Generators#now

**Comment by ljnotes** [comment]
@DamianEdwards 

> it should be printing into the output project the current year (which is perhaps what the original @ljnotes intended in the first place).

Yes, exactly. 

>  I could possibly be convinced it should be changed to emit something like `&copy; 2017-@DateTime.Now.Year - Company.WebApplication1`

If we output `2017-2018`, we would be talking about the copyright of the template source right. The generated output can be kept simple by using the current year I presume?

**Comment by DamianEdwards** [comment]
Yeah I meant we could have it output a range (given it seems that's common for web properties) with the starting year being when the project was created (dynamically generated by the template) and the ending year be dynamically generated by the app. But to make it super correct, it'd have to ensure it only prints a range when the diff is actually more than a full year, so I think we can leave that to app devs if they want to go to that much trouble.

Let's just fix the template to dynamically emit the current year (it will be static in the app).

**Comment by Eilon** [comment]
We closed the related PR because we want to use the tech that @natemcmaster showed because we want the year to be burned into the project at the time the template is executed.
