### ISSUE TITLE
How to help get the react template working properly?

### ISSUE THREAD

**Issue by georgiosd** [aspnet/templating#273]
Hi :)

I have been looking for a decent starter for dotnet core and React (with none of the Typescript) and this is the only sane project I've found.

The only problem I have is that when I make a change to the UI, the dotnet server freezes (or at least it seems that way on the browser). 

How could I help fix this?

EDIT: this particular problem seems to somehow be related to fiddler! I don't show up when I've closed it down. However I'd still like to know what I can do to help take it to the finish line!

**Comment by Eilon** [comment]
@georgiosd can you provide more info on what you'd like help with?

**Comment by Eilon** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
