### ISSUE TITLE
Observed some BOM/non ASCII characters in appsettings.json in .net core web api project

### ISSUE THREAD

**Issue by Pilchie** [aspnet/templating#276]
_From @shinkarmv on January 22, 2018 16:42_

While working with appsettings transformations using python script in Docker file.
I have observed that some BOM/non ASCII characters in the starting of appsettings.json

Please find screenshot below for reference
![image](https://user-images.githubusercontent.com/31374791/35232511-a587348a-ffc1-11e7-9f82-287cded2edfe.png)

These characters came by default with project template of WEB API in Visual Studio 2017 .Net Core.

Regards,
Mukesh

_Copied from original issue: dotnet/project-system#3171_

**Comment by Pilchie** [comment]
Likely a UTF-8 BOM?

**Comment by Pilchie** [comment]
@BillHiebert ?

**Comment by Pilchie** [comment]
_From @shinkarmv on January 22, 2018 16:54_

Yes @Pilchie.  These are BOM characters.

**Comment by Pilchie** [comment]
_From @shinkarmv on January 22, 2018 17:49_

I have cross verified the unit test at SchemaStore repository and observed no BOM character in it.

Please see below screenshot for reference.

![image](https://user-images.githubusercontent.com/31374791/35235561-86c41afa-ffca-11e7-85c5-fca50eae9deb.png)

Regards,
Mukesh

**Comment by Pilchie** [comment]
@jmarolf @mlorbetske - do you know where this comes from?

**Comment by Pilchie** [comment]
_From @jmarolf on January 23, 2018 21:11_

@mlorbetske I believe these come from the WebToolsExtensions repo

**Comment by Pilchie** [comment]
_From @shinkarmv on January 26, 2018 8:11_

Hi @Pilchie ,

I did some analysis on the aforementioned issue and finally got the Project Template for WEB API for C# .net core app.

Repository - https://github.com/aspnet/templating

Template link - https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/WebApi-CSharp/appsettings.json

I have validated appsettings.json file and got some BOM characters at start of file.
Please find the screenshot below for reference,

![image](https://user-images.githubusercontent.com/31374791/35430494-821a07ea-029e-11e8-83bc-c470e5ec2d7a.png)
 
cc: @mlorbetske, @jmarolf

Regards,
Mukesh

**Comment by BillHiebert** [comment]
@Pilchie  Yes these come from the template. Is there a concern about the characters being there? @phenning

**Comment by Pilchie** [comment]
I don't know if we have an all-up policy, but the de-facto standard for most linux and OSX users will be UTF-8 *without* BOM.  It may be unexpected to have the BOM is all.

**Comment by phenning** [comment]
I know there was a policy within Visual Studio for template content to generate files with BOMs in Visual Studio. Now that the template content is decoupled from Visual Studio, I'm uncertain if this is still a requirement.

**Comment by shinkarmv** [comment]
Since, BOM characters are illegal/invalid in JSON. It  leads to break JSON parsers as well. 
However, appsetting contains complete JSON data. 

That's why, I think these characters should get removed from appsetting file.

cc: @pilchie

Regards,
Mukesh

**Comment by Eilon** [comment]
Interesting: https://tools.ietf.org/html/rfc7159#section-8.1

>    Implementations MUST NOT add a byte order mark to the beginning of a
   JSON text.  In the interests of interoperability, implementations
   that parse JSON texts MAY ignore the presence of a byte order mark
   rather than treating it as an error.

**Comment by Eilon** [comment]
Let's remove all the BOMs from all the JSON files in this repo.

@jbagga can you also log a bug in VS (talk to our Web Tooling friends to find out where) to check any JSON files that are part of VS templates that aren't in this repo>

**Comment by Eilon** [comment]
We should also add a test for this repo that checks that all our content JSON files don't have a BOM in them. Need to figure out how to figure out how to find

**Comment by Eilon** [comment]
how to figure out which JSON files we should scan. Something like `content/**/*.json` in MSBuild terms.

**Comment by jbagga** [comment]
Web Tools tracking bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585217

**Comment by shinkarmv** [comment]
Thank you team for addressing the issue.

Will look forward to contribute more.

Regards,
Mukesh
