### ISSUE TITLE
Switch to the more-reliable Selenium-based tests by using web-driver

### ISSUE THREAD

**Issue by jbagga** [aspnet/Templating#277]
To mitigate flaky failures we may want to consider adding retries to tests. The CI flakiness has gone down ever since we updated npm but this should still be considered for random local test failures.

cc @javiercn @SteveSandersonMS

**Comment by javiercn** [comment]
Yes. I think that adding a global retry policy for the tests is a good way to improve the resiliency of these kind of tests. There are samples documenting how to do this with xUnit and it can help with selenium time outs. 

Another option is to drastically increment selenium timeouts (for lets say 2 minutes) at the cost of tests taking longer to fail. (It should not affect existing running tests).

**Comment by mkArtakMSFT** [comment]
For the #237 issue make sure it is also resolved as part of these changes.

**Comment by javiercn** [comment]
I showed them how our tests run in selenium the other day.

**Comment by javiercn** [comment]
@ryanbrandenburg Is there anything to do here after the changes you already did?

**Comment by ryanbrandenburg** [comment]
Yeah, we can re-open if we experience new/continued problems.
