### ISSUE TITLE
Bootstrap 4 update [project wide]

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templating#278]
Hi folks,

Is anyone tasked with this already at the team or working on this from the community? Or is there a side project maybe already created and ready for review?
I'd happy to help,

Thanks!

**Comment by Eilon** [comment]
Not currently planned, though we do intend to do this at some point.

**Comment by peterblazejewicz** [comment]
I'm aware of this:
https://github.com/peterblazejewicz/aspnet-5-bootstrap-4
I'll update the content. Thanks!

**Comment by mrlife** [comment]
@mkArtakMSFT Do you know if this is pushed to 2.3 or just 2.2.x?

**Comment by YehudahA** [comment]
+1

**Comment by ryanbrandenburg** [comment]
The work for this as I understand it so far:
* Bootstrap 4.x for File -> New template in ASP.NET Core 2.2.0. (???)
* Rework starter templates to be simpler and have less boiler plate content. (1-2 days)
* Make the cookie consent notification a dismissable alert. (1/2 day)
* Update all scaffolding content for bootstrap 4. (???)
* Identity UI: (???)
  * Support both Bootstrap 3.x and 4.x, selectable by option, in from the package.
  * Support both Bootstrap 3.x and 4.x, selectable by option, in Scaffolding.

**Comment by peterblazejewicz** [comment]
@ryanbrandenburg 
Ryan, also:
- [optionally] rethink how to include the FontAwesome and provide sample usage. The v3.* has been shipping with Glyphicons, v4.* does not.

The BS provides migration guide:
https://getbootstrap.com/docs/4.0/migration/

Frankly, I don't think that keeping v3.* around could have any positive value for MS and .NET team. I was always proponent of thinking the templates have great role on on-boarding users to the platform. I'm used to `yo`, which has its mantra:
> Yeoman helps you to kickstart new projects, prescribing best practices and tools to help you stay productive

Thanks!

**Comment by ryanbrandenburg** [comment]
I'm going to split the above out into smaller items and make this a tracking issue.
