### ISSUE TITLE
Update QR code doc fwlink

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/templating#28]
_From @danroth27 on July 20, 2017 5:54_

We need to update https://go.microsoft.com/fwlink/?Linkid=852423 to point to the QR code doc https://github.com/aspnet/Docs/issues/3780

_Copied from original issue: dotnet/templating#1121_

**Comment by mlorbetske** [comment]
_From @DamianEdwards on August 16, 2017 3:0_

The doc is now live but the FW link hasn't been updated. Needs to point to https://docs.microsoft.com/en-au/aspnet/core/security/authentication/identity-enable-qrcodes

@danroth27

**Comment by danroth27** [comment]
It is already updated.
