### ISSUE TITLE
Update ports section on vs-2017.3.host.json

### ISSUE THREAD

**Issue by javiercn** [aspnet/templating#282]
We broke VS as part of the changes to enable HTTPS and launchSettings.json by default. VS is not passing a port for HTTP, so it's getting generated randomly (VS does some extra checks to ensure that the port is available).

## Bad

```json
{
 "ports": [
    {
      "name": "HttpsPort",
      "useHttps": true
    }
}
```

## Good

```json
{
 "ports": [
    {
      "name": "HttpPort",
      "useHttps": false
    },
    {
      "name": "HttpsPort",
      "useHttps": true
    }
}
```

**Comment by Eilon** [comment]
Approved for preview1.
