### ISSUE TITLE
Flaky tests: RazorPagesTemplate_IndividualAuth_Works_NetFramework etc

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/templating#286]
I set:
- `RazorPagesTemplateTest.RazorPagesTemplate_IndividualAuth_Works_NetCore`
- `RazorPagesTemplate_IndividualAuth_Works_NetFramework`
- `MvcTemplate_IndividualAuth_Works_NetFramework`
- `MvcTemplate_IndividualAuth_Works_NetCore`

to ignore for now because they [fail](http://aspnetci/viewLog.html?buildId=397497&tab=buildResultsDiv&buildTypeId=Coherence_UpdateRepos#testNameId-6932212237237511002) sometimes. It should be investigated and re-enabled once fixed.

**Comment by jbagga** [comment]
Reverted for now: https://github.com/aspnet/templating/pull/294.
We will keep an eye on these (and skip again) and investigate if required.

**Comment by jbagga** [comment]
@ryanbrandenburg @Eilon Closing for now. I'll reopen if we need to revert again.

**Comment by Eilon** [comment]
Do we know anything about the cause? Did we change anything that would make us think they would no longer be flaky?

**Comment by jbagga** [comment]
@javiercn can confirm but he made changes to the Identity UI package responding to RazorPages changes related to UI as a library. And the errors were:

`Could not find the precompiled views assembly for 'Microsoft.AspNetCore.Identity.UI'`

**Comment by javiercn** [comment]
I believe I fixed this already during the weekend

**Comment by Eilon** [comment]
Ah ok.

**Comment by javiercn** [comment]
![image](https://user-images.githubusercontent.com/6995051/35838012-023f68aa-0a9e-11e8-8ffb-6b4d8c4d4e52.png)

This was fixed
