### ISSUE TITLE
The `react` template ships with broken CSS resource in production mode

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/templating#287]
```cshtml
<environment exclude="Development">
        <link rel="stylesheet" href="~/dist/site.css" asp-append-version="true" />
    </environment>
```
```js
// Plugins that apply in production builds only
            new webpack.optimize.UglifyJsPlugin(),
            new ExtractTextPlugin('site.css')
```
```sh
Hosting environment: Production
```
and there is no `site.cs` there, this yields expected: `Failed to load resource: the server responded with a status of 404 (Not Found)` - not fancy for template content.

Thanks!

**Comment by Eilon** [comment]
@SteveSandersonMS can you take a look?

**Comment by SteveSandersonMS** [comment]
I don't think this was really broken. It looks like you were trying to run in production mode without having built in production mode (i.e., having actually published, or at least run Webpack with the `--prod` flag, which causes it to run the `new ExtractTextPlugin('site.css')` logic).

In any case, the newer React templates are based on create-react-app and don't even have any custom Webpack config, so this issue could no longer apply anyway. Also I've just verified that the latest React template does publish correctly with its CSS.
