### ISSUE TITLE
Minor coding issue with `react` sample (no props passed from super in constructor)

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/templating#289]
Hi,
Here:
https://github.com/aspnet/templating/blob/1d9585b69d14bc0a8538ca65e11da021fff4d711/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/React-CSharp/ClientApp/src/components/Counter.js#L6-L7
and in TS sample

FB:
https://reactjs.org/docs/composition-vs-inheritance.html
https://github.com/facebook/create-react-app/blob/19e0bb1881e24fb1ee3fe421413d4d87e67f68dd/packages/react-scripts/fixtures/kitchensink/src/features/env/NodePath.js#L17

**Comment by Eilon** [comment]
@SteveSandersonMS can you take a look?

**Comment by SteveSandersonMS** [comment]
Fixed via #296
