### ISSUE TITLE
Why some templates ships with `.gitignore` by default, why the others do not?

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/templating#290]
Why is that e.g. Spa templates create a `.gitignore` while the same server type of project (static, no client side app), ships without that file template?

Thanks!

**Comment by Eilon** [comment]
The SPA templates have a wider variety of content that is more likely to benefit from a .gitignore file. It's difficult to predict what a good file would be for all tempaltes, so we placed them only where they were clearly needed.

**Comment by peterblazejewicz** [comment]
Just for the records, to myself:

- create a project (`dotnet new mvc`)
- init a repo (no .gitignore, I'm the junior) and initialize (`git init && git add . && git commit -m'Initial commit')
> I've already added the `obj`, but I would not notice)
- I build and run a project
```sh
dotnet restore
  Restore completed in 71.97 ms for /Users/piotrblazejewicz/dev/mvc/mvc.csproj.
  Restore completed in 36.17 ms for /Users/piotrblazejewicz/dev/mvc/mvc.csproj.
➜  mvc git:(master) dotnet build
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 58.8 ms for /Users/piotrblazejewicz/dev/mvc/mvc.csproj.
  Restore completed in 47.75 ms for /Users/piotrblazejewicz/dev/mvc/mvc.csproj.
  mvc -> /Users/piotrblazejewicz/dev/mvc/bin/Debug/netcoreapp2.0/mvc.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:06.35
➜  mvc git:(master) ✗ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bin/
	obj/Debug/
```
- so I end with debug/binary content added to repo:
```
bin/Debug/netcoreapp2.0/mvc.deps.json
bin/Debug/netcoreapp2.0/mvc.dll
bin/Debug/netcoreapp2.0/mvc.pdb
bin/Debug/netcoreapp2.0/mvc.runtimeconfig.dev.json
bin/Debug/netcoreapp2.0/mvc.runtimeconfig.json
obj/Debug/netcoreapp2.0/mvc.AssemblyInfo.cs
obj/Debug/netcoreapp2.0/mvc.AssemblyInfoInputs.cache
obj/Debug/netcoreapp2.0/mvc.csproj.CoreCompileInputs.cache
obj/Debug/netcoreapp2.0/mvc.csproj.FileListAbsolute.txt
obj/Debug/netcoreapp2.0/mvc.dll
obj/Debug/netcoreapp2.0/mvc.pdb
obj/mvc.csproj.nuget.cache
obj/mvc.csproj.nuget.g.props
obj/mvc.csproj.nuget.g.targets
obj/project.assets.json
```

Also just for records: is that behaviour aligned with TFS default behavior (if no `.tfIgnore` is added):
https://docs.microsoft.com/en-us/vsts/tfvc/add-files-server#tfignore
