### ISSUE TITLE
How do I re-run webpack?

### ISSUE THREAD

**Issue by kakins** [aspnet/templating#299]
First, my apologies as I'm pretty new to the node/webpack world.  I've added a .css file to my configuration, and I'd like to reload the bundle.

I've gone through some other tutorials and it's hard to get a clear answer for re-running webpack.

I added the following as a script in the package.json:
`"wbp" : 'npm run webpack --config webpack.config.vendor.js"
`

Then I just run the following from the root directory of my project:
`npm run  wbp`

Is this the way "correct" way to re-run webpack using the template?

**Comment by peterblazejewicz** [comment]
Which SPA template you're stuck with?

**Comment by SteveSandersonMS** [comment]
@kakins Your approach is fine. Alternatively you can run `webpack` on the command line directly, if you've installed it as a global tool (`npm install -g webpack`).
