### ISSUE TITLE
Consider adding [Display(Prompt="...")] attribute to show how to include placeholders in form inputs

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/templating#305]
It appears (I could be wrong about this), that Razor samples come without using placeholders for form inputs.
Using them could be beneficial for various reason,
Based on sample expected markup from this pending issue:
https://github.com/aspnet/templating/issues/106
the changes could be as simple as:

```diff
--- a/mvc-individual-authentication/Models/AccountViewModels/RegisterViewModel.cs
+++ b/mvc-individual-authentication/Models/AccountViewModels/RegisterViewModel.cs
@@ -10,17 +10,17 @@ namespace mvc_individual_authentication.Models.AccountViewModels
     {
         [Required]
         [EmailAddress]
-        [Display(Name = "Email")]
+        [Display(Name = "Email", Prompt="Enter Email")]
         public string Email { get; set; }
 
         [Required]
         [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
         [DataType(DataType.Password)]
-        [Display(Name = "Password")]
+        [Display(Name = "Password", Prompt="Password")]
         public string Password { get; set; }
 
         [DataType(DataType.Password)]
-        [Display(Name = "Confirm password")]
+        [Display(Name = "Confirm password", Prompt="Retype Password")]
         [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
         public string ConfirmPassword { get; set; }
```
Thanks!

**Comment by Eilon** [comment]
Given that the template UI has labels outside of each textbox, I'm not sure this adds much value.

**Comment by peterblazejewicz** [comment]
Yes, I understand. I think the added value is most user have a problem on how to add placeholder (in ASP MVC pattern) and to follow good practises, otherwise the same can be said about any docs/template:
http://getbootstrap.com/docs/4.0/components/forms/
I just though it could be useful, the docs are not discussing the topic:
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro
and people ask questions about placeholders in quite exotic places:
https://www.quora.com/How-do-I-add-a-placeholder-in-MVC-Razor
also considering the placeholder support is quite new:
https://github.com/aspnet/Mvc/commit/8b726ddc0ce208b41a07194af7052dbe14eed99f
Thanks!

**Comment by Eilon** [comment]
@peterblazejewicz understood, but the templates are not meant to be a way of showing features; rather, it's meant as a way to include a useful piece of functionality to get apps up and running quickly.
