### ISSUE TITLE
Switch from checked in initial migration to running Add-Migration as part of build

### ISSUE THREAD

**Issue by HaoK** [aspnet/templating#309]
Currently the migrations are constantly getting stale and broken.  We should look into switching to generating the initial migration during project creation since its just running the "Add-Migration Initial" command.  This guarantees the content will be fresh unlike today where the migration will just be broken if it becomes stale.

**Comment by HaoK** [comment]
Met with @seancpeters @Eilon @javiercn yesterday and discussed with @ajcvickers today.

We agreed that the best long term plan is for the templating repo to produce the migrations during build.

Rough thinking is to:
1. Build the templates like today.
2. Instantiate each flavor of the template via `dotnet new razor -au Individual` and one with `--use_local_db` specifying the project name to match the expected format "Company.WebApplication1"
3. Apply any fixup needed (maybe nothing)
4. copy the generated migrations into the matching Razor/StarterWeb.CSharp locations so they will be updated automatically.

**Comment by Eilon** [comment]
@HaoK can you take a crack at this? I chatted with @ajcvickers and he said you probably can fit this in.

**Comment by HaoK** [comment]
Looks like we've come full circle, I spent some time with @natemcmaster trying to figure out how we would do this...  The problem with build time, is the conditional logic between SqlServer/SqlLite, even if we generate the correct migration for each, we'd have to merge them back somehow into a single one.  This was why the runtime approach where we created the migrations after dotnet new was better, since it eliminates the need for this switch...

Anyways, I think the cheapest and highest ROI at this point is for me to just create a test in templating that does:

dotnet new (with and without sqlserver), and then runs dotnet ef migrations and verifies that the new migration is empty.

Sound reasonable?  Basically we'd just have a CI failure whenever migrations need to be updated instead of automatically updating them.

**Comment by ajcvickers** [comment]
@HaoK That sounds reasonable to me. @Eilon?

**Comment by javiercn** [comment]
> The problem with build time, is the conditional logic between SqlServer/SqlLite, even if we generate the correct migration for each, we'd have to merge them back somehow into a single one.

I believe this might be possible. You can have them be
Data/Migrations/SqlLite/... and Data/Migrations/SqlServer/... in the template content and move them to Data/Migrations/... when we instantiate the template.

@mlorbetske Can you teach us the ways of the template engine?

**Comment by HaoK** [comment]
Well adding the test is super cheap, I'll have the PR out shortly, I'm inclined to just go with this for now since its going to take much longer and require some of @natemcmaster time as well for us to get that to work.

**Comment by javiercn** [comment]
@HaoK Fair enough

**Comment by ajcvickers** [comment]
@HaoK Test is certainly worthwhile regardless, but I think it's worth exploring @javiercn's suggestion, partly be cause it would be nice if the migration that ended up in the project didn't have the conditionals for SQL Server/SQLite. This would then align with what people would get if they ran add-migration manually.

That being said, if this whole thing ends up in significant additional complexity then I am fine with us not doing it.

**Comment by HaoK** [comment]
The migration in a user's project doesn't have it today anyways, the templating engine strips that out during dotnet new... or are you talking about not having the conditional in the checked in migration?

**Comment by HaoK** [comment]
Nothing we are currently considering will affect the output/resulting project or migration after a dotnet new...

**Comment by Eilon** [comment]
I'm OK with whatever for now...

**Comment by seancpeters** [comment]
> I believe this might be possible. You can have them be
> Data/Migrations/SqlLite/... and Data/Migrations/SqlServer/... in the template content and move them to Data/Migrations/... when we instantiate the template.
> 

Dealing with only including the correct migration in the template output is handled in the "sources" section of the template.json file. Here's an example which should be close to what you need (assuming I understand the requirement correctly). In this example, I'm using a choice symbol named "Migration" to control which migration is included with the template - you can change the conditions in the source modifiers to whatever is appropriate for the use cases.

Here's the "Migration" symbol:
```
  "symbols": {
    "Migration": {
      "type": "parameter",
      "description": "Which migration to include",
      "datatype": "choice",
      "choices": [
        {
          "choice": "SqlServer",
          "description": "Use SqlServer migrations"
        },
        {
          "choice": "SqlLite",
          "description": "Use SqlLite migrations"
        },
        {
          "choice": "None",
          "description": "Don't use migrations"
        }
      ]
    },
  }
```

Then the "sources" section is used to control which files get included, excluded, and renamed as follows:
```
  "sources": [
    {
      "modifiers": [
        {
          "condition": "(Migration == \"SqlServer\")",
          "rename": {
            "Data/Migrations/SqlServer/": "Data/Migrations/",
          },
          "exclude": [
            "Data/Migrations/SqlLite/**"
          ]
        },
        {
          "condition": "(Migration == \"SqlLite\")",
          "rename": {
            "Data/Migrations/SqlLite/": "Data/Migrations/"
          },
          "exclude": [
            "Data/Migrations/SqlServer/**"
          ]
        },
        {
          "condition": "(Migration == \"None\")",
          "exclude": [
            "Data/Migrations/SqlServer/**",
            "Data/Migrations/SqlLite/**"
          ]
        }
      ]
    }
  ]
```
Note: This is setup for the implicit default source, if you have a source explicitly defined, this would go in that source. 

Modifiers is an array of directives that allows choosing files to incluce, exclude, rename, or copy without processing. This task should only need exclude & rename configuration (as shown above). Each modifier can optionally have a condition, the above has a modifier conditioned for each of the choice values of the Migration symbol.

The first modifier indicates that if the Migration is SqlServer:
- The "Data/Migrations/SqlServer/" directory gets renamed to Data/Migrations/ (and any content under that directory gets moved accordingly)
- The "Data/Migrations/SqlLite/" directory and all it's content is excluded from the creation output.

The second & third modifiers are setup analogously for their respective Migration values.

**Comment by HaoK** [comment]
Cool I think i might make this change regardless of whether we automate this process...since its much easier to update the baselines if we can just blindly copy the entire file over twice instead of hand merging changes...

**Comment by HaoK** [comment]
I can then just add a little batch file to automate the update..., so if the test fails you'd just have to build templating and run the patch file and commit the diffs.

dotnet new ...
dotnet ef migrations add update
copy Data/Migrations/*-update* ...

**Comment by ajcvickers** [comment]
@HaoK I like that plan.

**Comment by HaoK** [comment]
Test and splitting of template files done.  Last remaining work is to add the manual script to run that will generate new migrations in the repo enlistement
