### ISSUE TITLE
Vue single file components

### ISSUE THREAD

**Issue by thepill** [aspnet/templating#312]
Is it possible to create single file components using the vue template and typescript?

like: https://vuejs.org/v2/guide/single-file-components.html

Currently what i see is the html code out of the typescript files.

Thanks in advice.

**Comment by SteveSandersonMS** [comment]
The template in the `SpaTemplates` package doesn't use single-file components. I'm sure it's possible to amend the Webpack config to make it build single-file components, but you'd have to check Vue and Webpack docs to find out how.

Also we're no longer making changes to the Vue template in this repo, so closing. Hope that's OK!
