### ISSUE TITLE
Missing license header in some files

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Templating#32]
_From @omajid on August 18, 2017 16:5_

Some files have only this license header, which doesn't explicitly confirm that the file is licensed under the license documented in the https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/LICENSE  file:

    /*!
    ** Unobtrusive validation support library for jQuery and jQuery Validate
    ** Copyright (C) Microsoft Corporation. All rights reserved.
    */

For example, https://github.com/dotnet/templating/blob/rel/2.1.0-preview1/template_feed/Microsoft.DotNet.Web.ProjectTemplates.1.x/content/StarterWeb-CSharp/wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js. Can you please somehow clarify this header? The "All Rights Reserved" and no mention of MIT or jquery license makes me feel uncomfortable.

cc @leecow

_Copied from original issue: dotnet/templating#1216_

**Comment by Eilon** [comment]
I'll take a look at this. We do link to the license in the repo and in the various packages that contain the distributed files, e.g. here: https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/package.json#L21

But, I'll talk to our license experts and get a clarification and see what we should update to make things clearer.

**Comment by omajid** [comment]
@Eilon Thanks. 

That EULA link, for example, worries me even more. https://github.com/aspnet/templating/blob/dev/LICENSE.txt (the root license in this repo) and https://github.com/aspnet/jquery-validation-unobtrusive/blob/master/LICENSE.txt (root license in jquery-validation-unobtrusive repo) says the code is under Apache 2.0, so finding a file that has a proprietary eula/license is very troublesome to me.

cc @richlander @Bob-Davis

**Comment by Eilon** [comment]
@omajid the license of the source code doesn't need to match the license of the product that distributes the source code. However, what I'm hoping to do here is to massively simplify the license of this stuff so that there's no confusion at all.

**Comment by omajid** [comment]
>  the license of the source code doesn't need to match the license of the product that distributes the source code. 

I see. For some background, we are looking to consume this via https://github.com/dotnet/source-build/ and our hope is to produce packages that we can merge into various Linux distributions under the same license as the source.

> However, what I'm hoping to do here is to massively simplify the license of this stuff so that there's no confusion at all.

That will be great. Looking forward to it!

**Comment by Eilon** [comment]
Yup, totally understood. We want to clean this up for your benefit and for our own sanity 😄

**Comment by mkArtakMSFT** [comment]
@Eilon, what is the expectation here?

**Comment by Eilon** [comment]
@mkArtakMSFT - I think these are the things to do:

- [ ] Update licenses for our two JS libraries to be clear that they are .NET Foundation / Apache
- [ ] Release an updated version of those JS libraries
- [ ] Update the templates in this repo to consume those updated libraries

**Comment by mkArtakMSFT** [comment]
https://github.com/aspnet/jquery-ajax-unobtrusive/issues/41

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT where is the internal OneNote page @kichalla mentioned [here](https://github.com/aspnet/jquery-validation-unobtrusive/wiki/Release-checklist)? I searched and couldn't find it.

**Comment by ryanbrandenburg** [comment]
Also, we can remove anything having to do with the AJAX CDN from that checklist right?

**Comment by ryanbrandenburg** [comment]
A reminder that I need to know where the OneNote is before I can use it.

**Comment by Eilon** [comment]
Can you email Kiran? And then change the wiki to be an actual link?

**Comment by ryanbrandenburg** [comment]
Did so. I created a Coherence-Signed wiki page to link to instead, no need to have to leave GitHub.

**Comment by ryanbrandenburg** [comment]
This is blocked pending a decision about how we want to handle the release. I need that information from @Eilon and/or @mkArtakMSFT.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, please go ahead with the release per the wiki page. I've synced up with @danroth27. We're good to go!

**Comment by ryanbrandenburg** [comment]
The only remaining work on this is tracked in another issue.
