### ISSUE TITLE
Tests fail with "Certificate error: Navigation blocked"

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/templating#320]
Currently, all templates tests are failing on my machine with "Certificate error: Navigation blocked"

example:
```
[xUnit.net 00:01:28.7294386]     Templates.Test.SpaTemplateTest.AureliaTemplateTest.AureliaTemplate_Works_NetCore [FAIL]
[xUnit.net 00:01:28.7309556]       Assert.Contains() Failure
[xUnit.net 00:01:28.7311459]       Not found: 86e2ffb5eecd41de86cae0ea8e0754f9
[xUnit.net 00:01:28.7312242]       In value:  Certificate error: Navigation blocked
[xUnit.net 00:01:28.7323450]       Stack Trace:
[xUnit.net 00:01:28.7337289]         C:\dev\aspnet\Universe\modules\Templating\test\Templates.Test\SpaTemplateTest\SpaTemplateTestBase.cs(65,0): at Templates.Test.SpaTemplateTest.SpaTemplateTestBase.TestBasicNavigation(IWebDriver browser)
```

@javiercn any ideas? Do CI machines need to trust the dev-cert?

**Comment by javiercn** [comment]
You need to trust the cert on your machine, cuz the tests are running on edge.
We run the tests on Firefox on travis and using httpclient on the CI machine (both of which are setup so that it ignores invalid certs).
On your dev box you need to trust the cert so that they can run on edge, given that edge doesn't have support in selenium to tell it to ignore certificate errors.

**Comment by natemcmaster** [comment]
This will be problematic for our CI machines. This workaround appears to work: https://github.com/aspnet/templating/pull/321

**Comment by javiercn** [comment]
This will not be problematic for our CI machines as they don't run Selenium tests. They only run using HTTP Client and there is a workaround for that one. If we were to run selenium tests on our CI machines we would do so using Firefox which has explicit support for doing this through the WebDriver API.
________________________________
