### ISSUE TITLE
Create and use new Third Party Notices URL for templates

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#330]
Currently the 2.1 templates use a URL that was meant for earlier versions of the template, and links to the dotnet/templating repo. The ASP.NET Core templates need to have their own notices file with its own URL.

We need to:
* [ ] Create a Git **tag** for a version of https://github.com/aspnet/templating/blob/dev/src/THIRD-PARTY-NOTICES that has what we want for the 2.1.0 (previews, RC, RTM, should all be the same file) 
* [x] Create an AKA.MS link that points to it (I can do that)
* [x] Change the `thirdPartyNotices` metadata in the templates to point to the new AKA.MS link (here's an example of where it's used: https://github.com/aspnet/templating/blob/acc2147ac5b3092df194fd9ce043263b091ae4ae/src/Microsoft.DotNet.Web.ProjectTemplates/content/EmptyWeb-FSharp/.template.config/template.json#L14)

**Comment by Eilon** [comment]
@jbagga - let's chat about this because we each need to do part of this work item.

**Comment by Eilon** [comment]
Moving to RC1.

**Comment by Eilon** [comment]
OK I created https://aka.ms/aspnetcore-template-3pn-210 , which right now redirects to https://github.com/aspnet/templating/blob/dev/src/THIRD-PARTY-NOTICES .

So, let's use that AKA.MS link for now, and then we'll update it at RTM time once we have a real tag for the release.

**Comment by mkArtakMSFT** [comment]
We've looked through the PR during the Shiproom meeting yesterday. Go ahead with the commit, @jbagga.

**Comment by jbagga** [comment]
See https://github.com/aspnet/templating/issues/480
