### ISSUE TITLE
SPA templates contain invalid exception handler middleware

### ISSUE THREAD

**Issue by dasMulli** [aspnet/templating#332]
The SPA templates' `Startup` contain

```c#
app.UseExceptionHandler("/Home/Error");
```

but when an exception occurs, `/Home/Error` cannot be resolved to anything useful.

IMHO the templates should contain a small error page, even if it is just a controller action rendering a text or an error route in the SPA.

**Comment by Eilon** [comment]
Ah, seems like a good idea, we will investigate.

**Comment by mkArtakMSFT** [comment]
@jbagga, can you please look into this? Thanks!

**Comment by Eilon** [comment]
Moving to RC1.
