### ISSUE TITLE
Debuging with IIS in Angular SPA Template

### ISSUE THREAD

**Issue by atmike** [aspnet/templating#333]
Hi 
I have created a new angular5 / dotnet cor 2.0 Project with the latest version of the angular spa template=> dotnet new --install Microsoft.DotNet.Web.Spa.ProjectTemplates::2.0.0
But when I create a Project with => dotnet new angular -o IISTest and switch the debug settings to the following => 
![image](https://user-images.githubusercontent.com/22487185/36742014-e315a3a4-1be6-11e8-842b-7fcbeb4abcdd.png)
I always get the the following error =>
![image](https://user-images.githubusercontent.com/22487185/36742053-ff9d4c84-1be6-11e8-9448-08ae8241d117.png)
In IIS I created a new website on port 333 and a No Managed Code Pool.

I did the same with the Angular 4 Template and there it works all fine!

does any one has an idea what this problem is?

Best regards

Michael

p.s. when I run this Project IIS Express it works

**Comment by atmike** [comment]
can any one help me???

**Comment by Eilon** [comment]
@atmike sorry you're running into this.

@SteveSandersonMS can you take a look? Any idea on this?

**Comment by SteveSandersonMS** [comment]
In development mode, Angular CLI needs to execute `node` and `npm`. It looks like you haven't given the IIS worker the necessary permissions to access whatever directories they are installed into.

You could start by giving it permission to read the AppData\Roaming\npm directory and then look out for any different error that could indicate which other directories it needs permissions to access.

Of course, it's much simpler to use with IISExpress which runs under your normal user account.
