### ISSUE TITLE
Replace all uses of Html.PartialAsync, etc. with the new <partial /> Tag Helper instead

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/templating#338]
Seems there's at least one straggler: https://github.com/aspnet/templating/blob/acc2147ac5b3092df194fd9ce043263b091ae4ae/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Views/Shared/_Layout.cshtml#L38

**Comment by DamianEdwards** [comment]
@Eilon @javiercn

**Comment by javiercn** [comment]
https://github.com/aspnet/templating/blob/acc2147ac5b3092df194fd9ce043263b091ae4ae/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Pages/_Layout.cshtml#L38

https://github.com/aspnet/templating/blob/acc2147ac5b3092df194fd9ce043263b091ae4ae/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Views/Shared/_Layout.cshtml#L38

I did a github search. These are the only two places where it shows up.

**Comment by mkArtakMSFT** [comment]
Thanks @javiercn. @jbagga, can you please handle this? Thanks!

**Comment by jbagga** [comment]
There is one in Identity UI as well. 

https://github.com/aspnet/Identity/blob/df4db2f49c80ef310067af0808b04b0acf87e148/src/UI/Areas/Identity/Pages/Account/Manage/_Layout.cshtml
