### ISSUE TITLE
Update ValuesController in Web API project template to use ActionResult<T>

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/templating#339]
The `ValuesController` in the Web API project template should be updated to return `ActionResult<T>` from the two object returning actions it has:

``` c#
// GET api/values
[HttpGet]
public ActionResult<IEnumerable<string>> Get()
{
    return new string[] { "value1", "value2" };
}

// GET api/values/5
[HttpGet("{id}")]
public ActionResult<string> Get(int id)
{
    return "value";
}
```

@Eilon @danroth27

**Comment by mkArtakMSFT** [comment]
@jbagga, assigning this to you so you can keep it on your radar and merge when ready.
