### ISSUE TITLE
Add server-side rendering option to SPA templates

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/templating#34]
Server-side rendering requires a significant amount of non-trivial boilerplate code to be added for React and Angular. Making it a part of the template could save days of work for someone who has never done it.

It would add more clutter though if it's not something that the user needs, so it should be optional.

**Comment by SteveSandersonMS** [comment]
It is already in by default for the Angular and React+Redux templates and always has been. Apologies if I'm misunderstanding what you're asking for (and if so, please clarify).

**Comment by AndriySvyryd** [comment]
@SteveSandersonMS Oh, I meant it to be added to the React template too.

**Comment by SteveSandersonMS** [comment]
Please see https://github.com/aspnet/JavaScriptServices/issues/1271

**Comment by AndriySvyryd** [comment]
Got it, thanks
