### ISSUE TITLE
Move all partial & layout views in Razor Pages project template to Shared folder

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/templating#340]
In 2.1 we added support for the *Shared* folder under the configured Pages root. In the project templates however we have a mix of shared assets (partials, layouts, etc.) in the pages root itself, and the shared folder.

We should make this consistent and move all these assets into the new */Pages/Shared* folder in the project template.

@Eilon

**Comment by mkArtakMSFT** [comment]
@jbagga , can you please handle this? Thanks!
