### ISSUE TITLE
Template type update for RazorPage, MVC ViewImports, & MVC ViewStart

### ISSUE THREAD

**Issue by seancpeters** [aspnet/templating#341]
**Updated**

The templates in the repo directory  templating/src/Microsoft.DotNet.Web.ItemTemplates are currently configured without a 'type' in the tags section of their template.json files. These templates should be classified as `"type": "item"`.

**Comment by seancpeters** [comment]
On a similar note, these same templates should be given a language specification of C# in their tags section. Specifically, this can be added to all 3 template.json's:
```
  "tags": {
    "language": "C#",
    "type": "item"
  },
```

**Comment by Eilon** [comment]
@jbagga - I've assigned PR https://github.com/aspnet/templating/pull/343 to you to review. SHould be pretty straightforward.
