### ISSUE TITLE
Update the templates to cleanup the auth parameters from the template

### ISSUE THREAD

**Issue by javiercn** [aspnet/Templating#342]
The whole goal here is to remove parameters that are not commonly used from the CLI experience. (Visual studio experience doesn't change).

**Comment by mkArtakMSFT** [comment]
@jbagga, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
Moving this out to `2.2.0` as this is just a nice-to-have thing.

**Comment by javiercn** [comment]
Closing this as we are likely not doing it.
