### ISSUE TITLE
AppVeyor and Travis failing on MvcTemplate_NoAuth_Works_NetCore(languageOverride: "F#")

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#345]
Examples:
* https://ci.appveyor.com/project/aspnetci/templating/build/1.0.362
* https://travis-ci.org/aspnet/templating/builds/350051730?utm_source=github_status&utm_medium=notification

> Templates.Test.MvcTemplateTest.MvcTemplate_NoAuth_Works_NetCore(languageOverride: "F#") [FAIL]

**Comment by jbagga** [comment]
I saw this on the CI and it seemed like an issue with the Razor package https://travis-ci.org/aspnet/templating/jobs/350051731#L911 @pranavkm Have you seen this elsewhere?

**Comment by pranavkm** [comment]
The Ubuntu failure is known and fixed in a newer build of the runtime - https://github.com/dotnet/core-setup/issues/3762.
I've seen the OSX one in Razor builds too - my guess is it's likely a runtime \ JIT issue. Haven't dug in to it as yet.

**Comment by jbagga** [comment]
Is there a work item to track this on our side? I am guessing templating is not the only repo that may be affected?

**Comment by jbagga** [comment]
This has been resolved after updating dependencies. Closing for now.
