### ISSUE TITLE
LaunchSettings profile Company.WebApplication1 is created insted of  profile <AppName>

### ISSUE THREAD

**Issue by btorrild** [aspnet/templating#346]
Hello, when applying a new angular project template using 2.1 preview1-final the default non IIS launch profile is called Company.WebApplication1.

Should that not be the name of the console app?

**Comment by Eilon** [comment]
@btorrild hmm that certainly doesn't look right, we might be missing a substitution parameter somewhere. Can you show a screenshot or share more info about exactly where you're seeing this? Thanks!

**Comment by btorrild** [comment]
Does this help. 
```
PS>dotnet --version
2.1.300-preview1-008174

PS>dotnet new angular --name test
The template "ASP.NET Core with Angular" was created successfully.
The usual stuff here...

PS>cat .\test\Properties\launchSettings.json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:45041",
      "sslPort": 44385
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_HTTPS_PORT": "44385"
      }
    },
    "Company.WebApplication1": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "https://localhost:5001;http://localhost:5000"
      }
    }
  }
}

```
I tried some preview templates for 2.0, could that be an issue

**Comment by Eilon** [comment]
@btorrild thanks for the details, that is very helpful. This indeed looks like a bug so we'll take a look at it.

**Comment by Eilon** [comment]
Note: We'll need to investigate whether we should consider patching this or if it's a regression in 2.1.

**Comment by mkArtakMSFT** [comment]
@jbagga can you please look into this? Thanks! Also, assign a cost, please.

**Comment by jbagga** [comment]
launchSettings.json was added in 2.1.0-preview1 https://github.com/aspnet/templating/commit/4d2e642b94ad6c2e152e09005c33bac7543bcf04
Sending a PR for dev
