### ISSUE TITLE
Inconsistency with missing "launchUrl" and present "launchBrowser" in WebApi template

### ISSUE THREAD

**Issue by btorrild** [aspnet/templating#347]
When running a project from VS2017 created using dotnet new webapi, a browser is launched due to the `"launchBrowser": true,` setting in the `.\Properties\launchSettings.json`

It could save some time wondering why nothing happens when running a project out of the box if adding `"launchUrl": "api/values"` to the profiles in WebApi projects, or remove launchBrowser setting

**Comment by Eilon** [comment]
@btorrild ah, interesting point.

@DamianEdwards - thoughts on this regarding the user experience?

**Comment by Eilon** [comment]
Possible dup of https://github.com/aspnet/templating/issues/455.

@jbagga can you confirm?

**Comment by jbagga** [comment]
Yes. This will be handled by #455
