### ISSUE TITLE
Ensure 2.0.x SPA templates changes are merged into release/2.0 for servicing

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/templating#350]
It looks like the changes from the SpaTemplates OOB may not be in the release/2.0 branch.

https://github.com/aspnet/templating/compare/release/2.0...rel/2.0.x-spa-templates-oob

![image](https://user-images.githubusercontent.com/2696087/37224469-712c12b0-2388-11e8-811d-35f2f2c5b699.png)

@Eilon @muratg @SteveSandersonMS - are we supposed to be servicing this package and updating it on NuGet.org? Currently, this package is not marked as one that ships to NuGet.org

https://github.com/aspnet/Universe/blob/release/2.0/build/artifacts.props#L126

**Comment by Eilon** [comment]
@SteveSandersonMS can you comment on this? I thought everything was already as up-to-date as it needed to be.

**Comment by SteveSandersonMS** [comment]
The changes were made in the `rel/2.0.x-spa-templates-oob` branch, and were all also ported to `dev` to ensure they would ship in 2.1.0 as well.

I haven't also ported them to `release/2.0`, but now I understand that's necessary I will do that.

@natemcmaster Is there a specific deadline this needs to be done by? I'm trying to wrap up the Blazor 0.1.0 stuff this week so it would be handy if I could do this next week.

**Comment by natemcmaster** [comment]
I don't have deadlines for the next 2.0.x patch. Eilon might know.

**Comment by SteveSandersonMS** [comment]
Hold on, after several seconds of further consideration, do we *really* want the entirely new templates to ship in 2.0.x servicing releases? Shouldn't those releases just contain any minor updates to the existing templates (of which there are none)?

**Comment by SteveSandersonMS** [comment]
> [Nate] Currently, this package is not marked as one that ships to NuGet.org

i.e.,

```
<PackageArtifact Include="Microsoft.DotNet.Web.Spa.ProjectTemplates" Category="shipoob" />
```

It's marked shipoob because it's a template package that ships inside the SDK, just the same as `Microsoft.DotNet.Web.ProjectTemplates.2.0`. So that's already correct, isn't it?

**Comment by Eilon** [comment]
Hmm I don't think we need these in 2.0 do we? Otherwise they'd randomly show up in the next patch, even though they were never part of 2.0.

**Comment by natemcmaster** [comment]
Re: shipoob

How did this get published? https://www.nuget.org/packages/Microsoft.DotNet.Web.Spa.ProjectTemplates/ When should it be updated?

**Comment by SteveSandersonMS** [comment]
> How did this get published

It was published manually so that people could install it into their existing 2.0.0 SDKs, i.e., to support these installation instructions: https://docs.microsoft.com/en-us/aspnet/core/spa/#installation

> When should it be updated?

It only needs to be updated on NuGet.org if/when we choose to do OOB releases (which people then need to install manually if they want the update). That doesn't need to be automated.

More typically, the latest version of it will end up being distributed via the dotnet SDK, just the same as `Microsoft.DotNet.Web.ProjectTemplates.2.0`.

**Comment by Eilon** [comment]
Yeah I don't think we'd ever update it. The 2.1.0 release will supersede it.

**Comment by SteveSandersonMS** [comment]
OK, since these changes shouldn't be in `release/2.0`, I'll close this.
