### ISSUE TITLE
Remove references to Microsoft.VisualStudio.Web.CodeGeneration.Tools in 2.1 project templates

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/templating#357]
Now that the scaffolder tool is a global tool, we need to remove the references to it as a project tool from all our 2.1 project templates, e.g. like here https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/RazorPagesWeb-CSharp.csproj.in#L45

@Eilon

**Comment by ajcvickers** [comment]
Also for the EF global tool: see https://github.com/aspnet/EntityFrameworkCore/issues/10554

**Comment by mkArtakMSFT** [comment]
Moving to `RC` milestone as we don't have enough capacity to handle it during `preview2`.

**Comment by DamianEdwards** [comment]
This has to be done in preview2 as the tools have already been converted to global tools and thus leaving the project tools in the templates will cause issues.
