### ISSUE TITLE
Updating wwwroot/dist on Rebuild

### ISSUE THREAD

**Issue by scottkuhl** [aspnet/templating#36]
What does everyone think about regenerating the wwwroot/dist folder on rebuild?  Something like this:

`<Target Name="DebugRunWebpack" BeforeTargets="Rebuild" Condition=" '$(Configuration)' == 'Debug'">`
`<RemoveDir Directories="wwwroot/dist" />`
`<Message Importance="high" Text="Performing re-run Webpack build..." />`
`<Exec Command="node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js" />`
`<Exec Command="node node_modules/webpack/bin/webpack.js" />`
`</Target>`

**Comment by SteveSandersonMS** [comment]
You can certainly add that if you want, but we wouldn't put that in by default as it would greatly slow down the build, and doesn't help much if you're using the Webpack dev middleware anyway.
