### ISSUE TITLE
public (static?) class Program 

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/templating#361]
I am wondering why the `public class Program` that contains the `public static void Main(string[] args)` entry point is not marked as static.
It only contains static members.  I see it written in some samples as static but the templates do not have the static modifier

Running any template against FxCop gives

```
Program.cs(13,18): warning CA1052: Type 'Program' is a static holder type but is neither static nor NotInheritable [C:\Users\mikes\Repos\test1\test1.csproj]
```

**Comment by Eilon** [comment]
@davidfowl - do you recall the reason for this?

**Comment by davidfowl** [comment]
It's how console applications always worked.

**Comment by Eilon** [comment]
Oh duh I misread the question to begin with. I guess we didn't want to change history, so everything remains as it always has been.
