### ISSUE TITLE
Razor View compilation error leads to F# NetFx test failure

### ISSUE THREAD

**Issue by jbagga** [aspnet/templating#365]
`'"bin\Release\net461\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-AnyCPU.exe"' is not recognized as an internal or external command, operable program or batch file.`

http://aspnetci/viewLog.html?buildId=422171&tab=buildResultsDiv&buildTypeId=Lite_Templating

**Comment by Eilon** [comment]
Done?
