### ISSUE TITLE
Deploying to multiple environments?

### ISSUE THREAD

**Issue by kakins** [aspnet/Templating#366]
Does the current template setup facilitate easy deployment to multiple environments?

For instance, I've run into an issue where after deploying the latest template to a server, I received 404 errors due to incorrect path of *.bundle.js files.  The server was trying to access them at the root server path (e.g. http://myserver/*.bundle.js instead of http://test/myserver/*.bundle.js).

After some digging I found that I needed to modify Angular's  `base-ref` option where `npm build` is configured in the .csproj:

`<Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --prod --base-href /test/myserver/" />`

This fixed the 404 errors.  However now I need to figure out how to make the .csproj know about multiple deployment environments (e.g. /test/myserver/, /staging/myserver/).  Is this possbile?

**Comment by Eilon** [comment]
@kakins I would recommend having the dev and production environments have similar configurations with regard to paths.

**Comment by kakins** [comment]
@Eilon Thank you for the response.  That may be a good solution for some, unfortunately it is not the way our environment is set up.  

We deploy to multiple non-prod (dev, test, training) environment sites, all hosted on the same server.  Each site path is prefixed by the environment name as mentioned above.  

_For now_, I've modified the .csproj to read the Configuration variable, and set my configuration names such to mirror our paths.  For the production site, we do not prefix the environment name.
```
<Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --prod --base-href /MySite/" Condition="'$(Configuration)' == 'Prod'" />
<Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --prod --base-href /$(Configuration)/MySite/" />
```
This is not optimal and seems hacky.  I'd love a better way, but without somehow ripping out the publish configuration in the .csproj, I'm not sure there is one.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was no much community interest in this ask for quite a while now.
