### ISSUE TITLE
Can't use Angular CLI commands (ng) #

### ISSUE THREAD

**Issue by seancpeters** [aspnet/templating#367]
_From @lukyer on March 16, 2018 13:48_

I'm trying to use newest ASP.NET Core 2.1 with Angular template. It works as is but i'm unable to scaffold components using ng command. Actually no ng command is working because of missing .angular-cli.json in default template. It also makes impossible to ng serve manually out of ASP.NET Core application. It is important because now angular http server is always restarted and it has to start again (slow) with every rebuild.

_Copied from original issue: https://github.com/dotnet/templating/issues/1475_

**Comment by Eilon** [comment]
@SteveSandersonMS can you take a look?

**Comment by SteveSandersonMS** [comment]
Your command prompt has to be in the `ClientApp` subdirectory. That's where `.angular-cli.json` is, and where all the Angular CLI commands will work from. Scaffolding and all other `ng` commands work as normal from there.

**Comment by lukyer** [comment]
Thank you for your response. It seems working now, but different template was served by `dotnet new angular` command a week ago. ClientApp content:

```
C:\example\ClientApp>ls -la
total 24
drwxrwx---+ 1 lukyer lukyer    0 Mar 16 20:20 .
drwxrwx---+ 1 lukyer lukyer    0 Mar 16 21:42 ..
drwxrwx---+ 1 lukyer lukyer    0 Mar 16 20:11 app
-rwxrwx---+ 1 lukyer lukyer  974 Mar 16 20:11 boot.browser.ts
-rwxrwx---+ 1 lukyer lukyer 1722 Mar 16 20:11 boot.server.ts
drwxrwx---+ 1 lukyer lukyer    0 Mar 16 20:20 dist
drwxrwx---+ 1 lukyer lukyer    0 Mar 16 20:11 test
```

Doesn't matter anymore. 
Thanks.
