### ISSUE TITLE
Add conditional RootNamespace property to web projects

### ISSUE THREAD

**Issue by Eilon** [aspnet/Templating#371]
See https://github.com/dotnet/templating/pull/1478 for details.

cc @mlorbetske

**Comment by mlorbetske** [comment]
I talked this over with @vijayrkn and the thinking is to make this change for 2.0 and 2.1 templates only

**Comment by Eilon** [comment]
The bar for patching 2.0 templates is quite high. Are customers complaining about this loudly? It does have an easy workaround, no?

**Comment by mlorbetske** [comment]
It has an easy workaround & we're not actually shipping the 2.0 update but making the change available if 2.0 were to get respun. Updating 2.1 only should be fine as well

cc @vijayrkn

**Comment by Eilon** [comment]
I don't think we'd get this approved for ASP.NET Core 2.0 considering it's a fairly narrow case.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, we'll need to update the project files in templates to include this property.

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT/@Eilon Do we want to actually port this back to 2.1 like the title says or should this now target 2.2?

**Comment by Eilon** [comment]
Definitely not 2.1.
