### ISSUE TITLE
Latest Angular template throws Razor page exception when refreshing home page

### ISSUE THREAD

**Issue by kakins** [aspnet/templating#384]
When I load my home page, or main component, of the angular app and click refresh, I see the following error:

![image](https://user-images.githubusercontent.com/14915247/37631242-ca967454-2bb6-11e8-8fd5-001262fcac3d.png)

This is a 'fresh' instance of the template that I started from the dotnet CLI.  As far as I can tell, there are no references to any razor views in the app.  I can only think that this is somehow related to the MVC configuration?

```
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action=Index}/{id?}");
            });
```

**Comment by Eilon** [comment]
@kakins can you upload your app to GitHub so we can take a look?

**Comment by kakins** [comment]
Perhaps I modified something when updated to the latest CLI-based template, but changing `action=Index` to `action=Home` seemed to resolve the issue.  

There is no route in my app the corresponds to "Index", but for some reason MVC was looking for it when refreshing the home page, e.g. "localhost://myapp/home".

```
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action=Home}/{id?}");
            });
```

**Comment by Eilon** [comment]
The name of the action by default is what's used to look up the view name (unless the view name is explicitly specified).

**Comment by Eilon** [comment]
If this issue is resolved for you, can we close it?

**Comment by kakins** [comment]
Yes, I have no razor views referenced in my project.  Settings this fixed my issue though.  Thank you for your help!

**Comment by Eilon** [comment]
Thanks!
