### ISSUE TITLE
Include fully qualified namespace on @model directive in Razor Page cshtml template.

### ISSUE THREAD

**Issue by phenning** [aspnet/Templating#388]
This is needed to avoid errors in the cshtml file after adding a Razor Page to an Empty ASP.NET Core project, since no _ViewImports.cshtml exists.

Scaffolding already explicitly does this currently, so we should be consistent.

**Comment by Eilon** [comment]
@phenning which template specifically has this problem?

**Comment by phenning** [comment]
@Eilon The problem is here.

https://github.com/aspnet/templating/blob/1d00bb449fa0b65b0bf39348993ff195c9f89138/src/Microsoft.DotNet.Web.ItemTemplates/content/RazorPage/Index.cshtml#L3

This should be:
@model MyApp.Namespace.IndexModel
instead of 
@model IndexModel

**Comment by Eilon** [comment]
Got it!
