### ISSUE TITLE
Angular namespace converting issue (underscore)

### ISSUE THREAD

**Issue by haruair** [aspnet/templating#39]
I created angular project with dotnet cli. The project is created nicely, however, the namespace is something a bit different than I expected.

```
$ dotnet --version
2.0.0
$ dotnet new angular --output src/HelloWorld.AngularApp --name HelloWorld.AngularApp
The template "ASP.NET Core with Angular" was created successfully.
// ...
$ cat src/HelloWorld.AngularApp/Startup.cs
// ...
namespace HelloWorld_AngularApp
{
// ...
```

What I expected is below:

```
// ...
namespace HelloWorld.AngularApp
{
// ...
```

I can replace the namespace manually though, it would be nice to have a `--namespace` parameter for this case like `dotnet new mvc`.

Also, name property in `project.json` needs to check together.

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this. I'll close it as it's already being tracked in https://github.com/aspnet/JavaScriptServices/issues/1225
