### ISSUE TITLE
Remove the BrowserLink package and middleware line references from the project templates

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/templating#394]
It's disabled by default in VS today and we don't want to have an extra package ref and code in the project for the limited utility BrowserLink provides right now. We'll revisit how to make enabling it easy in the future.

**Comment by DamianEdwards** [comment]
@Eilon to triage & assign pls

**Comment by Eilon** [comment]
@jbagga - all yours.

**Comment by jbagga** [comment]
BrowserLink package is brought in and the middleware is used only when UseBrowserLink is set to true
https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/.template.config/template.json#L230

By default it is false and therefore not used. Are we removing the UseBrowserLink option? @DamianEdwards

**Comment by Eilon** [comment]
Just to make sure it's documented: we decided to keep the option, but turn it off by default for VS scenarios.
