### ISSUE TITLE
Should we remove app.db from the templates

### ISSUE THREAD

**Issue by javiercn** [aspnet/templating#4]
We create the templates with a pre-initialized app.db instance which causes that when we make changes to the migration and instantiate the template (and try to run the migrations) we get the message that everything is up to date when it is not.

Instead of that, we should just run the migrations in the same way we do for local db today.

Any thoughts? @ajcvickers

**Comment by ajcvickers** [comment]
Filed https://github.com/aspnet/EntityFrameworkCore/issues/9714 to track reviewing the templates from the EF side. We're not 100% sure yet what the best thing to do here is--we will need to do the review/investigation to figure it out. For consistency, having the same experience regardless of platform would be better. For simplicity of the SQLite experience, having the database file in the template might be better.

**Comment by Eilon** [comment]
I think this is covered by https://github.com/aspnet/templating/issues/309 now, which has more details, so closing this.
