### ISSUE TITLE
Re-enable tests when deps.json file issue is resolved

### ISSUE THREAD

**Issue by jbagga** [aspnet/templating#400]
Currently the newer SDK version is creating the deps.json file incorrectly and not bringing in Microsoft.AspNetCore.All reference

Since MVC is a transitive reference it is not being brought in either and we are seeing test failures http://aspnetci/viewLog.html?buildId=427552&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest

Once the issue is fixed we need to re-enable these tests

**Comment by ryanbrandenburg** [comment]
If you skip tests for any reason please add them to the Infrastructure project under Flaky.

**Comment by jbagga** [comment]
Skipping SPA template tests for now as well as they have an API as part of the test
