### ISSUE TITLE
Error display on typescript build

### ISSUE THREAD

**Issue by kakins** [aspnet/templating#402]
The previous (1.x) version of the Angular template had a nice debugger-like display whenever there was a typescript build error.  Are there any plans on bringing this back, or something similar?  Right now I have to browse through a lot of info my Output window in Visual Studio to see the typescript build error.

**Comment by Eilon** [comment]
@SteveSandersonMS any thoughts on this? I'm not familiar with that feature.

**Comment by SteveSandersonMS** [comment]
@kakins Since the new template uses Angular CLI (including for the build process), please see Angular CLI docs for info about possible configuration. Hope that's OK.

**Comment by kakins** [comment]
![image](https://user-images.githubusercontent.com/14915247/38887718-3ac9c840-423f-11e8-9c8d-c08d6da0c313.png)

I looked at the Angular CLI docs, but couldn't find much.

Here is an example of what I see using the new templates if I remove my bootstrap.css, for instance.  The previous templates showed something similar on compile failures.  Is there a way to bring this back?

**Comment by SteveSandersonMS** [comment]
@kakins Since Angular CLI controls compilation in the new template, please see Angular CLI docs for any available options for handling compilation failures.
