### ISSUE TITLE
F# template does not reference shared runtime

### ISSUE THREAD

**Issue by pranavkm** [aspnet/templating#409]
Unlike the C# templates, the F# web project templates don't reference the `Microsoft.AspNetCore.App` shared runtime. Additionally, once we're confident that the Razor Sdk works well with it (https://github.com/aspnet/Razor/issues/2188), we should have it use the Sdk as opposed to MvcPrecompilation.

**Comment by Eilon** [comment]
cc @cartermp FYI

**Comment by mkArtakMSFT** [comment]
@jbagga, can you please handle this? Thanks!

**Comment by jbagga** [comment]
All the F# templates have a `Microsoft.AspNetCore.App` reference:

- Empty: https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/EmptyWeb-FSharp.fsproj.in#L14
- Web API: https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/WebApi-FSharp.fsproj.in#L15
- Web App: https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/StarterWeb-FSharp.fsproj.in#L17

F# will not be supported for Razor Sdk cc @rynowak

**Comment by Eilon** [comment]
Nice!

**Comment by cartermp** [comment]
Thanks @jbagga
