### ISSUE TITLE
question about window.initialReduxState

### ISSUE THREAD

**Issue by mathysd** [aspnet/templating#411]
The reactredux template creates an index.js file containing:

`// Get the application-wide store instance, prepopulating with state from the server where available.
const initialState = window.initialReduxState;
const store = configureStore(history, initialState);`

What options do I have to initialize this initial state?

**Comment by tpetrina** [comment]
If I remember correctly, you need to utilise `asp-pretender` tag to create that object. It is used by server side rendering.

**Comment by Eilon** [comment]
@tpetrina maybe you meant `asp-prerender` tag? But `asp-pretender` tag sounds cool too 😄

**Comment by mathysd** [comment]
Thanks, I will have a look
