### ISSUE TITLE
Login by email, not by username

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#427]
_From @BolatovAlau on April 1, 2018 22:59_

Asp.Net MVC wants to log in by username, not by email. I think mostly web apps log in by emails, not by username. And, Let's think that user changed his username, and he forgot it?!  But, he surely knows his email, so he should be logged in by email, not by username!

`PasswordSignInAsync(string UserName, string Password, bool RememberMe, bool shouldLockout)`

should be replaced by

`PasswordSignInAsync(string Email, string Password, bool RememberMe, bool shouldLockout)`

Currently I use (Account, Login) which was
```
var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);

var userid = UserManager.FindByEmail(model.Email)?.Id;
```

like this

```
var user = UserManager.FindByEmail(model.Email);

var result = await SignInManager.PasswordSignInAsync(user.UserName, model.Password, model.RememberMe, shouldLockout: false);

var userid = user?.Id;
```
Sorry for perfect English

_Copied from original issue: aspnet/Mvc#7588_

**Comment by Eilon** [comment]
_From @BolatovAlau on April 1, 2018 23:4_

and in the ForgotPassword method:

` var user = await UserManager.FindByNameAsync(model.Email);`

it wants to find a user using the name, but the parameter is an email!

it also should be replaced by

`var user = await UserManager.FindByEmailAsync(model.Email);`

**Comment by Eilon** [comment]
@HaoK / @blowdart - any thoughts on this? It's not clear to me where the line is here between the default project templates and Identity itself. Is this all achievable by just changing the code in the project? Or would we need to change/add a feature to Identity?

**Comment by HaoK** [comment]
This is all UI/default template behavior, basically username and email are different things in identity, there's an api to check password against a user instance, and there's apis to find users by user name and email, so the app can do whatever it wants

**Comment by Eilon** [comment]
That was easy. Closing.
