### ISSUE TITLE
The new ReactRedux Template does not come with a HomeController. How do I force user to authenticate from the server?

### ISSUE THREAD

**Issue by larry-lau** [aspnet/templating#441]
I am using AzureAd. How do I force user to authentication? I don't have the HomeController where I used to attach an AuthorizeAttribute.  

Any built in support for this before I head down the middleware path?

Thanks

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@kichalla, can you please advise how the authentication can be configured globally? Link to docs would be great, if there is one on that topic.
