### ISSUE TITLE
Add automated validation of the templates to avoid template authoring bugs in metadata

### ISSUE THREAD

**Issue by Eilon** [aspnet/Templating#444]
To avoid bugs such as the one fixed here: https://github.com/aspnet/templating/pull/443

We should add automated tests that ensure that the template authoring requirements are met by the ASP.NET Core templates. Details TBD.

@phenning @mlorbetske - please provide a link to the "template authoring requirements" doc when available.

**Comment by mkArtakMSFT** [comment]
@phenning @mlorbetske, are the requirements referred above by @Eilon already available?

**Comment by ryanbrandenburg** [comment]
This issue is blocked as we can't write tests against authoring requirements until we have them.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, please sync up with @phenning offline regarding this.

**Comment by ryanbrandenburg** [comment]
Talked to @phenning offline, he says he should be able to get started on this in the next few days or so.

**Comment by mkArtakMSFT** [comment]
Closing this as it seems there no action for us to be taken here.
