### ISSUE TITLE
Update Web API templates to use new Web API conventions 

### ISSUE THREAD

**Issue by danroth27** [aspnet/templating#45]
We are adding some new [Web API specific conventions]() that we will need the Web API project and time templates to react to.

We are adding `[ApiController]` attribute as the way to opt-in to new API specific conventions and behaviors that are tuned around best practices for APIs.

This will include:
- Automatically responding with a 400 when validation errors occur (using https://tools.ietf.org/html/rfc7807)
- Infer smarter defaults for action parameters (`[FromBody]` for complex types, `[FromRoute]` when possible, otherwise `[FromQuery]`)
- Web API controllers should derive from ControllerBase (see https://github.com/aspnet/templating/issues/82)

**Comment by Eilon** [comment]
Added this to the list above:

- Web API controllers should derive from ControllerBase (see https://github.com/aspnet/templating/issues/82)

**Comment by Eilon** [comment]
@danroth27 / @rynowak / @pranavkm - should we get this into Preview1? Seems like a simple change that will help us get feedback on the greatness of `[ApiController]` and friends

**Comment by pranavkm** [comment]
With the exception of the first bullet not being fully fleshed out (we have the validation filter, we don't do RFC7807), there's enough in here to start getting some feedback.

**Comment by rynowak** [comment]
Should we add `[ApiController]`?

**Comment by danroth27** [comment]
I think we should
