### ISSUE TITLE
[Preview2-Validation] Scaffolding using EF CRUD should create a sub folder automatically

### ISSUE THREAD

**Issue by kichalla** [aspnet/templating#450]
**Repro:**
- Create a new `WebApplication` template based project
- Add a new class like the following
```c#
public class Customer
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int ZipCode { get; set; }
}
```
- Right click on Customers folder | Add Razor Page.. | Razor Pages using EntityFramework (CRUD) | Add | Choose Customer model class and ApplicationDbContext | Add

**Expected:** A `Customers` folder is created and the RazorPages views are generated in it.
**Actual**: A warning dialog like the following
![image](https://user-images.githubusercontent.com/6559784/38339302-67257a46-3822-11e8-83b3-290303e2d8ce.png)

In MVC scaffolding when we right-click on the Controllers and scaffold a controller, we use the plural service to automatically suggest `CustomersController` and also generate the views in `Customers` folder. We could do something like this for RazorPages too

**Comment by Eilon** [comment]
Should this be in the Scaffolding repo?

**Comment by Eilon** [comment]
This issue was moved to aspnet/Scaffolding#720
