### ISSUE TITLE
AllowedHosts configuration is incorrect in project templates

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/templating#451]
The non-empty project templates include a configuration entry in `appsettings.json` to configure the host filtering middleware (included by default in `DefaultWebHost`), however the format is incorrect (it wasn't changed from an earlier design). This results in changes to the value to restrict valid host names not being picked up, unless the format is also changed (the array .

**Expected**
``` json
   "AllowedHosts": "*"
```

**Actual**
``` json
   "AllowedHosts": [ "*" ]
```

**Comment by Eilon** [comment]
@jbagga - this can be closed as 3-Done right?
