### ISSUE TITLE
Angular template does not work on Windows Server 2012 R2 default web browser

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/templating#456]
Not sure if this is something we support but figured I'd log it anyways. The angular template doesn't work on IE11:

![image](https://user-images.githubusercontent.com/2008729/38443579-060ae414-39a1-11e8-8728-cde4b816d3a7.png)

**Comment by NTaylorMullen** [comment]
@Eilon @mkArtakMSFT  how much do we care about this in regards to preview2? My guess is that this is a corner case scenario that shouldn't be a blocker but not my call 😉

**Comment by Eilon** [comment]
Well it's by-design so we definitely won't fix it...

**Comment by Eilon** [comment]
IE is not supported out-of-the-box with the SPA templates. You have to install a polyfill library that provides the missing functionality to IE. All other major browsers should work out-of-the-box.
