### ISSUE TITLE
ConfigureHttps checkbox doesn't work when unchecked.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/templating#457]
This is might be an external issue but I wasn't sure where to log it so figured here was a good start.

If you uncheck "ConfigureHttps" when creating your project:
![image](https://user-images.githubusercontent.com/2008729/38448558-d4e4eb50-39b9-11e8-8bb8-20d525c298cb.png)

It generates the project without the `UseHttps` code in startup but still configures your `launchSettings.json` to use ssl:
```JSON
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:60074",
      "sslPort": 44383
    }
```

Which in turn then ends up spamming you to configure SSL:
![image](https://user-images.githubusercontent.com/2008729/38448632-76c8a916-39ba-11e8-8d03-b75378e7ee2c.png)

And boots to the Https version of your site.

@Eilon @mkArtakMSFT this is pretty bad. Basically makes the "don't configure https" options in VS useless
@phenning @BillHiebert

**Comment by mkArtakMSFT** [comment]
@jbagga, can you please confirm that this is an issue in templating? Thanks

**Comment by jbagga** [comment]
This is a bug in templating. The launchSettings.json should check for NoHttps option and not sslPort if it is true (like it does for setting applicationUrl for Kestrel)

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, seems a simple workaround would be to just update the `lunchSettings.json` to specify http - and that would do it, correct?

**Comment by NTaylorMullen** [comment]
> seems a simple workaround would be to just update the lunchSettings.json to specify http - and that would do it, correct?

Yup, that will fix the issue for the users current project.

**Comment by jbagga** [comment]
Removing the sslPort would do it for IIS Express. For Kestrel, it should already be correctly configured.

**Comment by mkArtakMSFT** [comment]
Ok, then this is not a concern for preview2. We'll address it during `rc1`. Thanks folks.

**Comment by mkArtakMSFT** [comment]
@danroth27, this is something we should document in the release notes as a `known issue`.

**Comment by Eilon** [comment]
> lunchSettings.json

Call me when this becomes a reality 😄
