### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by blowdart** [aspnet/templating#468]
_From @thiennn on April 12, 2018 2:46_

Bootstrap 4 has been released for a while. It would be nice if Identity UI support it by default

_Copied from original issue: aspnet/Identity#1751_

**Comment by blowdart** [comment]
This would be wider than just identity, so I'm going to move it to the templating repo.

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/templating/issues/278. We plan to do this in 2.2.0.
