### ISSUE TITLE
Remove "Bower" from images that appear in Web Templates

### ISSUE THREAD

**Issue by justcla** [aspnet/templating#469]
The web template for ASP.NET Core MVC web app includes four banner images. One of the images is about "Packages" and lists Bower (along with NuGet, npm and Gulp).

Bower is no longer supported by Visual Studio, so we should update the image, or remove it from the templates.

![image](https://user-images.githubusercontent.com/17131343/38705439-6aa1d326-3e5e-11e8-95e2-22c9d11bfa29.png)

**Comment by justcla** [comment]
Note, please check all other web templates for use of this image.

**Comment by DamianEdwards** [comment]
I think we should just remove this entire panel from the carousel, as everything on there is kinda contentious now.

**Comment by Eilon** [comment]
These "images" are SVG files. In particular, `banner3.svg`, such as this instance: https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/wwwroot/images/banner3.svg

So I guess we should delete banner3.svg from everywhere, and rename banner4 to banner3.
