### ISSUE TITLE
[Help] How do you write acceptance tests?

### ISSUE THREAD

**Issue by LukeBillo** [aspnet/templating#472]
Just wondering how you'd go about writing acceptance tests / end to end tests with these templates? Specifically, the Angular + .NET Core template - I've attempted to run Kestrel via IWebHost in acceptance tests using a .dll and then run Selenium, but couldn't get this to work and it seems quite messy.

Apologies if this has been answered elsewhere.

**Comment by Eilon** [comment]
Selenium is definitely one way to go, and we use it as well to test the templates here.

Beyond that, we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the `asp.net-core` tag to get broader views from the community. Thanks!
