### ISSUE TITLE
Remove wwwroot folder from Web API project template

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templating#478]
The latest Web API project template includes a _wwwroot_ folder. Since the controller (*ValuesController.cs*) derives from *ControllerBase*, MVC views aren't supported. It would then make sense to remove anything else from the template related to UI/static resources. Sure, I may add the folder back if I'm customizing my Swashbuckle-based help pages. I can't think of any other time I've used that folder in this template. Thoughts?

**Comment by GeekyMonkey** [comment]
Sounds like it would be a cleaner Angular dot net solution rather than a dot net web app with angular thrown in

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this issue.
@DamianEdwards thoughts?
