### ISSUE TITLE
Remove Bower from ASP.NET Core project templates

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/templating#48]
Remove Bower completely from the ASP.NET Core project templates and just leave the client-side files in their existing places (e.g. `wwwroot/lib/blah`).

We'll be moving to the new Library Manager (PackMan) in a release later on, but Bower is done now.

#23

**Comment by guardrex** [comment]
@DamianEdwards Do you want this change in topic samples as well? I was about to open an issue to fix topic samples to make them work properly with Bower and `BundlerMinifier.Core` (many don't because they don't include proper references/target(s) for non-VS dev scenarios); however, if you want both stripped out, I'll recast the issue over there.

**Comment by DamianEdwards** [comment]
As @madskristensen says, we're working on a replacement so I wouldn't add anything now as it'll become obsolete within the next few months or so.

So for now, if anything, we should have a topic that covers adding and using NPM along with gulp/a standard NPM script/webpack to move files to wwwroot. That'll be useful in the future for customers who choose to do that anyway.

**Comment by guardrex** [comment]
At least some of the current samples are broken for non-VS (and offline) scenarios. It's the result of two situations: On the one hand, we have samples without the correct references and targets to make Bower and BundlerMinifer work. On the other hand, we also have a *.gitignore* entry that prevents us from uploading *wwwroot/lib* folder contents to the repo. Many/most samples *don't* have the *lib* folder contents.

The issue I was going to open was just going to say that we need the references and targets today or ... as you say ... we could lift the restriction on *wwwroot/lib* from *.gitignore*. I could open the issue to say that we should remove Bower and BundleMinifier configuration files and add *lib* assets to each sample.

Sounds like you prefer that we just use *wwwroot/lib* right now. Not that a small green dinosaur's opinion matters (it doesn't lol), but I like that approach. I like Gulp, too.

I'll open a 2nd issue on:

> a topic that covers adding and using NPM along with gulp/a standard NPM script/webpack to move files to wwwroot

**Comment by Eilon** [comment]
@SteveSandersonMS can you take a crack at this for the 2.0.x templates? The trick here will be figuring out the process for doing this in a patch, for which I don't know the exact process. You'll need to chat with the likes of @seancpeters , @mlorbetske , and @mikeharder .

We'll need to get this figured out ASAP so we can get the patch built out and ready for verification.

**Comment by SteveSandersonMS** [comment]
@Eilon Will do.

**Comment by SteveSandersonMS** [comment]
@guardrex 

> we could lift the restriction on wwwroot/lib from .gitignore

Which `.gitignore` file are you referring to? There doesn't appear to be one in the 2.0 templates here, plus when I create an actual project using the 2.0 SDK it doesn't contain a `.gitignore` file. If I'm missing something please let me know as we'd have to update that for the 2.0.3 patch.

**Comment by guardrex** [comment]
@SteveSandersonMS It's ours ... aspnet/Docs. It's fixed ... https://github.com/aspnet/Docs/pull/4532

All new doc samples and sample updates will have full static assets and no Bower/`BundlerMinifier.Core` bits.
