### ISSUE TITLE
Update THIRD-PARTY-NOTICES link to point to git tag for 2.1 release

### ISSUE THREAD

**Issue by jbagga** [aspnet/templating#480]
See https://github.com/aspnet/templating/issues/330#issuecomment-381224180

Create a Git release **tag** for a version of https://github.com/aspnet/templating/blob/dev/src/THIRD-PARTY-NOTICES that has what we want for the 2.1.0 RTM 
~Update the AKA.MS link (example: https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/.template.config/template.json#L16) to point to the tag above for RazorPages, StartWeb-CSharp and StarterWeb-FSharp templates~

Update: The link that we already have at https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/.template.config/template.json#L16 should be redirected to point to the git tag for 2.1.0 release. No need to update the templates

**Comment by muratg** [comment]
@mkArtakMSFT This is in 2.1.0. Will you be sending the shiproom template?

**Comment by muratg** [comment]
@mkArtakMSFT Is this in 2.1.0?  Will you be sending the shiproom template?

**Comment by mkArtakMSFT** [comment]
There is no need for Shiproom approval for this. We've talked about this already in Shiproom during RC, and I said that we are tracking the RTM change as well. @muratg

**Comment by mkArtakMSFT** [comment]
@muratg, there is no action here related to a code change. I'll just update the FWLINK to point to the new location after we'll have the release tag created.

**Comment by mkArtakMSFT** [comment]
Just updated the link.
