### ISSUE TITLE
In ASP.NET Core 2.0 templates, remove EF Core and SecretManager tool references from csproj for CLI version 2.1.300 or higher

### ISSUE THREAD

**Issue by balachir** [aspnet/templating#485]
With latest 15.7 build + CLI version 2.1.300-preview3-008646 installed,

1. File > New > ASP.NET Core Web Application
    .NET Core > ASP.NET Core 2.0 > Web Application > Individual User Accounts
2. View Error List

**ACTUAL**
Warnings in Error list about obsolete tool references

![image](https://user-images.githubusercontent.com/8246794/39137407-51748368-46d2-11e8-9f14-426b04dba394.png)

**EXPECTED**
I was wondering why we should have these DotNetCliToolReference entries in csproj for ASP.NET Core 2.0 projects and then warn immediately after project creation.

Can we simply remove them from the template when the CLI version is 2.1.300 or higher?

**Comment by muratg** [comment]
These seem to be properly removed from the template: https://github.com/aspnet/templating/blob/release/2.1/src/Microsoft.DotNet.Web.ProjectTemplates/StarterWeb-CSharp.csproj.in

(Contrast with 2.0 file and see the reference)

Can you try the command line `dotnet new` experience?

**Comment by balachir** [comment]
Yes it's fine for the ASP.NET Core 2.1 templates. From my title and repro steps, I'm suggesting that we remove these from the ASP.NET Core 2.0 templates when the templates are part of CLI 2.1.300 or higher.

**Comment by muratg** [comment]
Ah, I see. 

It's the new RC1 SDK with 2.0 templates having obsolote tool warnings. 

I don't think this is escrow resetting, but we should consider it for the RTM.  cc @livarcocc and @Petermarcu for their thoughts.

**Comment by balachir** [comment]
Agree. I'm fine with fixing this for 2.1 RTW

**Comment by DamianEdwards** [comment]
Aren't those templates shipped in the 2.1.2xx SDKs though? That is, I didn't think we even had 2.0 templates in 2.1.3xx SDKs.

**Comment by muratg** [comment]
Good point!  @balachir can you find out where do those templates come from in your testing?

**Comment by balachir** [comment]
@phenning / @seancpeters, do you know the answer to Damian's question?
/cc: @vijayrkn

**Comment by phenning** [comment]
Damian is right, 2.0 Templates will come from 2.1.200 SDK, not 2.1.300 SDK.

**Comment by balachir** [comment]
I see, so 2.1.300 SDK ships only ASP.NET Core 2.1 templates? Then I suppose we cannot do much about this issue. 

It still feels like an odd experience though that with the 2.1.300 SDK installed, user will get warnings out-of-the-box when creating ASP.NET Core 2.0 project. I wish there was an easy way to solve it.
