### ISSUE TITLE
Remove AspNetCore TargetFrameworkVersions workaround

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/Templating#488]
Revert https://github.com/aspnet/templating/pull/487 when we update our TFM or have released 2.1.0.

**Comment by ryanbrandenburg** [comment]
This seems to be [already done](https://github.com/aspnet/Templating/blob/release/2.2/test/GenerateTestProps.targets#L8). Closing. Re-open if I mis-understood.
