### ISSUE TITLE
Show 'Add Razor Page...' in the menu in Razor Pages web application

### ISSUE THREAD

**Issue by kichalla** [aspnet/Templating#490]
I wanted to add a razor page in an area of a Razor web pages application, but the top menu item says 'Controller..'. Since this is a Razor Pages web application, we should show 'Razor Page...' as the default option.

![image](https://user-images.githubusercontent.com/6559784/39185995-f0936cec-477d-11e8-877f-04197dfa836b.png)

**Comment by mkArtakMSFT** [comment]
@seancpeters, is this something to be moved to `Scaffoling` repo?

**Comment by seancpeters** [comment]
It's a scaffolding-related issue, but the required change would be to Visual Studio - not a change in the aspnet/scaffolding repo.

**Comment by mkArtakMSFT** [comment]
@seancpeters, @pranavkm, do you know where this should be moved to?

**Comment by mkArtakMSFT** [comment]
@ToddGrun do you know who should own this?

**Comment by vijayrkn** [comment]
you can create a VS issue using report a project/Provide a suggestion
![image](https://user-images.githubusercontent.com/3981619/41441025-b18d7da4-6fe5-11e8-8f41-47fdb770dcdf.png)

We will route it to the Scaffolding crew from there.

**Comment by Eilon** [comment]
@kichalla - can you report this via VS so we can close this issue?

**Comment by kichalla** [comment]
Sure, I created an issue now using VS feedback:
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/34785640-show-razor-page-in-add-menu-for-a-razor-pag
