### ISSUE TITLE
Razor Class Library template should be in the .NET Standard node of New Project dialog rather than in One Asp Net dialog

### ISSUE THREAD

**Issue by balachir** [aspnet/templating#491]
**INSTALL STEPS**
1. VS 15.7 Preview 5 build d15.7.27622.00
2. CLI for .NET Core 2.1 RC (version 2.1.300-rc1-008662)

**ACTUAL**
The new "Razor Class Library" template currently shows up in the One Asp Net dialog when "ASP.NET Core 2.1" is selected

When you create a project using the template, the TFM in csproj is netstandard2.0. It's unclear from the One Asp Net UI that the project's TFM will be netstandard2.0 and it does not really correlate with the ".NET Core / .NET Framework" dropdown in the One Asp Net dialog.

![image](https://user-images.githubusercontent.com/8246794/39195978-db0aeaa4-4795-11e8-97c7-60f63ba557f3.png)

**EXPECTED**
Suggestion: Below "Class Library (.NET Standard)" template, there can be a "Razor Class Library (.NET Standard)" template
![image](https://user-images.githubusercontent.com/8246794/39196481-1a275e2e-4797-11e8-916f-2f0c9992dc41.png)

Would the ".NET Standard" node in New Project Dialog be a better location for the "Razor Class Library" template? If the template applies to ASP.NET Core 2.1 projects only, perhaps we can get the template to show up only when the CLI for .NET Core 2.1 is installed.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
