### ISSUE TITLE
sri: requested without the "integrity" attribute

### ISSUE THREAD

**Issue by ghost** [aspnet/templating#498]
default ASP.NET Core Web Application using Kestrel

- `<script src="/lib/bootstrap/dist/js/bootstrap.js"></script>`
- `<link rel="stylesheet" href="/css/site.css">`
- `<link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css">`
- `<script src="/lib/jquery/dist/jquery.js"></script>`
- `<script src="/js/site.js?v=ji3-IxbEzYWjzzLCGkF1KDjrT2jLbbrSYXw-AhMPNIA"></script>`

[Require scripts and styles to use subresource integrity](https://sonarwhal.com/docs/user-guide/rules/rule-sri/)

**Comment by mkArtakMSFT** [comment]
Closing this, as the maintenance cost with the added integrity attribute will fall on the users, who will have to now update the hash on every single change. That can result in those references not to load up, and cause bigger problems.
/cc @DamianEdwards
