### ISSUE TITLE
Angular template incompatible with NodeJs 10

### ISSUE THREAD

**Issue by mikeharder** [aspnet/templating#513]
The Angular template is currently incompatible with NodeJs 10.  The fix may be to upgrade `node-sass` to `4.9.0` (https://github.com/sass/node-sass/issues/2345).

# Repro Steps
1. Install NodeJs 10
2. `dotnet new angular`
3. `dotnet build`

# Error
```
> node-sass@4.7.2 install C:\Temp\angular\ClientApp\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.7.2/win32-x64-64_binding.node":

HTTP error 404 Not Found
```

**Comment by muratg** [comment]
This was approved in the shiproom today.

**Comment by mkArtakMSFT** [comment]
Thanks @muratg!

**Comment by kichalla** [comment]
b7eacbb1c33457358dbf75cb83a8630a6373d793
