### ISSUE TITLE
Mvc Web App template inside docker tries to connect to localdb

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/Templating#52]
Moved from https://github.com/aspnet/EntityFrameworkCore/issues/10002 by @smitpatel 

Steps:
Create new ASP.NET Core Web Application
Choose Web Application template for 2.0
Add individual accounts auth
Enable Docker support for windows.
Restore packages/build solution etc.
Press F5

Above will fail due to https://github.com/aspnet/Mvc/issues/6923
Once you correct the URL to http://172.21.203.31/
Website loads correctly. But when trying to register User, it fails with following error
![image](https://user-images.githubusercontent.com/1528107/31301164-d558664e-aaac-11e7-8ea4-284f0abd6581.png)

Essentially it is trying to connect to localdb which does not exist inside docker container (for obvious reason)

**Comment by Eilon** [comment]
@natemcmaster - any ideas on this? What could/should we do differently in the templates to avoid this?

**Comment by natemcmaster** [comment]
You could create new templates that generate a setup using SQL server via docker-compose. This will require VS changes. The existing vs docker tooling doesn't participate in the generation in a way that makes this possible.

**Comment by Eilon** [comment]
@glennc - what are your thoughts on this?

**Comment by glennc** [comment]
@natemcmaster You are suggesting here that we scaffold all the docker stuff instead of docker tools since we know to make a different file when using auth?

**Comment by mkArtakMSFT** [comment]
So should this move to some other repo, @natemcmaster, @glennc?

**Comment by natemcmaster** [comment]
I'm not really sure there is a place to move this. We own this experience. If we don't want to support this scenario, I'd vote to close as `wontfix`. IMO that's reasonable - we can't template every possible scenario.

**Comment by mkArtakMSFT** [comment]
Hi.

Thanks for your feature proposal.
While this may be a good idea, this is not a priority for us for the near future.
If, however, we'll see a good community interest in this issue, we'll reconsider it in the future.
