### ISSUE TITLE
Fix the jquery.min.js file in RazorPages web application

### ISSUE THREAD

**Issue by kichalla** [aspnet/templating#523]
https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/wwwroot/lib/jquery/dist/jquery.min.js

This issue is also present in `release/2.1`

**Comment by kichalla** [comment]
cc @mkArtakMSFT

**Comment by natemcmaster** [comment]
@muratg this is a good candidate for the 2.1.x patches.
