### ISSUE TITLE
[Patch for 2.1.x] Fix the jquery.min.js file in RazorPages web application

### ISSUE THREAD

**Issue by kichalla** [aspnet/templating#525]
Original issue: https://github.com/aspnet/templating/issues/523

**Comment by kichalla** [comment]
The following commit, from 'dev' branch, needs to be cherry picked onto the patch branch:
https://github.com/aspnet/templating/commit/90fe58be756b3bc96d527bbdc8a03ce30b56080f

**Comment by mkArtakMSFT** [comment]
@kichalla, I assume this is ready to be closed now, is it?
