### ISSUE TITLE
Windows authentication is not applied on launchSettings.json

### ISSUE THREAD

**Issue by javiercn** [aspnet/templating#528]
Our current launchSettings.json don't apply the proper settings to launchSettings.json

https://github.com/aspnet/templating/blob/4dd1c7ae0677b8b9fcf9f4834a86b2da713d014e/src/Microsoft.DotNet.Web.ProjectTemplates/content/WebApi-CSharp/Properties/launchSettings.json#L3-L9

The workaround is to modify launchSettings.json after project creation by editing the file or through the Visual Studio project properties Window.

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please provide more details regarding what exactly is wrong here?

**Comment by javiercn** [comment]
The settings in launchSettings.json are unconditionally set to 
```
     "windowsAuthentication": false, 
     "anonymousAuthentication": true, 
```
even when windows authentication is used.

**Comment by mkArtakMSFT** [comment]
I see - didn't notice that the actual `if` was commented out.
