### ISSUE TITLE
Remove reference to Microsoft.AspNetCore.Mvc.Razor.ViewCompilation from desktop templates

### ISSUE THREAD

**Issue by pranavkm** [aspnet/templating#530]
For instance - https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/StarterWeb-CSharp.csproj.in#L44

ViewCompilation isn't recommended any longer, and we shouldn't reference it from our templates.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, here is a templating issue to look into.
