### ISSUE TITLE
React & Redux JavaScript unit test fails

### ISSUE THREAD

**Issue by lancscoder** [aspnet/Templating#540]
In both the React and Redux templates the JavaScript test falls with the following error:

```
 [console.error node_modules\fbjs\lib\warning.js:33
   Warning: Failed context type: The context `router` is marked as required in `Link`, but its value is `undefined`.
       in Link (at NavMenu.js:11)
       in NavbarBrand (at NavMenu.js:10)
       in div (created by NavbarHeader)
       in NavbarHeader (at NavMenu.js:9)
       in div (created by Grid)
       in Grid (created by Navbar)
       in nav (created by Navbar)
       in Navbar (created by Uncontrolled(Navbar))
       in Uncontrolled(Navbar) (at NavMenu.js:8)
       in Unknown (at Layout.js:9)
       in div (created by Col)
       in Col (at Layout.js:8)
       in div (created by Row)
       in Row (at Layout.js:7)
       in div (created by Grid)
       in Grid (at Layout.js:6)
       in Unknown (at App.js:9)
       in Unknown (at App.test.js:7)](url)
```

This is because the `<App />` is trying being rendered outside the context of a Router. Therefore when a `<Link />` is being rendered there is no context and the above error is thrown.

This can be resolved by wrapping the `<App />` component in the test in a `<MemoryRouter />` (and in teh case of the Redux template a mock store as well).

I've submitted a PR that fixes the issue: https://github.com/aspnet/templating/pull/539

**Comment by mkArtakMSFT** [comment]
Thanks @lancscoder for reporting the issue as well as your effort.
@ryanbrandenburg, can you please look into the #539 PR?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, seems like the PR has been already merged. Can you please verify that the change is in release/2.2 milestone, as the PR was for aspnet/dev branch.

**Comment by ryanbrandenburg** [comment]
Yep, this is in release/2.2.
