### ISSUE TITLE
Privacy page/view question

### ISSUE THREAD

**Issue by guardrex** [aspnet/templating#544]
Hello @jbagga @natemcmaster ... Was it intentional to leave the Privacy page link out of *_Layout.cshtml*? ...

```cshtml
<li><a asp-page="/Privacy">Privacy</a></li>
```

I'm working 2.1 doc sample updates and plan to wire the page/view up in the layout unless you instruct me not to do so.

**Comment by natemcmaster** [comment]
Not sure. @mkArtakMSFT @ryanbrandenburg would know.

**Comment by danroth27** [comment]
It's linked to from the cookie consent UI. It makes sense to me that it would be linked to from the layout as well. https://github.com/aspnet/templating/issues/551

**Comment by guardrex** [comment]
I see. I usually place it in the footer; but if the consent UI is always available, then visitors can get to it easily enough. I was mistaken that the consent UI goes away after acceptance.

**Comment by danroth27** [comment]
> I was mistaken that the consent UI goes away after acceptance.

The consent UI isn't always available. Once you accept you no longer see it. I agree the link should be available from the layout. That's why I opened https://github.com/aspnet/templating/issues/551

**Comment by guardrex** [comment]
Sorry ... I'm out on the :bicycle: ... I should've clicked the issue.

*Don't bike and work at the same time.* :smile:
