### ISSUE TITLE
Default templates should contain libraries from some package manager rather than an embed

### ISSUE THREAD

**Issue by hajekj** [aspnet/templating#549]
When you scaffold a new project, it contains a folder with frontend packages like jQuery and Bootstrap in `wwwroot\lib`. This then results in people commiting the code into Git repositories without excluding it which adds overhead to the repos. I believe that front-end packages should be treated just like Nuget or NPM packages - you don't commit those to Git either.

Since it seems like ASP.NET Core is stepping away from Bower, it would be nice to either have those packages loaded from NPM or some other package source.
Those packages should then be downloaded during the build phase configured in .csproj.

- https://github.com/aspnet/templating/tree/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/wwwroot/lib
- https://github.com/aspnet/templating/tree/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/wwwroot/lib

I think this would set a better example of treating 3rd party libraries and Git best practices and hygiene. I understand that having 4 small libraries in Git doesn't do any harm, but once developers start adding more, it could be a problem.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS thoughts?
/cc @danroth27

**Comment by danroth27** [comment]
@justcla I believe this is the problem that LibMan is eventually intended to solve without pulling in a Node dependency.

**Comment by hajekj** [comment]
Oh that's awesome! Actually, something I have been looking for! I have VS2017 15.7.3 but the GUI is not available. Is there anything special I need to do to enable it or is it not shipped in that version of VS yet?

**Comment by danroth27** [comment]
@hajekj LibMan hasn't shipped yet. It was available in preview form at one point, but it wasn't quite ready to make it into VS2017 15.7. It's actively being worked on though.

**Comment by hajekj** [comment]
Ah, I see! Well, I am going to use it manually, since it will simplify my .csproj. Anyways, I suggest keeping this issue open until it is shipped so the templates can be updated with this feature.

**Comment by danroth27** [comment]
We're tracking updating the templates to use LibMan with https://github.com/aspnet/templating/issues/471 I'm going to go ahead and close this issue and you can track the LibMan integration status with the other one. Hope that's ok!

**Comment by hajekj** [comment]
Totally! Thanks a lot for showing me this tool!
