### ISSUE TITLE
react-redux SSR template - DeprecationWarning: Buffer() 

### ISSUE THREAD

**Issue by PatrickKunz** [aspnet/Templating#550]
I created a web page with the core 2.1 react-redux template and didn't change the template base components. I see following warning / error on the production server from time to time (maybe 4 times / day for 2k visitors):

`2018-05-30 23:42:23.2243||ERROR|Microsoft.AspNetCore.NodeServices|(node:7056) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. |url: https://someUrl/|action: Index`

I'm new to this topic, but it looks like a component using a deprecated way to allocate a buffer. The site seems to work fine. Is there a solution for this issue?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @PatrickKunz.
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment]
This seems to be a problem in NodeServices, I created aspnet/JavaScriptServices#1668. We'll leave this issue open to track, and to double check that that resolves the issue.

**Comment by PatrickKunz** [comment]
@ryanbrandenburg thanks for looking at it. 

Keep up the great work on the templates!

**Comment by ryanbrandenburg** [comment]
This should be resolved in the next release. Thanks for the report!
