### ISSUE TITLE
Duplicate files shown for SPA templates in Visual Studio for Mac

### ISSUE THREAD

**Issue by mrward** [aspnet/Templating#559]
**To repro**

1. .NET Core 2.1.300 installed
2. dotnet new angular
3. Open project in Visual Studio for Mac.
4. Expand ClientApp folder in Solution window.

**Expected result**

ClientApp folder shows each file one time only.

**Actual result**

ClientApp folder shows duplicate files.

<img width="280" alt="angular" src="https://user-images.githubusercontent.com/372361/41173799-0fedbfe0-6b0d-11e8-9aba-89ecc83e66d8.png">

**Investigation**

Visual Studio for Mac does not hide duplicate MSBuild items defined by a project in the Solution window (Visual Studio on Windows does hide these duplicate files in the Solution Explorer).

Changing the SPA template to remove the default None items added by the .NET Core SDK fixes the problem - ` <None Remove="$(SpaRoot)**" />`

    <ItemGroup>
      
      <Content Remove="$(SpaRoot)**" />
      <None Remove="$(SpaRoot)**" />
      <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
    </ItemGroup>

This seems to affect all SPA templates from the Microsoft.DotNet.Web.Spa.ProjectTemplates 2.0.0 NuGet package.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mrward.
@ryanbrandenburg, can you please look into this? It seems @mrward  has already a PR to fix this. Please review and merge, if it looks good.

**Comment by ryanbrandenburg** [comment]
Thanks @mrward!
