### ISSUE TITLE
SPA project templates should exec npm install prior to build

### ISSUE THREAD

**Issue by mjrousos** [aspnet/templating#56]
The ASP.NET Core Angular template's csproj runs `npm install` [as part of running webpack for publishing](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/AngularSpa.csproj#L48), but not [as a pre-build step](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/AngularSpa.csproj#L41) (when webpack is also run). 

We should make sure the SPA templates run `npm install` prior to build so that packages are available for webpack build, etc.

**Comment by SteveSandersonMS** [comment]
Thanks - closing this in favour of your pull request #60.

**Comment by Eilon** [comment]
Re-opening this for tracking purposes.

Will this slow down the build on every run?

**Comment by Eilon** [comment]
Ah actually it looks like the target it's in is already smart enough that it will run only conditionally when needed.

**Comment by mjrousos** [comment]
Yes, it should only run if the *wwwroot\dist* folder isn't present yet. It's possible that the dist folder could have been cleaned and we'll run `npm install` when not necessary, but if the packages are present, it should execute fairly quickly and won't run again until webpack outputs are deleted.

If we find that it's an issue, we could consider wrapping the `npm install` call in a check to only execute if *node_modules* isn't present.

**Comment by SteveSandersonMS** [comment]
As per [this comment](https://github.com/aspnet/templating/pull/60#issuecomment-342625435), this requirement is now handled as part of some broader changes, so I'll close this.
