### ISSUE TITLE
can't use typescript for jest tests

### ISSUE THREAD

**Issue by jmagaram** [aspnet/Templating#562]
I had been using create-react-app with the [TypeScript option](https://github.com/wmonk/create-react-app-typescript) and it worked perfectly out of the box. Now I want a "real" web site, using solid Microsoft technology like asp.net core. So I updated to the latest .net core SDK and in Visual Studio started with a "ASP.NET Core Web Application" template with the "React" option. It seems to work. Now I'm trying to use Facebook jest testing. From the command line I can run `npm test` and it does what I expect. OK so now I try to add a single test file that uses TypeScript. My typescript file test looks like this...

    test("simple typescript case", () => expect(5).toBe(5));

I get red squigglies underneath "test" and "expect". The errors are `Cannot find name expect`. I tried following instructions on [using jest with typescript](https://github.com/kulshekhar/ts-jest) but it still doesn't work. There isn't even a `tsconfig.json` file in the project.

I think jest testing should work out-of-the-box with TypeScript. What is the downside to doing that? Or there should be a TypeScript-specific template. I'm a newby to web development and find all this babel, npm, webpack, etc. stuff completely unintuitive and painful and have no clue how to fix it. I actually don't even know how it works in VS Code - the editor somehow knows about the jest `test` and `expect` functions without me even doing an `import`.

This is probably a simple fix for someone who knows what they are doing (not me).

**Comment by jmagaram** [comment]
So I followed the [typescript jest instructions](https://github.com/kulshekhar/ts-jest) and specifically (1) installed ts-jest (2) modified my package.json to include the recommended jest section, and (3) created a tsconfig.json with settings from my VS Code Project. Now Visual Studio seems to recognize the `test` and `expect` functions - intellisense is nice!. But when I run the tests from the command prompt I get this error. Why does this have to be so painful?

    Out of the box, Create React App only supports overriding these Jest options:

    • collectCoverageFrom
    • coverageReporters
    • coverageThreshold
    • snapshotSerializers.

    These options in your package.json Jest configuration are not currently supported by Create React App:

    • transform
    • testRegex
    • moduleFileExtensions

    If you wish to override other Jest options, you need to eject from the default setup.You can do so by running
    npm run eject but remember that this is a one - way operation.You may also file an issue with Create React App
    to discuss supporting more options out of the box.

**Comment by jmagaram** [comment]
Looking at my VS Code package.json that works, each script is suffixed with -ts, like this but when I try to just change it in my Visual Studio project and then try to run the tests using `npm test` it can't find the script files. So maybe your template includes the non-TypeScript scripts.

    "scripts": {
      "start": "react-scripts-ts start",
      "build": "react-scripts-ts build",
      "test": "react-scripts-ts test --env=jsdom",
      "eject": "react-scripts-ts eject"
    },

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by jmagaram** [comment]
No not really. I'm filing a "bug" regarding the ASP.NET Core template I used to create an ASP.NET Core project in Visual Studio. Isn't this repo for the project templates I see in Visual Studio? I used the template and then some basic things don't work out-of-the-box, like Jest testing and TSX. These things work fine with the create-react-app "template" and VS Code, so I assume they should work by using the Visual Studio template as well.

**Comment by mkArtakMSFT** [comment]
The default react template for ASP.NET Core does not use the TypeScript option. In general the react community has not fully bought into TypeScript yet.
That said, if you need to setup TypeScript, you'll have to do it manually. If we hear more people ask for this then we may consider it.
