### ISSUE TITLE
Template tests failing due to compiler error MVC1001

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/templating#563]
Templates for 2.2 do not compile anymore.

```
Pages\Error.cshtml.cs(17,10): error MVC1001: 'ResponseCacheAttribute' cannot be applied to Razor Page handler methods. It may be applied either to the Razor Page model or applied globally. [C:\b\w\33bdfc1cae7b2a38\modules\Templating\test\Templates.Test\bin\Release\netcoreapp2.2\TestTemplates\AspNet.Template.036266b6962741fdbcb9c610de3c49f1\AspNet.Template.036266b6962741fdbcb9c610de3c49f1.csproj]
```
http://aspnetci/viewLog.html?buildId=481546&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest

Caused by changes added in https://github.com/aspnet/Mvc/issues/7684 (@kichalla / @pranavkm )

**Comment by pranavkm** [comment]
Should be fixed with https://github.com/aspnet/templating/commit/e403187be35a25560692aaa7ded495e26bb3ad90
