### ISSUE TITLE
Port ResponseCache attribute on RazorPages Error handler method fix to patch

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Templating#565]
Original issue: https://github.com/aspnet/templating/issues/553

Commit to port: https://github.com/aspnet/templating/commit/e403187be35a25560692aaa7ded495e26bb3ad90

**Comment by pranavkm** [comment]
cc @mkArtakMSFT

**Comment by muratg** [comment]
Approved for 2.1.3.

**Comment by ryanbrandenburg** [comment]
Fixed in #609.
