### ISSUE TITLE
Move cookie consent banner below menu (rather than over it)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Templating#567]
Per discussion offline with @DamianEdwards 

It feels overly intrusive that it covers the site menu. The EU cookie compliance doesn’t require that you block folks from using the site, so there is no reason it can’t be below the menu.

I think hiding the menu makes it hard to grok the page when you first open it. I haven’t seen this on a website before, so it’s a new pattern for folks to parse. My immediate reactions was, “wait, there’s no menu anymore?”. I think this will be especially true for brand new folks who run the site for the first time.

When developing sites, it's also not uncommon to run in Incognito etc. and it's an annoyance to have to dismiss the banner every time, so that you can navigate to the desired page.

## Suggested updates

From an implementation point of view, I’d use a dismissible alert (already baked into Bootstrap) below the nav. Here is a suggested updated implementation for `_CookieConsentPartial.cshtml`:

```
@using Microsoft.AspNetCore.Http.Features

@{
    var consentFeature = Context.Features.Get<ITrackingConsentFeature>();
    var showBanner = !consentFeature?.CanTrack ?? false;
    var cookieString = consentFeature?.CreateConsentCookie();
}

@if (showBanner)
{
    <div id="cookieConsent" class="alert alert-info alert-dismissable">
        <div class="container">
            Use this space to summarize your privacy and cookie use policy. <a asp-page="/Privacy">Learn More</a>.
            <button data-cookie-string="@cookieString" type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
    </div>
    <script>
        (function () {
            document.querySelector("#cookieConsent button[data-cookie-string]").addEventListener("click", function (el) {
                document.cookie = el.target.dataset.cookieString;
            }, false);
        })();
    </script>
}
```

**Comment by DamianEdwards** [comment]
Looks good to me.

**Comment by ryanbrandenburg** [comment]
We're going to do this as part of the Bootstrap4 update, using a dismissable alert customized to have "Accept" instead of "X"
