### ISSUE TITLE
Please update vue/typescript template

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/templating#568]
_From @denimaaark on February 7, 2018 8:41_

Please update vue/typescript template, there are old versions in package.json.

I have try to update manualy but there are errors on starting.

And please add .vue file extension as recognized file for imports etc.

_Copied from original issue: dotnet/templating#1414_

**Comment by mlorbetske** [comment]
_From @seancpeters on February 7, 2018 21:56_

@denimaaark - can you post the output from running `dotnet --info`? Also, could you post the exact command you used to try to update the template?

**Comment by mkArtakMSFT** [comment]
We are no longer maintaining the `Vue` template: https://github.com/aspnet/Announcements/issues/289 
/cc @seancpeters
