### ISSUE TITLE
ASP.NET CORE 2.1 Angular Template: JQuery and Bootstrap Javascript not rendering in build

### ISSUE THREAD

**Issue by ramious76** [aspnet/Templating#569]
When doing a new build off of the supplied template for an ASP.NET Core with Angular template the default web application does not compile the Bootstrap java into the presented web page.  When adding it manually it turns out that this applies for JQuery as well that Bootstrap requires.

You can recreate this by simply adding the markup example from Bootstrap documentation for 3.3 to the home page and validate the java performs its functions

```
<div>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Home</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Messages</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Settings</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="home">...</div>
    <div role="tabpanel" class="tab-pane" id="profile">...</div>
    <div role="tabpanel" class="tab-pane" id="messages">...</div>
    <div role="tabpanel" class="tab-pane" id="settings">...</div>
  </div>

</div>
<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade in active" id="home">...</div>
  <div role="tabpanel" class="tab-pane fade" id="profile">...</div>
  <div role="tabpanel" class="tab-pane fade" id="messages">...</div>
  <div role="tabpanel" class="tab-pane fade" id="settings">...</div>
</div>

```
This example the tabs will not change.  My work around is to manually add the bootstrip.min.js and jquery-1.9.1.js to the assets and call them in the index.html and restores their functionality.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @ramious76.
What version of the SDK are you having this issue with?

**Comment by ramious76** [comment]
Just installed the .NET Core 2.1 SDK v2.1.300

**Comment by mkArtakMSFT** [comment]
@ramious76, could you please share a repro project with us?

**Comment by ramious76** [comment]
How and where can I send it?

**Comment by ramious76** [comment]
Posted  [GitHub/ramious76/BootstrapJavaTest](https://github.com/ramious76/BootstrapJavaTest )

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment]
I was able to replicate your problem. One solution I found was to do something like [this](https://github.com/aspnet/Templating/commit/e4d8bb9aa4fcec1a716a6f226201a5143893d4e0). That is, include jquery and bootstrap in your angular.json `scripts` array.

@SteveSandersonMS is that a normal way of doing things in Angular? If so we should probably add it to our templates.

**Comment by SteveSandersonMS** [comment]
@ryanbrandenburg Yes, that's a perfectly reasonable way to add those scripts.

The reason we didn't include them originally is that not everyone wants them (if they did, we'd have issues posted about this every day, whereas this is the first one I can remember for months). There are other ways of using Bootstrap components in Angular that can be simpler and more lightweight, e.g., Angular-specific variants like [ng-bootstrap](https://ng-bootstrap.github.io/) which doesn't require jQuery or the Bootstrap .js file. Our thinking was that devs will make their own choice about which of these third-party packages meet their needs, and the template itself doesn't require any of them.

Personally I'd be fine with changing the design intent here if you really want to include the bootstrap.js file directly, even though I think our earlier reasoning is also still valid.

**Comment by ryanbrandenburg** [comment]
@SteveSandersonMS that's a reasonable decision, it makes bootstrap.js pay-to-play and keeps the files we serve from the SPA small-ish by default.

I'm going to say we'll stick with Steve's original decision to leave it up to devs unless I hear otherwise.

@ramious76 I believe my suggestion above will solve your problem. Steve's ng-bootstrap suggestion would also fix you, and is probably the "more Angular" way to do this. I'm going to close this issue, if you're still having trouble let us know.
