### ISSUE TITLE
--exclude-launch-settings should set NoDefaultLaunchSettingsFile

### ISSUE THREAD

**Issue by poke** [aspnet/Templating#574]
When you create a new project using the `--exclude-launch-settings` option, the generated template will not contain a `Properties/launchSettings.json` files. However, as soon as you launch Visual Studio, it will automatically create a `launchSettings.json` file since that’s the default behavior with Visual Studio.

So when one enables `ExcludeLaunchSettings`, the following setting should be added to the generated `.csproj`:

    <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>

This disables the default launch settings behavior and will prevent Visual Studio from generating one.

---

If I figure out how the template’s project files are generated, I’ll attempt to provide a PR for this.

**Comment by mkArtakMSFT** [comment]
Thanks for bringing this to our attention, @poke.

**Comment by ryanbrandenburg** [comment]
Thanks for the report and the PR!
