### ISSUE TITLE
[VS2017]Angular-CLI not working on ASP.NET Core with Angular project

### ISSUE THREAD

**Issue by eSPiYa** [aspnet/Templating#576]
When I try to generate a component using `ng g c [component_name]` on Package Manager Console, it returns an error message:
`ng : This command can only be run inside of a CLI project.`

I tried create a new Angular project
`ng new [project_name]`
Then copied the 'angular.json' file to the root folder of my ASP.NET Core with Angular project then set the value 'sourceRoot' with 'ClientApp'. But still have the same error.

Currently I have Node.js v10.0, npm v6.0, and Angular CLI 6.0.

**Comment by JACrazy** [comment]
Create a new dotnet core Angular project using 
`dotnet new angular -o my-new-app`

The latest version of .net core 2.1 generates it as an Angular CLI project rather than as non-CLI like 2.0 used to do.

https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio&view=aspnetcore-2.1

**Comment by eSPiYa** [comment]
@JACrazy 
I tried to create a new project using that command I still can't use commands like creating new component using the command line interface. `Like ng g c [component_name]`. I also just checked the version of .NET Core I'm using(`dotnet --version`), it is 2.1.300. Maybe I should update the project template? But how?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @eSPiYa.
@SteveSandersonMS, is this something we designed for?

**Comment by SteveSandersonMS** [comment]
`ng` commands have to be run inside the `ClientApp` subdirectory, not the project root. Then they will work as normal.
