### ISSUE TITLE
Google OAuth with Angular Template

### ISSUE THREAD

**Issue by LukeBillo** [aspnet/Templating#577]
When selecting the standard web application template in Visual Studio, it offers the "change authentication" option and provides templates for individual accounts, windows authentication, etc. - it would usually generate code to allow integration with Google OAuth using Identity framework.

Is there any way to achieve the same using the .NET Core 2.0 Angular template? I have attempted to do a simple Angular form and POST to a controller which then used the SignInManager, but this didn't work as it returned a 302 redirect (to Google's login page) which Angular seemingly intercepted and ignored.

Unsure if this issue belongs in aspnet/identity - please advise. :)

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
/cc @javiercn

**Comment by mkArtakMSFT** [comment]
@blowdart, do you have any recommendations regarding how to configure GoogleAuth in SPA template?

**Comment by blowdart** [comment]
Nope.

**Comment by SteveSandersonMS** [comment]
I don't think we have a specific recommendation, but since the Angular app in the template is a standard Angular CLI one, whatever approach is recommended for Angular CLI apps should work the same. As far as I'm aware, it wouldn't make any difference that the files are being served by ASP.NET Core, since the auth flow and use of auth tokens is entirely client-side.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
