### ISSUE TITLE
Razor Class Library Project template incorrectly sets layout to null

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Templating#579]
[This](https://github.com/aspnet/templating/blob/e403187be35a25560692aaa7ded495e26bb3ad90/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorClassLibrary-CSharp/Areas/MyFeature/Pages/Page1.cshtml#L4) sets the default view's layout to `null`. This conflicts with the current [RCL doc](https://docs.microsoft.com/en-us/aspnet/core/mvc/razor-pages/ui-class). Basically if you follow the doc you end up getting a layoutless page.

Docs aside I'd imagine the project template would not set the Layout in the view.

@mkArtakMSFT we should consider this for a patch, it'll confuse the hell out of users.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, does this impact 2.1 only?

**Comment by mkArtakMSFT** [comment]
Fixed in https://github.com/aspnet/Templating/pull/659
