### ISSUE TITLE
Asp.Net Core 2.1+ React Template without CRA

### ISSUE THREAD

**Issue by boraturant** [aspnet/Templating#583]
2.1 SPA templates (React) use Create-React-App, which is not flexible enough for some of us. If you eject CRA or use your own client side webpack config, then the 2.1 Template code (asp.net core side) will be incompatible with your client side. Also, current template does not support injecting hashes in to the .cshtml side and lacks other server-client side integrations.

How are you approaching this problem? Are there plans or motivation to work on non-CRA templates?

I have developed a sample template with the latest webpack4 features including dynamic hashed bundle injection to .cshtml files, works great for me, and curious to get community perspective on non-CRA template development.
 
https://github.com/boraturant/aspnetcore-multi-spa-template-react

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @boraturant.
@SteveSandersonMS, @danroth27 thoughts?

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT I would think this would be better handled as a community project. Our goal for the built-in templates was for them to be as standard as possible, hence using CRA.

**Comment by mkArtakMSFT** [comment]
Thanks for the information @SteveSandersonMS.
I agree with the approach. Closing this issue.
