### ISSUE TITLE
Allow the user to decline the cookie policy

### ISSUE THREAD

**Issue by glacasa** [aspnet/Templating#585]
On a new MVC project, there is a banner displayed over the menu, with 2 buttons : one to go to the privacy page, and one to accept it.

As noted on #567, moving the banner below the menu would be better, to let the user navigate the site, but the banner is still here. 

According to GDPR, it must be as easy to refuse than to accept, so we need to have a "Decline" button to remove the banner without accepting the non-essential cookies.

(a cookie containing a boolean saying "refused" would be ok, it's essential to hide the banner permanently, and doesn't contains any personal data)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @glacasa.
@blowdart, @danroth27 thoughts?

**Comment by mkArtakMSFT** [comment]
Thanks @blowdart. I do agree that this is an application concern, so the application owners should handle this as necessary.
That said, I'm going to close this issue as this is not something we'd like to do in the framework.

**Comment by glacasa** [comment]
I agree on this point : the default template shouldn't make decisions for the site owner, but that is what is actually done today.

The RGPD law explicitly forbids to block access to a site until the user "consent".
Maybe you shouldn't add a "decline" button, but the banner blocking all interaction still needs to be changed, because this default behavior is illegal in EU

**Comment by blowdart** [comment]
We're not lawyers, we're not about to start interpreting the GDPR for you, but from our reading the GDPR does not say what you think it says. You should consult your own legal experts in your own country, with an understanding of what your site does in order to get advice.

The implementation will stand.
