### ISSUE TITLE
Angular 6 Update

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Templating#586]
_From @mbeckenbach on June 22, 2018 12:57_

Hi, 

do you have plans to upgrade to angular 6 anytime soon?
The project file and some dependencies have changed there.

Best regards

_Copied from original issue: dotnet/templating#1592_

**Comment by mkArtakMSFT** [comment]
Support for Angular 6 has been added as part of https://github.com/aspnet/Templating/issues/541.
Closing this issue as a dupe.
