### ISSUE TITLE
For updated ASP.NET templates consider using bootstrap.bundle.js dependency

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templating#601]
The Bootstrap 4 has new dependency for everything pop-over like, floating content including modals:
https://getbootstrap.com/docs/4.0/getting-started/introduction/
See section: 'Show components requiring JavaScript'.

To ease issue with updating content from version 3 to 4 and including another dependency, the dedicated version of Bootstrap javascript library is being created and released with current 4.* version:

https://github.com/twbs/bootstrap/issues/23381#issuecomment-330852161

After the templates are updated to Bootstrap 4, see #595, it could be beneficial for developer using templates to use the same `bootstrap.bundle.js` as dependency in client templates to achieve the same gains for developer experience.

Note that at the moment Ajax CDN does not offer that bundled version yet with its hosted 4.* library version:
https://github.com/aspnet/Home/issues/3290

Thanks!

**Comment by ryanbrandenburg** [comment]
[Done](https://github.com/aspnet/Templating/blob/release/2.2/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-FSharp/Views/Shared/_Layout.cshtml#L61).
