### ISSUE TITLE
How to install templates in Visual Studio?

### ISSUE THREAD

**Issue by jhermsen** [aspnet/Templating#605]
Hi according to the repository description this should also be installable to Visual Studio, but how do I do that?

**Comment by Eilon** [comment]
@jhermsen the templates are installed when you install the .NET Core SDK. Can you provide more info about what you tried to do, what happened, and what you expected? Thanks!

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
