### ISSUE TITLE
How to add authentication to SPA templates?

### ISSUE THREAD

**Issue by chris-herring** [aspnet/Templating#612]
In Startup.cs the React SPA template calls UseSpa() which sends everything through the React app. How do I secure this so that I can send to a login page, pass cookies down etc?

Alternatively I can check if the use is logged in on the client side and have the login form in the SPA. In this case is it possible to pass data down from the server e.g. if the user is logged in and profile settings for the user?

**Comment by tpetrina** [comment]
You can use cookies, JWT, depends on your setup.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
/cc @javiercn

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS do you have any advice regarding this?

**Comment by SteveSandersonMS** [comment]
I think @tpetrina is correct.

For example, one solution is to use ASP.NET Core middleware (placed before the `.UseSpa` in the pipeline) to send unauthenticated visitors to a server-rendered login page where they log in and get issued with an auth cookie. After that, the middleware will let visitors through to the SPA, and subsequent `fetch` requests to the server API endpoints will be accompanied by the auth cookie so the server knows what data to let them access.
