### ISSUE TITLE
Angular template - VS2017 npm install fails due to package.json being in the clientapp folder

### ISSUE THREAD

**Issue by tizubythefizo** [aspnet/Templating#616]
When I build or manually try to restore npm dependencies through the UI in Visual Studio 2017 (15.7.5) using the Angular template in .net 2.1 it's failing to do so.

It gives the npm WARN ENOENT ENOENT: no such file or directory, error and seems to be looking in the project root folder for package.json. That's a problem since the template creates the package.json folder in the ClientApp folder instead of root.

Is this intentional for the template to place it there even though it seems to break VS's ability to install packages through the UI?

Even on build it's failing (which is odd since there's some voodoo in the csproj that tells it to look in sparoot, which should be the clientapp folder).

Thanks for any help with this.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tizubythefizo.
@ryanbrandenburg can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment]
This seems to be a VS bug to me. When you right click a package.json and select `Restore Packages` VS should know what folder that file is in and execute the NPM script there. There is no way (that I know of) for the templates to "tell" VS where to look. I recommend using the comment button on the top right of your VS window to report this behavior.

The "voodoo" you refered to worked for me, but it has two conditions.

1. You must be building Debug (The idea here is that when you build something in release you should be using a specific package-lock.json to ensure you get the dependable version).
2. node_modules must not already exist (npm install takes a while, so we don't want to waste a ton of time always re-installing).

If you meet both those requirements and still can't get it to restore I'll need some more information about exactly how you're trying to build, the the result your getting when you do (I assume it's different from the one you listed above).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
