### ISSUE TITLE
Make sure EF migrations in all templates are up-to-date with latest EF migrations code

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#62]
cc @ajcvickers FYI

**Comment by Eilon** [comment]
cc @HaoK @javiercn because of the discussions we're having.

**Comment by Eilon** [comment]
@ajcvickers I'm assigning this to you as well because it's tracking https://github.com/aspnet/templating/pull/134.

**Comment by Eilon** [comment]
And this is listed in preview1, so let's find out ASAP what needs to be done.

**Comment by javiercn** [comment]
I believe this is blocked on https://github.com/aspnet/Identity/issues/1497. I'll let @ajcvickers and @HaoK  and @blowdart figure it out.

**Comment by javiercn** [comment]
The main issue is that the updated migrations apparently create indexes and those indexes are too big in some platforms, but I don't have all the context.

**Comment by ajcvickers** [comment]
@HaoK and I came up with a plan and he is working on it as a priority. Shouldn't be more than a few days work.

**Comment by HaoK** [comment]
5d2f598c8094f4c0b00e430ddd50512fc32fe3eb
