### ISSUE TITLE
Can not run ng-cli commands in ClientApp.

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templating#628]
Moved from https://github.com/aspnet/Docs/issues/7558. Originally opened by @Hypnoes.

> ```
> $ ng generate component livecast
> This command can only be run inside of a CLI project.
> ```
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
> * Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
> * Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=netcore-cli)
> * Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
> * Product: **aspnet-core**
> * GitHub Login: @SteveSandersonMS
> * Microsoft Alias: **scaddie**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Hypnoes.
Can you please provide more details regarding the issue you're facing. Which version of the CLI do you use, and which version of the SDK you've used to create the project?

**Comment by Hypnoes** [comment]
I'm using .net core 2.1.200
Run `dotnet new angular my-new-app`
Run `npm install`
![default](https://user-images.githubusercontent.com/13956546/43694981-9238b75a-9968-11e8-9881-8323713fdad0.PNG)
![1](https://user-images.githubusercontent.com/13956546/43695037-c8c1dd9c-9968-11e8-857a-df6638b6dfcf.PNG)

**Comment by SteveSandersonMS** [comment]
It looks like you have a newer (Angular 6?) version of the `ng` tool installed globally. If you choose to use `ng` as a global tool, its version will have to match the version of Angular used by your template. So you'll need to uninstall the version you currently have (via `npm uninstall -g ng`) then install the one matching your Angular application.

Note that we're updating the template to Angular 6 as part of the next release.
