### ISSUE TITLE
what happened to webpack?

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templating#629]
Moved from https://github.com/aspnet/Docs/issues/7697. Originally opened by @mhamri.

> in the new angular template there is no trace of webpack, what happened, also the doc doesn't cover anything about it

**Comment by Eilon** [comment]
@SteveSandersonMS - can you share thoughts on this?

**Comment by raky291** [comment]
https://github.com/aspnet/JavaScriptServices/issues/1633

**Comment by Eilon** [comment]
Indeed, it looks like https://github.com/aspnet/JavaScriptServices/issues/1633#issuecomment-389873675 has the answer. Thanks @raky291 !
