### ISSUE TITLE
Re-enable tests to run in parallel 

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/templating#63]
On macOS/Linux, there appears to be some race condition with the tests and the template engine, leading to errors such as:

```
==> /Users/namc/.dotnet/dotnet new web [/Users/namc/dev/aspnet/templating/test/Templates.Test/bin/Debug/netcoreapp2.0/TestTemplates/37025cf1fb724909ad785b6ef06a34ac]
 [ERROR] Unexpected end when reading JSON. Path 'TemplateInfo[19].Tags.language.Description', line 1365, position 26.
 [ERROR]    at Newtonsoft.Json.JsonTextReader.ParseValue()
 [ERROR]    at Newtonsoft.Json.JsonTextReader.Read()
 [ERROR]    at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
 [ERROR]    at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
 [ERROR]    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
 [ERROR]    at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
 [ERROR]    at Newtonsoft.Json.Linq.JObject.Parse(String json)
 [ERROR]    at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.EnsureTemplatesLoaded()
 [ERROR]    at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.WriteTemplateCache(IList`1 templates, String locale)
 [ERROR]    at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCacheForLocale(String locale, String existingCacheVersion)
 [ERROR]    at Microsoft.TemplateEngine.Edge.Settings.TemplateCache.WriteTemplateCaches(String existingCacheVersion)
 [ERROR]    at Microsoft.TemplateEngine.Edge.Settings.SettingsLoader.Save(TemplateCache cacheToSave)
```

I've disabled test parallelization for now https://github.com/aspnet/templating/commit/a4ba5a1cb1c61d3a4bead34915baccf438a8d1b3, but it means a full test run can take 10-15 minutes.

**Comment by Eilon** [comment]
@SteveSandersonMS any idea how to resolve this?

**Comment by SteveSandersonMS** [comment]
@Eilon At first glance, no idea, but I will take a look.

**Comment by natemcmaster** [comment]
Likely would be fixed by creating a clean, isolated template engine state for each test, which I believe isn't possible yet. https://github.com/dotnet/templating/issues/806

**Comment by natemcmaster** [comment]
https://github.com/dotnet/templating/pull/1321 should help

**Comment by SteveSandersonMS** [comment]
I re-enabled the parallelization, putting a lock only around the actual `dotnet new` invocation since that depends on exclusive access to global state (at least, until the underlying `dotnet` CLI changes that @natemcmaster mentioned).

Since `dotnet new` call itself only takes a few seconds, serializing access to that doesn't significantly slow down the entire test run. By far the most time-consuming thing is the NPM restore process, which I've also taken separate steps to speed up.
