### ISSUE TITLE
Bootstrap updated to 4.1.2

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Templating#631]
This is probably to work on after the #595 is merged, so just make reference for future update and you could folks treat this as FYI:

- first make sure that MS CDN ships updated version
- make sure the Docs contain updated version
https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview#bootstrap-releases-on-the-cdn

https://github.com/twbs/bootstrap/releases/tag/v4.1.2

@ryanbrandenburg  Ryan, just FYI
/cc 
@ryanbrandenburg 

Thanks!

**Comment by Eilon** [comment]
Given that we just updated to 4.1.1, we should probably wait until much, much later in the release to update to a newer minor/patch version of Bootstrap. Otherwise I think we'll be updating every few weeks, not that I know whether @ryanbrandenburg would necessarily mind doing that 😁

**Comment by ryanbrandenburg** [comment]
We ended up doing this in #595 after all.
