### ISSUE TITLE
Support multiple projects with solution file

### ISSUE THREAD

**Issue by a-patel** [aspnet/templating#64]
I want to create multiple .net core projects with solution files. 
Also project  other referenced added in them.
My Directory structure is like:

|- data (blank or may contain some files)
|- design
|- help
|- **src**
> |-.**sln** (VS solution file)
> |-**Libraries**
  >> |-LIB1.csproj
  >> |-LIB2.csproj
  >> |-LIB3.csproj
> |-**Presentation**
   >>|-PRE1.csproj
   >>|-PRE2.csproj 
 >|-**Tests**
   >>|-TEST1.csproj
   >>|-TEST2.csproj
 >|-**Plugins**
   >>|-Plugin1.csproj
   >>|-Plugin2.csproj

**Comment by a-patel** [comment]
solution file contain more than one class library projects, unit test projects, web/web api projects.
(asp.net core 2.0)
- add unit test/api projects conditionally (as currently support select docker, auth, unit test project selection)

**Comment by Eilon** [comment]
If you're asking for how to create a template that supports this, please log an issue on https://github.com/dotnet/templating.
