### ISSUE TITLE
Angular template: Dependency injection fails for lazy loaded module

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templating#641]
Moved from https://github.com/aspnet/Docs/issues/7826. Originally opened by @tedishero.

Lazy loading itself works, however as soon as I introduce a dependency to a component or service in the lazy loaded module, it starts to complain about not able to resolve dependencies.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tedishero.
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
