### ISSUE TITLE
Angular template: SSR not working

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templating#648]
Moved from https://github.com/aspnet/Docs/issues/7895. Originally opened by @Chris-Devine.

> When checking the fetch data page. I noticed when checking the Page Source Code in a browser that the loading statement was there. 
> 
> This suggests to me that the HTTP call to get the data was not done on the server and was done on the client. I thought this data would come back pre-populated from the server and thus the source code of the page would contain the data. 
> 
> Kind of like what we would want for SEO reasons. 
> 
> My question is, first am i correct in my assumption and if so how do i reflect that in the app
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
> * Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
> * Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
> * Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
> * Product: **aspnet-core**
> * GitHub Login: @SteveSandersonMS
> * Microsoft Alias: **scaddie**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us @Chris-Devine.
@SteveSandersonMS, do you have any thoughts about this? Did we remove support for SSR when we move to the AngularCLI?

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Yes, SSR is no longer enabled by default. The docs for how to enable it are at https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio#server-side-rendering

**Comment by Chris-Devine** [comment]
Hi @SteveSandersonMS, i had enabled the SSR as stated in guide. The issue was the page was rendering before the data was received from the controller.
Can you reopen the issue please

**Comment by SteveSandersonMS** [comment]
The next release of the Angular template will use Angular 6, which is quite different. It may be that different instructions are required for SSR with Angular 6. We'll need to wait until that template is ready to find out. There isn't any further update planned for the earlier Angular template.
