### ISSUE TITLE
Misleading help text for --no-https option

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templating#649]
Execute the `dotnet new mvc --help` command, and you'll see the following help text for the `--no-https` option:

> Whether to turn off HTTPS. This option only applies if IndividualAuth or OrganizationalAuth are not being used.

This text may lead some to believe that `IndividualAuth` and `OrganizationalAuth` are valid values for the `--auth` option. Both `--auth IndividualAuth` and `--auth OrganizationalAuth` result in error messages.

I propose that the help text change to the following:

> Whether to turn off HTTPS. This option only applies if Individual, IndividualB2C, SingleOrg, or MultiOrg aren't being used for --auth.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @scottaddie.
Will you be interested in submitting a PR with the proposed text?
/cc @javiercn

**Comment by javiercn** [comment]
This change sounds good to me. Feel free to send us a PR for it and we'll be happy to take it.
