### ISSUE TITLE
Decide if we want to ship e2e fold in SPA templates

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#654]
We have [this folder](https://github.com/aspnet/Templating/tree/release/2.2/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/ClientApp/e2e) in our SPA templates which is a setup for end-user tests, but we don't provide any testing structure in for example, our MVC template, so @Eilon and I weren't sure if we wanted to do so here.

CC @danroth27 to decide if this is something we want to be doing, or it should be removed.

**Comment by Eilon** [comment]
@SteveSandersonMS - can you share thoughts on the history of this?

**Comment by mkArtakMSFT** [comment]
@danroth27 , assigning to you to come up with a decision.

**Comment by SteveSandersonMS** [comment]
> can you share thoughts on the history of this?

The content in that folder (and indeed in all of the parent-level `ClientApp` folder) is provided by Angular CLI. It's not something we've built ourselves. It's just a standard part of a new Angular CLI project.

I don't see any reason why we'd want to remove this. That would make our templates less consistent with the Angular CLI defaults.

**Comment by mkArtakMSFT** [comment]
Thanks @SteveSandersonMS.
Closing this per your answer.
