### ISSUE TITLE
Include HSTS configuration when using app.UseHsts();

### ISSUE THREAD

**Issue by mark-szabo** [aspnet/Templating#655]
https://github.com/aspnet/BasicMiddleware/pull/354

The new ASP.NET Core 2.1 templates are including `app.UseHsts()`, which is adding the Strict-Transport-Security header. Which is awesome. 
But the default for the max-age parameter in Microsoft.AspNetCore.HttpsPolicy is 30 days to address initial configuration issues when deploying a new app. The configuration of this is not that straightforward, so we should add a configuration code (or a comment at least). Now we are encouraging developers to leave it on 30 days which is not that great...

```
// Change max-age to a longer period (1 year at least) after you are confident with your configuration
services.Configure<HstsOptions>(options =>
{
    options.IncludeSubDomains = true;
    options.MaxAge = TimeSpan.FromDays(30);
});
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @mark-szabo.
@blowdart, do you think we should include a piece of code like this in the templates? Or shuold we just add a comment instead?
/cc @javiercn

**Comment by blowdart** [comment]
If there's an AddHsts or something of that ilk then the comment, maybe point to a docs page via an aka.ms link?

**Comment by mark-szabo** [comment]
Yeah a docs page with a code sample is perfectly fine. @blowdart do you have something like that?

**Comment by javiercn** [comment]
@guardrex @Rick-Anderson This is a doc request. Don't we have this on the HTTPS doc?

**Comment by blowdart** [comment]
Yup - https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-2.1&tabs=visual-studio#http-strict-transport-security-protocol-hsts - needs a little expansion to talk about starting small, then ending up with a year.

**Comment by blowdart** [comment]
PR created https://github.com/aspnet/Docs/pull/7941

We could do the aka.ms link to the URL above in templates without merging that PR anyway.

**Comment by mark-szabo** [comment]
Here it is: https://aka.ms/aspnetcore-hsts

**Comment by mkArtakMSFT** [comment]
@blowdart, what code change you'd like to see in the template? Is the suggestion in the issue what you want?

**Comment by blowdart** [comment]
Add a comment before the HSTS call, saying something like "The default HSTS value is X days. You may want to change this for production scenarios, see link"
