### ISSUE TITLE
Template footers should have year autocompleted

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#657]

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, please have a look at https://github.com/aspnet/Templating/issues/271

**Comment by ryanbrandenburg** [comment]
There's an existing solution to this, the string "copyrightYear" in cshtml files gets replaced with the current year by the templating system, I just need to do the same thing in the RazorPages template.

**Comment by ryanbrandenburg** [comment]
We still have some [instances](https://github.com/aspnet/Templating/blob/release/2.2/src/Microsoft.DotNet.Web.ProjectTemplates/content/RazorPagesWeb-CSharp/Pages/Shared/_Layout.cshtml#L54) of this to clean up.

**Comment by ryanbrandenburg** [comment]
Fixed by #686.
