### ISSUE TITLE
Add HttpsRedirection and HSTS middleware template

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#66]
_From @jkotalik on October 13, 2017 19:22_

With https://github.com/aspnet/BasicMiddleware/pull/264 being added, @Eilon asked me to write templates for this feature.
cc/ @javiercn @Tratcher 

_Copied from original issue: aspnet/Templates#871_

**Comment by Eilon** [comment]
_From @Tratcher on October 13, 2017 19:24_

We need to make sure Kestrel is set up for https first.

**Comment by jkotalik** [comment]
@Eilon my bad. Didn't realize there were two templates repos.

**Comment by Eilon** [comment]
Yeah I have a TODO to add notes to the old repo.

**Comment by Eilon** [comment]
(So, not your fault 😄 )

**Comment by Eilon** [comment]
Let's review the proposed code change with @DamianEdwards .

**Comment by jkotalik** [comment]
This is still pending on picking up configuration in the middleware. Will be added once implemented.

**Comment by javiercn** [comment]
@jkotalik Put out a PR for it and we'll merge it at the appropiate time, but we can start iterating on it.

**Comment by javiercn** [comment]
https://github.com/aspnet/templating/commit/4d2e642b94ad6c2e152e09005c33bac7543bcf04
