### ISSUE TITLE
Template enhancements

### ISSUE THREAD

**Issue by guardrex** [aspnet/Templating#67]
**Updated: 8/6/2018**

### Language

This is probably just a localization issue, but the template is in English. Do you want to set a `lang="en"` here? I do set it on our doc samples.

### Add/update `crossorigin`

Only missing for the Bootstrap stylesheet. Recent updates have squared it (and `integrity`) away in the 2.1 template.

### \<h1> MIA

Pages and views should provide the page/view title in **\<h1>** headings. The current templates ignore W3C advice (ref: https://www.w3.org/QA/Tips/Use_h1_for_Title). I suggest raising the **\<h2>** headings to **\<h1>**, and there's nothing wrong with changing the four **\<h2>** elements on the Index page to **\<h1>** elements ... nothing prevents multiple **\<h1>** elements in HTML5. Could set the sizes of headers in the stylesheet (make them smaller than default) to preserve the current style.

### Void elements

Some of us in the community feel that W3C *hacked* their own spec to allow closing void elements. IIRC Razor needs them generally closed; however, the void elements in the template aren't processed by Razor. I think it would be safe to not close most/all of them (i.e., **\<link>**, **\<meta>**, **\<hr>**).

### Language in the Error page

I recommend some language updates to the Error page. Something like ...

> \<h3>Development Mode\</h3>
> \<p>
>     Swapping to the \<strong>Development\</strong> environment displays detailed information about the error that occurred.
> \</p>
> \<p>
>     \<strong>The Development environment shouldn't be enabled for deployed applications\</strong>. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the \<strong>Development\</strong> environment by setting the \<strong>ASPNETCORE_ENVIRONMENT\</strong> environment variable to \<strong>Development\</strong> and restarting the app or calling \<code>UseEnvironment("Development")\</code> on the host in \<strong>Program.Main\</strong> and restarting the app.
> \</p>

Except for a few style updates, the proposal surfaces `.UseEnvironment()`.

### Extra line space

```csharp
// This method gets called by the runtime. Use this method to add services to the container.
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<CookiePolicyOptions>(options =>
    {
        // This lambda determines whether user consent for non-essential cookies is needed for a given request.
        options.CheckConsentNeeded = context => true;
        options.MinimumSameSitePolicy = SameSiteMode.None;
    });


    services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
}
```

At least in the RP template, there seems to be an extra line space before `AddMvc`.

**Comment by guardrex** [comment]
@natemcmaster @jbagga Just curious if any of these (especially the first two) are under consideration? We can close this if not.

**Comment by natemcmaster** [comment]
cc @Eilon @SteveSandersonMS for triage

**Comment by DamianEdwards** [comment]
@mkArtakMSFT @danroth27 can we look at these suggestions and figure out if any should be applied as part of latest updates in 2.2? I'm particularly interested in `crossorigin="anonymous"` on our `<script>` elements that load from CDNs and would appreciate @blowdart's thoughts on that too.

**Comment by guardrex** [comment]
Recent PRs have fixed a few of the items since I opened this issue. I updated the OP :point_up: today (7/21/2018) based on the 2.1 template.

**Comment by blowdart** [comment]
I didn't even know crossorigin=anoymous existed. But heck yes.

**Comment by guardrex** [comment]
`crossorigin` has been resolved for the scripts but not for the Bootstrap stylesheet.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, please work with @danroth27  to see what's left to be handled here. Let's try to cover these points during 2.2 release.

**Comment by ryanbrandenburg** [comment]
- I'm going to spin this off into it's own issue as it seems like it might require a bit of design.
- The crossorigin thing seems to have been sorted unless you want to point me at a line where it's missed.
- Looks like Privacy was the only remaining offender here, I'll have a PR out in a bit.
- Seems reasonable. I'll try it out.
- I'll play around with that and see how it looks.
- This seems to have been fixed already.

**Comment by danroth27** [comment]
@ryanbrandenburg This all sounds fine, except for the void elements. Let's leave them as closed.

**Comment by ryanbrandenburg** [comment]
This is all done now. Thanks for the report!
