### ISSUE TITLE
CSRF Redirect Link in Fresh .NET Core 2.1.302 SDK ASP.NET Core template is incorrect

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Templating#675]
_From @gortok on August 14, 2018 16:58_

#### Is this a Bug or Feature request?:

Bug
#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

1. Create a new ASP.NET Core web application using the .NET Core 2.1.302 SDK (reproducible on Mac OS command line and on VS 2017 15.7.6) using the following command:

```
 dotnet new webapi --auth Windows
```

2. Go to the `ValuesController.cs` file, and make note of the following text:

```
// For more information on protecting this API from Cross Site Request Forgery (CSRF) attacks, see https://go.microsoft.com/fwlink/?LinkID=717803
```
3. Click on the link; the redirect takes you to here: 

https://docs.microsoft.com/en-us/aspnet/core/security/cross-site-scripting?view=aspnetcore-2.1

The link should take you to here:

https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1

#### Description of the problem:

Redirect link in template to LinkId=717803 is incorrect and redirects you to the page on XSS; where it should redirect you to the page about CSRF, as indicated in the comment text.

_Copied from original issue: aspnet/Mvc#8268_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gortok.
@ryanbrandenburg, can you please look into this? Thanks!

**Comment by ryanbrandenburg** [comment]
@mkArtakMSFT I believe the easiest solution here is to change the reference underlying that link from the redirect service. This has the benefit of fixing everyone who already has that link. @Eilon probably knows the specifics behind getting that changed.

**Comment by Eilon** [comment]
I think @danroth27 is more likely to be able to update that FWLink.

BTW are we sure that *every* use of this link is in regards to CSRF and that it wasn't used elsewhere for other purposes? That is, should we re-point this existing FWLink, or should we create a new FWLink?

**Comment by ryanbrandenburg** [comment]
I did [this search](https://github.com/search?q=org%3Aaspnet+https%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkID%3D717803&type=Code), and it shows me that all instances of that link reference CSRF.

**Comment by danroth27** [comment]
Should be fixed now.
