### ISSUE TITLE
Pass data down in React template

### ISSUE THREAD

**Issue by chris-herring** [aspnet/Templating#676]
Is there a way to pass data down in the rendered page from the React template? For example to pass user settings data down as JSON rendered in the HTML sent down that can be parsed on the client. I know I could use a cookie to achieve this but I don't think that's as robust.

This was easy to do in the previous JavascriptServices template.

**Comment by tpetrina** [comment]
I am having hard time understanding this question. Are you sending JSON from C# to React or from React to HTML and picking it up with javascript?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chris-herring.
Same here, not sure it's clear what your'e trying to do. Can you please provide more details about your scenario?

**Comment by chris-herring** [comment]
Say I'm creating a blogging app and when a user creates a blog post they select a category for the post. These categories are user defined so can not be hard-coded in the form. You could fetch them when the user creates the blog post but that could result in a delay while the categories are loaded. So instead you prefetch them by including them in the initial HTML document sent down by the server. My use case is more complicated than this but hopefully this explains the concept.

An example of this in an ASP MVC view would be:

	@{
		ViewBag.categories = Repository.GetCategories();
	}

	<script type="text/javascript">
		(function () {
			MyAppData = {
				"categories": @Html.Raw(Newtonsoft.Json.JsonConvert.SerializeObject(@ViewBag.categories))
			};
		})();
	</script>

**Comment by tpetrina** [comment]
So you want server side rendering/hydration. In case of first hit, that _is_ possible, but in case of subsequent navigation you are no longer hitting the web endpoint.

How do you propose handling different data requirements per route? Say user requests `/blog/{id}` and another opens `/blog/new`, how will you know which data to load in which case? I smell a giant switch statement there.

**Comment by chris-herring** [comment]
Yes I just need it on first hit. I'm not concerned about subsequent navigation as in practice I not caching data that changes at all based on routing.
