### ISSUE TITLE
How to identify 404 with Angular 

### ISSUE THREAD

**Issue by vasyliv** [aspnet/Templating#681]
How to identify 404 with Angular?
similar issues 

- https://github.com/angular/quickstart/issues/406#issuecomment-288394851
- https://github.com/aspnet/Templating/issues/546

For me, it doesn't work fine, the followed example returns status code 200, but I want to return error code 404 (for analytics) (not 200 as in https://github.com/angular/quickstart/issues/406#issuecomment-288394851)

Here is an example for Node.js (https://blog.thecodecampus.de/angular-universal-handle-404-set-status-codes/), but I can't use it with this template, Do we have something similar?

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, can you please answer this question? Thanks!

**Comment by SteveSandersonMS** [comment]
@vasyliv I assume you're asking about making the SSR response return a 404. In that case, please see https://github.com/aspnet/Templating/issues/587#issuecomment-413601497

**Comment by vasyliv** [comment]
@SteveSandersonMS thanks a lot.
