### ISSUE TITLE
angular.json file missing in the project template

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templating#682]
Moved from https://github.com/aspnet/Docs/issues/8168. Originally opened by @SindhuSaravanan.

> I am not able to find angular.json in the new project template. Hence adding a new angular component fails. Kindly provide the steps
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: 32a18270-91cd-2a02-2eb8-2c8b1ed03737
> * Version Independent ID: c58d57e5-a0c2-201d-f6dd-076ad5971fcb
> * Content: [Use the Angular project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.1&tabs=visual-studio)
> * Content Source: [aspnetcore/client-side/spa/angular.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/angular.md)
> * Product: **aspnet-core**
> * GitHub Login: @SteveSandersonMS
> * Microsoft Alias: **scaddie**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @SindhuSaravanan.
Can you please provide the output of `dotnet --info` command?

**Comment by damienbod** [comment]
This seems like an angular CLI update problem. The .angular-cli.json was renamed to angular.json. To fix, try the ng update @angular/cli after updating the global angular CLI

https://stackoverflow.com/questions/48970553/want-to-upgrade-project-from-angular-v5-to-angular-v6

**Comment by mkArtakMSFT** [comment]
@ryanbrandeburg, is this covered as part of our 2.2 changes?

**Comment by mkArtakMSFT** [comment]
Confirmed that this is done already as part of 2.2 work. Closing the issue.
Thanks @damienbod.

**Comment by SindhuSaravanan** [comment]
Hi Scott,

Thanks a lot for your response. Given below is the output of dotnet --info
command.

.NET Command Line Tools (2.1.104)

Product Information:
 Version:            2.1.104
 Commit SHA-1 hash:  48ec687460

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

Regards,
Sindhu
