### ISSUE TITLE
revoking consent?

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templating#683]
Moved from https://github.com/aspnet/Docs/issues/8174. Originally opened by @joeaudette.

> The new GDPR tools in the latest MVC project templates are a good improvement, but my understanding is that users must have the option to revoke cookie consent once they have given consent, and the template doesn't seem to have any mechanism for that.
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: 28d0490e-205f-20a5-ace5-904f4c8ad78f
> * Version Independent ID: 4a2c8d95-fdd2-fdb1-b61d-802d0a8539c3
> * Content: [General Data Protection Regulation (GDPR) support in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1)
> * Content Source: [aspnetcore/security/gdpr.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/security/gdpr.md)
> * Product: **aspnet-core**
> * GitHub Login: @Rick-Anderson
> * Microsoft Alias: **riande**

**Comment by mkArtakMSFT** [comment]
https://github.com/aspnet/Templating/issues/585

**Comment by blowdart** [comment]
First let's be clear, this is not a legal opinion, nor a recommendation. 

We give you tools to help you meet your GDPR obligations, which you must discover for yourself, in consultation with your own legal advice, modelling and other methods suggested by or listed in the GDPR.

Because we cannot know what you do with data you gather once you have given consent we cannot give a meaningful way to revoke consent within the templates, much like we cannot do a true delete account, as both functions require an in depth knowledge of your data gathering and database structures. 

So this function is all in your own hands, as we cannot know what it means for your systems.

**Comment by Rick-Anderson** [comment]
@joeaudette

```
public class Consent : PageModel
{
    public void OnGet()
    {
    }

    public IActionResult OnPostWithdrawAsync()
    {
        HttpContext.Features.Get<ITrackingConsentFeature>().WithdrawConsent();
        return RedirectToPage("./Index");
    }
}
```

**Comment by joeaudette** [comment]
@Rick-Anderson that looks good to me. I'm going to implement something similar to that in my cloudscribe project. I guess we just need another partial view to be shown once we do have initial consent, but more out of the way like a small link in the footer, next to the privacy policy link. And it can do a post to a method like that to withdraw consent.

**Comment by Rick-Anderson** [comment]
@joeaudette  sounds like a great blog if others want to do the same.

**Comment by joeaudette** [comment]
@Rick-Anderson yes, great idea. Probably a blog post showing how to add it in the standard project templates would be best. Pretty easy to do really. For cloudscribe it will be just built in. I'll see if I can find the time to do that and write a post soon.

**Comment by joeaudette** [comment]
@Rick-Anderson just blogged this, please let me know if you think it is ok or needs any changes.
http://www.joeaudette.com/blog/2018/08/28/gdpr---adding-a-revoke-consent-button-in-aspnet-core

**Comment by Rick-Anderson** [comment]
First let's be clear, this is not a legal opinion, nor a recommendation. I'm not an attorney. But the blog looks great to me.

**Comment by joeaudette** [comment]
Thanks @Rick-Anderson ! and thanks for a great idea for a post!
