### ISSUE TITLE
yarn.lock is included in .gitignore

### ISSUE THREAD

**Issue by vuorinem** [aspnet/templating#69]
https://github.com/aspnet/templating/blob/38be05d4425c465cfa9fbc64c9f7f921e9a05497/src/Microsoft.AspNetCore.SpaTemplates/content/Aurelia-CSharp/.gitignore#L34

Example from Aurelia, but applies to other templates too.

Usually lockfiles should be committed to source control (e.g. Yarn documentation for yarn.lock: https://yarnpkg.com/en/docs/yarn-lock#toc-check-into-source-control). Is there a reason yarn.lock is being ignored?

**Comment by Eilon** [comment]
@SteveSandersonMS thoughts on this?

**Comment by SteveSandersonMS** [comment]
Originally it was unclear what patterns would emerge around `yarn.lock`, but recently it's become clear that consensus is to include it in source control.

So I agree with @vuorinem's implication that we should change this by removing that line from `.gitignore`.

**Comment by Eilon** [comment]
@SteveSandersonMS can you review the PR #177 and merge?

**Comment by SteveSandersonMS** [comment]
Done.
