### ISSUE TITLE
Injecting Data from the Server into the Page

### ISSUE THREAD

**Issue by chris-herring** [aspnet/Templating#690]
create-react-app does supports injecting server data into the page as shown below. How can we do this?

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#injecting-data-from-the-server-into-the-page

> 
> Injecting Data from the Server into the Page
> Similarly to the previous section, you can leave some placeholders in the HTML that inject global > variables, for example:
> 
> <!doctype html>
> 
> <script> window.SERVER_DATA = __SERVER_DATA__; </script> Then, on the server, you can replace __SERVER_DATA__ with a JSON of real data right before sending the response. The client code can then read window.SERVER_DATA to use it. Make sure to sanitize the JSON before sending it to the client as it makes your app vulnerable to XSS attacks.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @chris-herring.
@SteveSandersonMS can you please look into this? Thanks!

**Comment by SteveSandersonMS** [comment]
@chris-herring There's no direct, built-in way to inject server-generated dynamic content into the initial HTML with this template. That's because we're being consistent with CRA's structure which, at least out of the box, assumes it can take entire responsibility for rendering the initial HTML.
