### ISSUE TITLE
NPM dependencies and Task Runner Explorer integration missing with Angular template in VS 2017

### ISSUE THREAD

**Issue by jitterbox** [aspnet/Templating#697]
When you create a new project using the Angular template, the Angular app (and its package.json) are placed within a /ClientApp folder.  But apparently Visual Studio 2017 only enumerates your NPM packages and lists them under your project Dependencies in Solution Explorer when the package.json is in the project root (?).  Same goes for the auto-detection of NPM scripts within Task Runner Explorer.

I believe that there was going to be some collaboration with the VS team to address this.

**Comment by mkArtakMSFT** [comment]
@vijayrkn, do you have any info regarding this?

**Comment by vijayrkn** [comment]
+ @jodavis

**Comment by jodavis** [comment]
@justcla is going to follow up with the template team to see how tooling can improve support for this project structure. We weren't aware the change was made to the templates until recently.

**Comment by mkArtakMSFT** [comment]
As there is no `MVC` related work here, @jitterbox I'd suggest you to open a VS feedback issue instead and that would be redirected as necessary.
Closing this issue as there is no `MVC` related work here.
