### ISSUE TITLE
Using Angular BrowserAnimationsModule throws error

### ISSUE THREAD

**Issue by kakins** [aspnet/templating#7]
I modified the app.module.browser and app.module.server as shown here:
https://github.com/aspnet/JavaScriptServices/commit/c0c47e3def208873c470a524a826f8d235a5f9de
This was a response to the following issue:
https://github.com/aspnet/JavaScriptServices/issues/1160

However when trying to add to the animations array in a component decorator, I get the error described in this issue:
https://github.com/angular/angular/issues/18562

```
ERROR TypeError: Cannot read property 'display' of undefined
...
```

Looks like this may be an Angular problem, not necessarily one with the templates?  I'm not sure what, if anything, I'm overlooking.

**Comment by kakins** [comment]
I just noticed that this is an issue with server side rendering.  So maybe not an issue with the templates per-se?

**Comment by kerocode** [comment]
same issue here

**Comment by SteveSandersonMS** [comment]
Since we moved to the new Angular CLI-based templates, the issue should no longer be applicable. If anyone is still hitting this with the Angular CLI-based template, please let us know.

**Comment by kakins** [comment]
@SteveSandersonMS when you say Angular CLI-based templates, does this include the templates that we can use in the latest Visual Studio version (15.5.6)?

**Comment by kakins** [comment]
I think I just answered my previous question, and I see these new docs:
https://docs.microsoft.com/en-us/aspnet/core/spa/angular?tabs=visual-studio

It looks like project generation has changed a bit.
