### ISSUE TITLE
Templating rant - why don't you guys just use a git repo?

### ISSUE THREAD

**Issue by jtheisen** [aspnet/Templating#708]
I just figured that the new React template is not longer Typescript, despite them having the same name as they used to have, which prompts me to go on this rant.

The ASP.NET Core templates have been quite the time waster for me so far, much unlike the classic ASP.NET VS templates that hardly ever changed.

But really I just don't get why the templates are distributed through dedicated tools such as "dotnet new" to begin with - it makes important things you want to do with it quite hard:

- You can't go back to a version you got from a previous version of dotnet new,
- you can't compare the version you get to what you got earlier so you don't really know why a template may behave differently now that you remember it did a month ago and
- you can't just fix a problem with the template and contribute it back to the community with a pull request right from the repo you checked out to use.

You could do that if the template were just git repos offered for convenient cloning.

This git repo (aspnet/Templating) contains the templates, but it's not convenient to use as the starting point for a new app directly.

For that, the templates need to live at the root of the repo. Different templates could either be in different repos or in different branches of the same repo, depending on how similar they are. In the latter case, fixes could be easily merged.

The only drawback here is that "dotnet new" also performs some replacements. But that's a) not really that important and b) you could factor that out in a separate script if you really think it needs to be there.

End of rant.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @jtheisen.
@danroth27, I'll leave this one for you to handle.

**Comment by mlorbetske** [comment]
Let's discuss the dotnet new globally applicable points over at https://github.com/dotnet/templating/issues/1652

**Comment by danroth27** [comment]
@jtheisen I can certainly understand your frustration with the amount of change with the SPA templates. Our goal with the SPA templates is to keep them up to date with the current best practices for using the various SPA frameworks (React/Angular) with ASP.NET Core. But, the client-side world changes pretty quickly, which means the SPA templates have to change rapidly to keep up. To enable using older versions of the templates we can look into shipping the template packages for the templates that ship with the .NET Core SDK. Then you could install older versions of the templates as needed. 

I'm going to go ahead and close this issue as most of the follow on discussion will happen in the https://github.com/dotnet/templating repo.
