### ISSUE TITLE
Unnecessary User.Id provided in password reset link?

### ISSUE THREAD

**Issue by tverboon** [aspnet/templating#71]
The user Id is provided in the callback link:
https://github.com/aspnet/templating/blob/a80061f42be6ba7de36f8fea35086da58e08a69b/src/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Controllers/AccountController.cs#L424

But in the controller action only code is used:
https://github.com/aspnet/templating/blob/a80061f42be6ba7de36f8fea35086da58e08a69b/src/Microsoft.DotNet.Web.ProjectTemplates.2.0/content/StarterWeb-CSharp/Controllers/AccountController.cs#L443

In my opinion it's better not to provide more information than necessary.

Copy of:  https://github.com/aspnet/Templates/issues/872

**Comment by Eilon** [comment]
Indeed, it looks like it's not needed, so we should remove it.
