### ISSUE TITLE
Unnecessary file on angular template

### ISSUE THREAD

**Issue by Amine-Smahi** [aspnet/Templating#722]
In .NET Core 2.2 preview1 the default angular template comes with a counter.component.spec.ts file witch is useless

![image](https://user-images.githubusercontent.com/24621701/44983591-9a518880-af71-11e8-8a3e-4a1e6cd0ff58.png)

**Comment by ryanbrandenburg** [comment]
This `spec` file is not useless, it provides tests (run by `ng test` from within ClientApp). It follows what's generated by the CLI and the guidance from the [Angular docs](https://angular.io/guide/testing#test-file-name-and-location). In fact, to reflect what's generated by the Angular CLI when you do `ng generate component <componentName>` we should add `.spec.ts` files on the other components too. Our guiding star on the SPA templates is to follow the accepted standards of the individual frameworks, so this one is "as intended".
