### ISSUE TITLE
How to Scaffold Identity UI in ASP.NET Core 2.2 preview1

### ISSUE THREAD

**Issue by Amine-Smahi** [aspnet/Templating#723]
In ASP.NET Core 2.1 we had the chance to use scaffold using visual studio like this

![image](https://user-images.githubusercontent.com/24621701/45003154-48dbe480-afd7-11e8-9085-a67371374fb1.png)

But now in ASP.NET Core 2.2 preview1 the new scaffold item is missing in visual studio 

![image](https://user-images.githubusercontent.com/24621701/45003175-88a2cc00-afd7-11e8-8892-995109ee7ae8.png)

**Comment by mkArtakMSFT** [comment]
This issue was moved to aspnet/Scaffolding#867
