### ISSUE TITLE
Swap "webapp" for "razor" in template list

### ISSUE THREAD

**Issue by guardrex** [aspnet/Templating#726]
Related: https://github.com/aspnet/Templating/issues/325

In the list of templates provided by `dotnet new list`/`dotnet new --help`, the Razor Pages template shows with the **razor** name. We're documenting **webapp** everywhere in aspnet/Docs. Therefore, we have a mismatch between what the docs call for devs to type and what the template list shows.

Would it be possible to swap them? ... Make the template name **webapp** (for the list) and make the alias (not seen) **razor**?

Alternatively, could the `dotnet new` command list template names and aliases together in the output, perhaps as a a comma-delimited list when aliases are available?

cc @Rick-Anderson @scottaddie

**Comment by mkArtakMSFT** [comment]
Yes, `webapp` is indeed an alias for `razor`.
The ask, though is reasonable.
@ryanbrandenburg, let's do this in `preview3`.

**Comment by Rick-Anderson** [comment]
Any change you could go back to the 2.1 version of the razor templates with Index/about/contact in lieu of the new version with page1, page2 and no layout.

**Comment by ryanbrandenburg** [comment]
@Rick-Anderson what exactly are you asking there, you just want us to revert all the work we did for 2.2 template visuals?

**Comment by Rick-Anderson** [comment]
The 2.2 Razor Pages templates are radically different from 2.1 templates- is that correct? Is there a good reason for the change? That's a major impact to our documentation pages.

**Comment by danroth27** [comment]
@Rick-Anderson Yes, that is expected. As part of updating from Bootstrap 3 to Bootstrap 4 we decided to do a UI refresh on our templates. We understand that this has a major impact on the docs. This kind of change isn't something we should do frequently, but with the move to Boostrap 4 it seemed appropriate.

**Comment by Rick-Anderson** [comment]
@danroth27 thanks. They look much simpler than the previous templates so that should be a win for everyone - once we get them documented. I'll get the work scheduled.
