### ISSUE TITLE
Change the default `password reset` to off

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Templating#728]

**Comment by ryanbrandenburg** [comment]
By this are your referring to [these](https://github.com/aspnet/Templating/blob/release/2.2/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/.template.config/template.json#L150)?
If so it's still unclear to me what the correct `"defaultValue":` is. Is there more context about this somewhere?

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please handle this? Thanks!
