### ISSUE TITLE
.NET 4.7x Framework pages are started with Workstation GC

### ISSUE THREAD

**Issue by Tratcher** [aspnet/templating#73]
_From @Tornhoof on October 18, 2017 9:0_

In the old DNX the pages were started with Server.GC, due to an issue with https://github.com/dotnet/project-system/issues/2896 the appropriate project setting is ignored for netfx.
It might be more useful to have the default GC set to server as it was in the old DNX.

# Steps to reproduce:
1. Create Webpage for ASP.NET Core 2.0 and target Framework 4.7.x
2. Run in IIS
3. Log the GC type
# Expected Result
Server GC
# Actual Result
Workstation GC

This bug is kinda annoying because the performance characteristics of Server GC vs. Workstation GC are quite different on server systems.

Repro:
[WrongDefault.zip](https://github.com/aspnet/IISIntegration/files/1394003/WrongDefault.zip)

_Copied from original issue: aspnet/IISIntegration#452_

**Comment by Tratcher** [comment]
GC is an app configuration, it's unrelated to IIS / the launcher. The default is controlled by the runtime, though perhaps it could be influenced by the SDK.

Adding an app.config file to your project with the following should help.
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/gcserver-element

We should update the template to include this.

**Comment by Tornhoof** [comment]
Ah I understand, I need to edit the .config (or actually add the .config) of the actual web application and not the web.config. Thank you very much, that solves my problem.

**Comment by Eilon** [comment]
Indeed, all the .NET Framework flavors of the projects should set it to the Server GC.

**Comment by DamianEdwards** [comment]
@Eilon this should be considered for a servicing release of 2.0.x and 1.0.x/1.1.x

**Comment by Eilon** [comment]
Logged these to track patch work items:
* 1.0 patch: https://github.com/aspnet/templating/issues/172
* 1.1 patch: https://github.com/aspnet/templating/issues/171
* 2.0 patch: https://github.com/aspnet/templating/issues/170

**Comment by Eilon** [comment]
(And this item will be for `dev`)

**Comment by jbagga** [comment]
@Tratcher Will an app.config need to be added to ALL templates? Or is this specific to certain types? I can look into it, but just wondering if I should be expecting different results with the current configurations.

**Comment by Tratcher** [comment]
All web templates, but only for the .NET 4.x targeted ones.
