### ISSUE TITLE
Web Site project template

### ISSUE THREAD

**Issue by rendmath** [aspnet/templating#74]
Is there a way to create a "Web Site" project from the dotnet CLI?

By "Web Site", I mean the kind of no-csproj project that can be created in Visual Studio, for example.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this. All .NET Core projects are based on the CSPROJ project system (which is new and improved compared to the previous CSPROJ!).

**Comment by rendmath** [comment]
In my experience, Web Sites are particularly useful for working on non-.NET source code, such as SPAs. Do you see any practical alternative to make an arbitrary folder hierarchy available from the Solution Explorer in Visual Studio?

**Comment by Eilon** [comment]
The new CSPROJ format supports better globbing than the previous CSPROJ files, which might help you get what you want. You might need to mark the project as non-buildable in some manner (you'd need to ask some MSBuild experts on that, though).
