### ISSUE TITLE
Improve SPA template startup time

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#746]
When a SPA template launches it can take a really long time to restore the NPM package, compile the JavaScript and generally be ready to use. It would be really nice (though possibly impossible) to improve the turnaround time here.

**Comment by ryanbrandenburg** [comment]
I'm under the impression the answer here is "There's nothing to be done." But considering how slow they are I think it's worth spending the time to confirm that.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, do you have any ideas about what we can do regarding this? Any suggestions?

**Comment by SteveSandersonMS** [comment]
Yes, [we have a long-term plan to solve this](https://blazor.net/).

Apologies, couldn't resist. Less flippantly, I don't have a good suggestion, as virtually all the setup time comes down to restoring NPM packages. We could make more of an effort to use `yarn` for people who have that installed on their machines, but that's not standard for Node environments so it wouldn't benefit everyone, nor is consistent with having VS do package restoration.

**Comment by mkArtakMSFT** [comment]
Ok, thanks guys. Seems like the only thing I can do is close this for now.
