### ISSUE TITLE
Individual accounts auth template produces migrations not supported by SQLite

### ISSUE THREAD

**Issue by hoppyluke** [aspnet/templating#75]
I'm getting an error when creating a new MVC web app using individual user accounts. After scaffolding, there are pending EF changes. The migration created by these changes is not supported by SQLite since it involves adding a foreign key.

I'm using the following commands to scaffold the app:

```
dotnet new mvc --auth Individual
dotnet ef migrations add IdentityExtraChanges
dotnet ef database update
```

The database update results in the error: *SQLite does not support this migration operation ('AddForeignKeyOperation').*

The migration that EF wants to create is:

```csharp
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.DropIndex(
        name: "IX_AspNetUserRoles_UserId",
        table: "AspNetUserRoles");

    migrationBuilder.DropIndex(
        name: "RoleNameIndex",
        table: "AspNetRoles");

    migrationBuilder.CreateIndex(
        name: "RoleNameIndex",
        table: "AspNetRoles",
        column: "NormalizedName",
        unique: true);

    // Not supprted by SQLite:
    migrationBuilder.AddForeignKey(
        name: "FK_AspNetUserTokens_AspNetUsers_UserId",
        table: "AspNetUserTokens",
        column: "UserId",
        principalTable: "AspNetUsers",
        principalColumn: "Id",
        onDelete: ReferentialAction.Cascade);
}
```
This might be related to #62?

**Comment by Eilon** [comment]
@bricelam / @ajcvickers / @divega - what should the behavior here be for SQLite?

**Comment by bricelam** [comment]
The Migrations behavior is as expected. The templates should be up-to-date (issue #62) and not include these additional changes to the Identity schema when a new migration is added.

**Comment by hoppyluke** [comment]
Thanks for confirming. I'll close this as a duplicate of #62.
