### ISSUE TITLE
Adding component to React Redux ASP.NET Core React template

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Templating#750]
Moved from https://github.com/aspnet/Docs/issues/8471. Originally opened by @KevinBurton.

> I am trying to add components to my simple test project and I am getting an error (squiggly red line) that indicates:
> 
> [ts]
> Type '{}' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes&lt;TitleDescription&gt; & Readonly&lt;{ children?: ReactNod...'.
>   Type '{}' is not assignable to type 'Readonly&lt;TitleDescriptionProps&gt;'.
>     Property 'itemId' is missing in type '{}'.
> 
> I am having a hard time tracing where the type {} is defined.
> 
> Thank you.
> 
> Kevin
> 
> ---
> #### Document Details
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> * ID: 7264db1b-55ec-e419-d2c4-bd4fe64922a2
> * Version Independent ID: 720995d2-006a-3573-4868-d253c8a2acc7
> * Content: [Use the React-with-Redux project template with ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/react-with-redux?view=aspnetcore-2.1)
> * Content Source: [aspnetcore/client-side/spa/react-with-redux.md](https://github.com/aspnet/Docs/blob/master/aspnetcore/client-side/spa/react-with-redux.md)
> * Product: **aspnet-core**
> * GitHub Login: @SteveSandersonMS
> * Microsoft Alias: **scaddie**

**Comment by mkArtakMSFT** [comment]
@KevinBurton, did you get your question answered on StackOverflow? Should this issue be closed or do you still need help from us?

**Comment by KevinBurton** [comment]
Not yet thank you.

**Comment by mkArtakMSFT** [comment]
It would be useful to have a small repro project.

**Comment by KevinBurton** [comment]
I need the steps needed to add a component.

**Comment by tpetrina** [comment]
It is rather simple. In a fresh project, add a new file named `MyComponent.js` to `/ClientApp/src/components` with the following content:

```js
import React from "react";
import { connect } from "react-redux";

const MyComponent = () => (
  <div>
    <h1>My component</h1>
  </div>
);

export default connect()(MyComponent);
```

And in the `Home.js` file add `import MyComponent from './MyComponent';` as the second line. After `</h1>` add `<MyComponent />` and it should work.

If you have something nontrivial, we need your code to see what you did differently. Especially since your error is _TypeScript_ which is not supported in this template.

**Comment by KevinBurton** [comment]
Yet all the components in the template are defined with .tsx and .ts.
Getting all the types right seems to be where the bulk of the work is.
Finding the right combination for the component (tsx), the state (ts) and
the dispatch actions (ts) has some how eluded me so far on all but the
simplest components. A good annotated example of an added component that
“reacts” to state changes, accesses state props, invokes /dispatches
actions that change the state, and some explanations on what is needed to
properly define an action. That would be really helpful.
Thank you.

**Comment by SteveSandersonMS** [comment]
@KevinBurton It sounds like you're using the older (pre-ASP.NET Core 2.1) templates. The latest React+Redux template is closer to the original create-react-app (CRA) output and hence is `.js`/`.jsx` only. This is discussed elsewhere on the issue tracker here if you want to search to find more discussion about it.

If you want to continue using the older template with `.tsx`, then it already contains an example of a component that does all the things you mention: the FetchData component. I'm sure you've seen that so I'm not clear on what other example you'd be looking for.

**Comment by tpetrina** [comment]
@KevinBurton as @SteveSandersonMS says you are using an older version of templates. I can help you in that regard, but that template is considered archived and not to be used. If you want to use TypeScript with CRA and ASP.NET Core, you have to jump through some hoops.

**Comment by KevinBurton** [comment]
Thank you. I was just using the template that was available with VS 2017. I
wasn’t aware that it was “old”. How do I get the new version?

**Comment by tpetrina** [comment]
Which version of .NET Core are you running? Can you run in console:

```dotnet --version```

And also ```dotnet new reactredux -o C:\temp\rrtest``` to see what is actually created?

**Comment by KevinBurton** [comment]
PS C:\Users\Kevin> dotnet --version
2.1.200
PS C:\Users\Kevin>

This also creates .tsx components with .ts store and state (uses TypeScript)

**Comment by mkArtakMSFT** [comment]
@KevinBurton, you should be on at least 2.1.300 to get the new templates. Just update to the latest SDK (2.1.403).
