### ISSUE TITLE
[VS2017]Angular-CLI 6 not working on ASP.NET Core with Angular 5.2 project

### ISSUE THREAD

**Issue by tkumark** [aspnet/Templating#758]
I create default Asp.net Core Angular project. Is it possible to used Angular -CLI 6 with Angular 5.2. I did try a bit with by updated the version of typescript and angular cli version in package.json and added angualr.json but still ran it not issues.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @tkumark.
As far as I know, ASP.NET Core has no limitations in terms of the mentioned compatibility. The https://github.com/angular/angular-cli would be a better place to ask this question.

@SteveSandersonMS, please correct me if I'm wrong.

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT I agree with your comments.

@tkumark The easiest way to use Angular 6 with ASP.NET Core will be to use the updated Angular template that will ship in ASP.NET Core 2.2. In the meantime you could compare your implementation with [our sources](https://github.com/aspnet/Templating/tree/master/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp) to figure out the differences.
