### ISSUE TITLE
/Properties/launchSettings.json should be removed from .gitignore in template content files

### ISSUE THREAD

**Issue by kasajian** [aspnet/Templating#760]
The following files should be updated and /Properties/launchSettings.json should be removed:

        Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/React-CSharp/.gitignore
        Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/.gitignore
        Templating/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/ReactRedux-CSharp/.gitignore

The justification is described here:
        https://github.com/github/VisualStudio/issues/1405

And here's the actual change made to "VisualStudio.gitignore" @ https://github.com/github/gitignore
        https://github.com/github/gitignore/pull/2705

**Comment by SteveSandersonMS** [comment]
@ryanbrandenburg I agree. These SPA templates should be the same as our other ASP.NET Core templates in terms of whether `launchSettings.json` is gitignored or not.
