### ISSUE TITLE
ASP.NET Core Web App | .NET Framework | ASP.NET Core 2.1 | Web Application template issue

### ISSUE THREAD

**Issue by seancpeters** [aspnet/Templating#767]
When I create a new project in VS with this configuration:
- ASP.NET Core Web App 
- .NET Framework 
- ASP.NET Core 2.1 
- Web Application

The package versions cause a NuGet restore error:
```
Error	NU1605	Detected package downgrade: Microsoft.AspNetCore.Hosting from 2.1.2 to 2.1.1. Reference the package directly from the project to select a different version. 
 WebApplication208 -> Microsoft.AspNetCore 2.1.4 -> Microsoft.AspNetCore.Server.Kestrel 2.1.3 -> Microsoft.AspNetCore.Hosting (>= 2.1.2) 
 WebApplication208 -> Microsoft.AspNetCore 2.1.4 -> Microsoft.AspNetCore.Hosting (>= 2.1.1)	
```

Here is a .csproj file from the project with this issue:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <UserSecretsId>aspnet-WebApplication208-B1DBF9F7-91DD-4C54-9477-614FBA26C82C</UserSecretsId>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.4" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.CookiePolicy" Version="2.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.1"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.4" PrivateAssets="All" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.5" PrivateAssets="All" />
  </ItemGroup>

</Project>
```

I cleared all my NuGet caches just before creating this project and encountering the issue, to avoid a false positive.

Note: I receive the same error whether selecting No Auth or Individual Auth.

**Comment by Eilon** [comment]
@natemcmaster - any idea?

**Comment by natemcmaster** [comment]
Looks like the same issue we discussed in https://github.com/aspnet/Templating/issues/753. I haven't been able to reproduce this on my own.

**Comment by seancpeters** [comment]
@natemcmaster - I agree, it does seem similar, but I am consistently reproducing this error.

**Comment by natemcmaster** [comment]
Just tried it on my laptop. No repro  ¯\\\_(ツ)\_/¯. I wonder if there is something running on your box that messes with the NuGet cache.

**Comment by mkArtakMSFT** [comment]
@seancpeters, did you try to clean the NuGet cache a is suggested in the referenced issue?
@natemcmaster, you can sync up with @seancpeters and see what's going on his machine.

**Comment by seancpeters** [comment]
Yes, I cleared my nuget cache just before repro'ing. I have just tried again:
- Clear all nuget cachge
- Create new project with the same configuration as mentioned above.
Same error occurs.

But, after messing around with my nuget sources, I have found a configuration where the error does not occur.
