### ISSUE TITLE
Need some samples to implement pre-rendering (isomorphism) in React

### ISSUE THREAD

**Issue by gfox1984** [aspnet/Templating#768]
From what I read on the Internet, the template for the react + redux app from [the old repository](https://github.com/aspnet/JavaScriptServices/tree/master/templates) used to implement pre-rendering on server side. 

It is now impossible to find any example of a react app that uses pre-rendering on Asp.Net core (2.1).

Please include this to the react + redux template, or create a new project that implements pre-rendering.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @gfox1984.
The new template is well aligned with how the `create-react-app` tool generates the project. At the moment, the tool doesn't have support for prerendering. We'll consider supporting it after the CLI will be updated to support pre-rendering.

**Comment by gfox1984** [comment]
How about creating a new template whose purpose would be to demonstrate pre-rendering in a simple react + redux app? I haven't been able to find any example on the internet that used the official release of Asp.Net core 2.1 (the only few examples where for RC, and they were advising you to use the now defunct aspnetcore-spa generator...)

**Comment by iJzFan** [comment]
@gfox1984 Here is a react prerendering template.
[ReactCoreTemplate](https://github.com/JiarongGu/ReactCoreTemplate)
