### ISSUE TITLE
Remove Bower even harder from the 2.1 templates

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#77]
In https://github.com/aspnet/templating/issues/48 we mostly removed the remnants of Bower from the templates, but a few Bower-related files are still there.

We should remove everything that's left from the 2.1 templates.

**Comment by SteveSandersonMS** [comment]
@eilon In #48 I removed Bower-related artifacts from the project with the deliberate exception of not messing with the internal structure of the package directories themselves.

The idea was that these package directories are opaque structures provided by a third party, and in case developers want ways of upgrading or changing versions, it will make the most sense if they were still in their original form so it's clear where the files came from, what exact version of them you have, and what you could replace with an alternate version.

So if you are definitely keen to remove the `wwwroot\lib\<packagename>\.bower.json` files then we can, but there's a good case that they are providing some value at very little cost (explaining where the files came from and why they are organised how they are). Of course, this is all going to change again when we move to a different package system soon.

**Comment by Eilon** [comment]
Oh, duh, this totally makes sense. I don't think we should change the contents of packages because it'll just cause problems down the road. So, closing this issue.

cc @DamianEdwards FYI.
