### ISSUE TITLE
Update `unshiftio/url-parse` dependency

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Templating#773]
We have the dependency here: https://github.com/aspnet/Templating/blob/master/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/Angular-CSharp/ClientApp/package-lock.json

**Comment by ryanbrandenburg** [comment]
Done! If we could figure out how it is that you see those warnings on GitHub and set it up so I see them too that would be super helpful.
