### ISSUE TITLE
All tags with an integrity attribute should have "crossorigin="anonymous""

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#781]
Fixed by #779.

**Comment by javiercn** [comment]
What's the reasoning behind this?

**Comment by ryanbrandenburg** [comment]
Without it we get errors like:
`Subresource Integrity: The resource 'https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.
`
