### ISSUE TITLE
npm ERR! peer dep missing

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Templating#784]
To my knowledge the messages [as seen here](https://github.com/aspnet/Release/issues/322#issuecomment-430387094) have been this way for at least a couple releases, but it would be nice to either add these dependencies or silence the warnings depending on which is cleaner/better.

**Comment by ryanbrandenburg** [comment]
CC @SteveSandersonMS, do you have a bit more history or knowledge of these?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, why are the references missing? Are we downgrading any transitive dependency somewhere?

**Comment by ryanbrandenburg** [comment]
More on peer dependencies in node/npm [here](https://nodejs.org/en/blog/npm/peer-dependencies/) but the basic idea is that if an npm package defines a peer dependency the referencing package provides it rather than being automatically included. The idea is to prevent dependency graphs like:
```
├── winston@0.6.2
└─┬ winston-mail@0.2.3
  └── winston@0.5.11
```
Again, our templates function like we want them to even with these messages, but we want to understand this a bit better to ensure we're not setting end users up for trouble when they start adding functionality.

**Comment by SteveSandersonMS** [comment]
Our NPM dependencies should be a superset of those used by the underlying SPA frameworks. For example, in the Angular template, we should have all the same dependencies as the equivalent Angular CLI project does, plus a few extras to support our enhancements.

As such I don't think we should have any missing peer dependencies, except if Angular CLI projects also do.
