### ISSUE TITLE
Published apps from MVC, Razor and WebApp projects are incomplete

### ISSUE THREAD

**Issue by dougbu** [aspnet/Templating#786]
#### Repro steps
1. `dotnet new mvc --output mvc`
2. `cd mvc`
3. `dotnet publish`
4. `cd bin/Debug/netcoreapp2.2/publish/`
5. `dotnet mvc.dll`
##### Expected
Similar UI to what `dotnet run` in the project directory provides:
![image](https://user-images.githubusercontent.com/6431421/47064366-03910200-d194-11e8-84b8-a502be31680a.png)
##### Actual
Banners and so on are broken:
![image](https://user-images.githubusercontent.com/6431421/47064083-d8f27980-d192-11e8-8b9c-86865826812e.png)

Found while verifying: aspnet/Release#322

**Comment by mkArtakMSFT** [comment]
Thanks @dougbu.
This is a known issue, which is tracked here: https://github.com/aspnet/Templating/issues/781
