### ISSUE TITLE
IEmailSender should have explicitly named parameters for html vs plain text

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#79]
_From @joeaudette on September 27, 2017 14:32_

There have been a number of people reporting bugs about the email confirmation link in the StarterWeb template not working.

This is happening because people implement IEmailSender and don't realize that the message being passed in is html. When they send the email as plain text the confirmation link does not work because of the url encoding.

I think the "message" parameter of SendEmailAsync should be renamed to htmlMessage and possibly should have an additional parameter for "plainTextMessage" and both should be passed in from AccountController.

This would make it more clear to implementors of IEmailSender what kind of string(s) they are dealing with and how to correctly implement it.

related issues:
https://github.com/aspnet/Home/issues/2152
https://github.com/aspnet/Home/issues/2217

_Copied from original issue: aspnet/Templates#868_

**Comment by jbagga** [comment]
@Eilon What would be the value of having another parameter "plainTextMessage"? If we do the conversion from plain text to html if htmlMessage is not provided, I can see it being useful. But is that really a scenario that should be supported?

**Comment by Eilon** [comment]
Hmm good point. Maybe just rename the existing parameter to be clearer about what it is? I don't think we need 2 parameters because then it's confusing which one to use and what happens if you use both.

So, does the current parameter expect it to be a string containing HTML, as in, `<div>This is a confirmation <b>email</b>!</div>`?

**Comment by jbagga** [comment]
Yeah something like this
`Please confirm your account by <a href='<link>'>clicking here</a>.`

**Comment by Eilon** [comment]
Yeah then I think just rename the existing parameter is all we need.

**Comment by jbagga** [comment]
I changed the parameter names in `IEmailSender` and `EmailSender`. Will send a PR out soon. I noticed that we do not encode the link for `ForgotPassword` in `AccountController` [here](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Areas/Identity/Controllers/AccountController.cs#L377) but perhaps we should like we do [here](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/content/StarterWeb-CSharp/Areas/Identity/Extensions/EmailSenderExtensions.cs#L15)
