### ISSUE TITLE
Issue with Angular 7 on Docker

### ISSUE THREAD

**Issue by eSPiYa** [aspnet/Templating#830]
Creating a new ASP.NET Core with Angular project then adding Docker support after, works fine by installing Node.js through the dockerfile:
```
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
# Setup NodeJs
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_11.x | bash - && \
    apt-get install -y build-essential nodejs
# End setup
WORKDIR /app
EXPOSE 80
```
Upgrading the Angular from 5 to 6 to 7 works with this setup. Deleting the ClientApp then re-create it with Angular 6(tested 6.2.7) works fine with Docker too. But re-creating the ClientApp with Angular 7(7.0.5), I can only see a page with "Cannot GET /" message written on it.

Looking at the output window, there is no error message. Though there are 4 lines of "realpath(): Invalid argument" in the beginning.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @eSPiYa.
We haven't yet brought support for Angular 7 to our templates, but it's something we plan to handle as part of https://github.com/aspnet/Templating/issues/694.
