### ISSUE TITLE
What is the markdown syntax for templating

### ISSUE THREAD

**Issue by cilerler** [aspnet/Templating#838]
I have a [.NET Core template](https://github.com/cilerler/burcin/blob/master/dist/.template.config/template.json) and wondering how I can hide partial content from markdown file based on the flags set?  

As you may see below I tried what I do in CS project files but it didn't work.

## README.md

```
# Steps

- createSolutionFile.ps1

<!--#if (CacheSqlServer)-->
- sql-cache.ps1
    1. create database `DistributedCache`
    2. create schema `cache`
    3. run the script
<!-- #endif -->

- user-secrets.ps1

<!--#if (EntityFramework)-->
- scaffold.ps1
- migrate.ps1 
<!-- #endif -->

- build.ps1

<!--#if (WindowsService)-->
- windows-service.ps1
<!-- #endif -->
```

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg can you please answer this question when you'll get time? Thanks!

**Comment by cilerler** [comment]
Based on answer @poke provided in [StackOverflow](https://stackoverflow.com/a/53432496/439130) adding code below into **template.json** solves the issue.

```json
"SpecialCustomOperations": {
  "**/*.md": {
    "operations": [
      {
        "type": "conditional",
        "configuration": {
            "if": ["<!--#if"],
            "else": ["<!--#else"],
            "elseif": ["<!--#elseif", "<!--#elif"],
            "endif": ["<!--#endif"],
            "trim": "true",
            "wholeLine": "true"
        }
      }
    ]
  }
}
```
