### ISSUE TITLE
Core MVC template database file name starts with a backslash on Linux/Mac

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#85]
_From @DesktopMan on April 14, 2017 22:36_

From the template's appsettings.json:

```
"DefaultConnection": "DataSource=.\\test.db"
```
This has two presumably unintentional consequences: The file becomes hidden and the name starts with a backslash. My students had trouble finding the file to inspect it until I pointed this out.

_Copied from original issue: aspnet/Templates#840_

**Comment by seancpeters** [comment]
It appears that othing needs to be done for this issue. From the history & references of the related issues, it appears this was fixed back in June in this PR: https://github.com/dotnet/templating/pull/904

Looking through this repo, all the appsettings.json files in StarterWeb templates have their default connections setup as `"DefaultConnection": "DataSource=app.db"`

@Eilon - if there is anything else that needs to be done, please let me know.

**Comment by Eilon** [comment]
@seancpeters ah yes that appears to be the case, so closing this.
