### ISSUE TITLE
Remove UseIISIntegration from the templates, use lightup instead

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#86]
_From @Tratcher on April 4, 2017 3:1_

Once the following work items are complete we can remove UseIISIntegration from the templates and have it use automatic lightup instead.
https://github.com/aspnet/IISIntegration/issues/348
https://github.com/aspnet/AspNetCoreModule/issues/81

_Copied from original issue: aspnet/Templates#837_

**Comment by Tratcher** [comment]
This is no longer required. UseIISIntegration was built into CreateDefaultBuilder so there's minimal concern of taking up space in the template.
https://github.com/aspnet/MetaPackages/blob/afee0de3e416f8e2807c7d49ad2bdef5016dae5f/src/Microsoft.AspNetCore/WebHost.cs#L185
