### ISSUE TITLE
Remove PackageTargetFallback from Web Templates 

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#87]
_From @vijayrkn on March 8, 2017 17:40_

Moving this issue to the templates repro: https://github.com/aspnet/websdk/issues/76

_Copied from original issue: aspnet/Templates#833_

**Comment by Eilon** [comment]
I think this is already done because I can't seem to find any mentions of `PackageTargetFallback`, but can you double check? If it's gone, close it. If it's there, fix then close.

**Comment by jbagga** [comment]
I didn't find any either. Closing this issue.
