### ISSUE TITLE
Remove usage of ApplicationException from all templates

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#9]
This exception type is not recommended by MSDN because it carries no meaning (you might as well throw Exception).

For each current usage we need to either:
1. Ideally stop throwing an exception (e.g. return an MVC action result, or propagate errors some other way)
2. If (1) isn't an option, throw a more appropriate (and meaningful) exception type

**Comment by jbagga** [comment]
After merging #204 all instances of ApplicationException have been removed from this repo
