### ISSUE TITLE
Consider removing Microsoft.EntityFrameworkCore.Design as an explict package reference

### ISSUE THREAD

**Issue by Eilon** [aspnet/templating#99]
_From @phenning on January 10, 2017 17:53_

This gets brought in by Microsoft.EntityFrameworkCore.Tools. Make sure this works for both 1.0.3 and 1.1 versions of the package

_Copied from original issue: aspnet/Templates#786_

**Comment by Eilon** [comment]
@bricelam / @ajcvickers - any thoughts on this? Not sure if this still applies to 2.1 (not looking to patch any older versions).

These are examples of the places where the reference exists:
* https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/StarterWeb-CSharp.csproj.in
* https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.ProjectTemplates/RazorPagesWeb-CSharp.csproj.in

In both cases it's in use only when targeting .NET Framework.

**Comment by bricelam** [comment]
You don't need it if you reference `Microsoft.EntityFrameworkCore.Tools`. It's always been that way and probably always will be that way.
